/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ForwardAgentAddress;

/**
 * The forwarding agent is the company or person acting as agent in the trans-shipping of freight to the destination country or territory.  Applicable for EEI form only.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ContactsForwardAgent {
  @JsonProperty("CompanyName")
  private String companyName = null;

  @JsonProperty("TaxIdentificationNumber")
  private String taxIdentificationNumber = null;

  @JsonProperty("Address")
  private ForwardAgentAddress address = null;

  public ContactsForwardAgent companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Company Name or the Individual name of the Forwarding agent.  Applicable for EEI form only.
   * @return companyName
  **/
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public ContactsForwardAgent taxIdentificationNumber(String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
    return this;
  }

   /**
   * Tax ID of the Forwarding agent. Valid Values: (Below values are applicable for EEIFilingOption Code &#x3D;3) 94-308351500  13-168669100     Applicable for EEI form only.
   * @return taxIdentificationNumber
  **/
  public String getTaxIdentificationNumber() {
    return taxIdentificationNumber;
  }

  public void setTaxIdentificationNumber(String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
  }

  public ContactsForwardAgent address(ForwardAgentAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public ForwardAgentAddress getAddress() {
    return address;
  }

  public void setAddress(ForwardAgentAddress address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactsForwardAgent contactsForwardAgent = (ContactsForwardAgent) o;
    return Objects.equals(this.companyName, contactsForwardAgent.companyName) &&
        Objects.equals(this.taxIdentificationNumber, contactsForwardAgent.taxIdentificationNumber) &&
        Objects.equals(this.address, contactsForwardAgent.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, taxIdentificationNumber, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactsForwardAgent {\n");
    
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    taxIdentificationNumber: ").append(toIndentedString(taxIdentificationNumber)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
