/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ProducerAddress;
import com.ups.wwwcie.api.client.ProducerPhone;

/**
 * Information of the producer. The NAFTA Certificate of Origin must be completed, signed, and dated by the exporter.  When the Certificate is completed by the producer for use by the exporter, it must be completed, signed, and dated by the producer. The date must be the date the Certificate was completed and signed.  Applies to NAFTA CO.  Required for NAFTA CO forms.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ContactsProducer {
  @JsonProperty("Option")
  private String option = null;

  @JsonProperty("CompanyName")
  private String companyName = null;

  @JsonProperty("TaxIdentificationNumber")
  private String taxIdentificationNumber = null;

  @JsonProperty("Address")
  private ProducerAddress address = null;

  @JsonProperty("AttentionName")
  private String attentionName = null;

  @JsonProperty("Phone")
  private ProducerPhone phone = null;

  @JsonProperty("EMailAddress")
  private String emailAddress = null;

  public ContactsProducer option(String option) {
    this.option = option;
    return this;
  }

   /**
   * The text associated with the code will be printed in the producer section instead of producer contact information.  Use attached List if more than one producer&#x27;s good is included on the Certificate, attach a list of additional producers, including the legal name, address (including country or territory), and legal tax identification number, cross-referenced to the goods described in the Description of Goods field.  Applies to NAFTA CO.   Valid values:  01 - AVAILABLE TO CUSTOMS UPON REQUEST 02 - SAME AS EXPORTER 03 - ATTACHED LIST 04 - UNKNOWN
   * @return option
  **/
  public String getOption() {
    return option;
  }

  public void setOption(String option) {
    this.option = option;
  }

  public ContactsProducer companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Company Name or the Individual name of the Producer.  Applies to NAFTA CO.  Only applicable when producer option is empty or not present. Conditionally required for: NAFTA CO, when Producer option is not specified.
   * @return companyName
  **/
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public ContactsProducer taxIdentificationNumber(String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
    return this;
  }

   /**
   * Tax ID of the Producer.  Applies to NAFTA CO. Only applicable when producer option is empty or not present
   * @return taxIdentificationNumber
  **/
  public String getTaxIdentificationNumber() {
    return taxIdentificationNumber;
  }

  public void setTaxIdentificationNumber(String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
  }

  public ContactsProducer address(ProducerAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public ProducerAddress getAddress() {
    return address;
  }

  public void setAddress(ProducerAddress address) {
    this.address = address;
  }

  public ContactsProducer attentionName(String attentionName) {
    this.attentionName = attentionName;
    return this;
  }

   /**
   * Contact name at the Producer location.  Applies to NAFTA CO.
   * @return attentionName
  **/
  public String getAttentionName() {
    return attentionName;
  }

  public void setAttentionName(String attentionName) {
    this.attentionName = attentionName;
  }

  public ContactsProducer phone(ProducerPhone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public ProducerPhone getPhone() {
    return phone;
  }

  public void setPhone(ProducerPhone phone) {
    this.phone = phone;
  }

  public ContactsProducer emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Producer email address.  Applies to NAFTA CO.
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactsProducer contactsProducer = (ContactsProducer) o;
    return Objects.equals(this.option, contactsProducer.option) &&
        Objects.equals(this.companyName, contactsProducer.companyName) &&
        Objects.equals(this.taxIdentificationNumber, contactsProducer.taxIdentificationNumber) &&
        Objects.equals(this.address, contactsProducer.address) &&
        Objects.equals(this.attentionName, contactsProducer.attentionName) &&
        Objects.equals(this.phone, contactsProducer.phone) &&
        Objects.equals(this.emailAddress, contactsProducer.emailAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(option, companyName, taxIdentificationNumber, address, attentionName, phone, emailAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactsProducer {\n");
    
    sb.append("    option: ").append(toIndentedString(option)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    taxIdentificationNumber: ").append(toIndentedString(taxIdentificationNumber)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    attentionName: ").append(toIndentedString(attentionName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
