/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.UPSFiledPOA;

/**
 * Indicates the EEI UPS Filed option. (option 3)  Applicable for EEI form.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class EEIFilingOptionUPSFiled {
  @JsonProperty("POA")
  private UPSFiledPOA POA = null;

  public EEIFilingOptionUPSFiled POA(UPSFiledPOA POA) {
    this.POA = POA;
    return this;
  }

   /**
   * Get POA
   * @return POA
  **/
  public UPSFiledPOA getPOA() {
    return POA;
  }

  public void setPOA(UPSFiledPOA POA) {
    this.POA = POA;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EEIFilingOptionUPSFiled eeIFilingOptionUPSFiled = (EEIFilingOptionUPSFiled) o;
    return Objects.equals(this.POA, eeIFilingOptionUPSFiled.POA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(POA);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EEIFilingOptionUPSFiled {\n");
    
    sb.append("    POA: ").append(toIndentedString(POA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
