/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.HandlingUnitsDimensions;
import com.ups.wwwcie.api.client.HandlingUnitsType;

/**
 * Handling Unit for Density based rating container.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class FreightDensityInfoHandlingUnits {
  @JsonProperty("Quantity")
  private String quantity = null;

  @JsonProperty("Type")
  private HandlingUnitsType type = null;

  @JsonProperty("Dimensions")
  private HandlingUnitsDimensions dimensions = null;

  public FreightDensityInfoHandlingUnits quantity(String quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Handling Unit Quantity for Density based rating.
   * @return quantity
  **/
  public String getQuantity() {
    return quantity;
  }

  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }

  public FreightDensityInfoHandlingUnits type(HandlingUnitsType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public HandlingUnitsType getType() {
    return type;
  }

  public void setType(HandlingUnitsType type) {
    this.type = type;
  }

  public FreightDensityInfoHandlingUnits dimensions(HandlingUnitsDimensions dimensions) {
    this.dimensions = dimensions;
    return this;
  }

   /**
   * Get dimensions
   * @return dimensions
  **/
  public HandlingUnitsDimensions getDimensions() {
    return dimensions;
  }

  public void setDimensions(HandlingUnitsDimensions dimensions) {
    this.dimensions = dimensions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FreightDensityInfoHandlingUnits freightDensityInfoHandlingUnits = (FreightDensityInfoHandlingUnits) o;
    return Objects.equals(this.quantity, freightDensityInfoHandlingUnits.quantity) &&
        Objects.equals(this.type, freightDensityInfoHandlingUnits.type) &&
        Objects.equals(this.dimensions, freightDensityInfoHandlingUnits.dimensions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, type, dimensions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FreightDensityInfoHandlingUnits {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
