/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.TransportationChargesDiscountAmount;
import com.ups.wwwcie.api.client.TransportationChargesGrossCharge;
import com.ups.wwwcie.api.client.TransportationChargesNetCharge;

/**
 * Transportation charges container. Ground Freight Pricing transportation charges. These are only returned for Ground Freight Pricing enabled shipper account number when the user includes the FRSShipmentIndicator in the request.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class FRSShipmentDataTransportationCharges {
  @JsonProperty("GrossCharge")
  private TransportationChargesGrossCharge grossCharge = null;

  @JsonProperty("DiscountAmount")
  private TransportationChargesDiscountAmount discountAmount = null;

  @JsonProperty("DiscountPercentage")
  private String discountPercentage = null;

  @JsonProperty("NetCharge")
  private TransportationChargesNetCharge netCharge = null;

  public FRSShipmentDataTransportationCharges grossCharge(TransportationChargesGrossCharge grossCharge) {
    this.grossCharge = grossCharge;
    return this;
  }

   /**
   * Get grossCharge
   * @return grossCharge
  **/
  public TransportationChargesGrossCharge getGrossCharge() {
    return grossCharge;
  }

  public void setGrossCharge(TransportationChargesGrossCharge grossCharge) {
    this.grossCharge = grossCharge;
  }

  public FRSShipmentDataTransportationCharges discountAmount(TransportationChargesDiscountAmount discountAmount) {
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * Get discountAmount
   * @return discountAmount
  **/
  public TransportationChargesDiscountAmount getDiscountAmount() {
    return discountAmount;
  }

  public void setDiscountAmount(TransportationChargesDiscountAmount discountAmount) {
    this.discountAmount = discountAmount;
  }

  public FRSShipmentDataTransportationCharges discountPercentage(String discountPercentage) {
    this.discountPercentage = discountPercentage;
    return this;
  }

   /**
   * It indicates the shipment level discount percentage for transportation charges.
   * @return discountPercentage
  **/
  public String getDiscountPercentage() {
    return discountPercentage;
  }

  public void setDiscountPercentage(String discountPercentage) {
    this.discountPercentage = discountPercentage;
  }

  public FRSShipmentDataTransportationCharges netCharge(TransportationChargesNetCharge netCharge) {
    this.netCharge = netCharge;
    return this;
  }

   /**
   * Get netCharge
   * @return netCharge
  **/
  public TransportationChargesNetCharge getNetCharge() {
    return netCharge;
  }

  public void setNetCharge(TransportationChargesNetCharge netCharge) {
    this.netCharge = netCharge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FRSShipmentDataTransportationCharges frSShipmentDataTransportationCharges = (FRSShipmentDataTransportationCharges) o;
    return Objects.equals(this.grossCharge, frSShipmentDataTransportationCharges.grossCharge) &&
        Objects.equals(this.discountAmount, frSShipmentDataTransportationCharges.discountAmount) &&
        Objects.equals(this.discountPercentage, frSShipmentDataTransportationCharges.discountPercentage) &&
        Objects.equals(this.netCharge, frSShipmentDataTransportationCharges.netCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grossCharge, discountAmount, discountPercentage, netCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FRSShipmentDataTransportationCharges {\n");
    
    sb.append("    grossCharge: ").append(toIndentedString(grossCharge)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    discountPercentage: ").append(toIndentedString(discountPercentage)).append("\n");
    sb.append("    netCharge: ").append(toIndentedString(netCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
