/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.HandlingUnitsUnitOfMeasurement;

/**
 * Dimension of the HandlingUnit container for density based pricing.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class HandlingUnitsDimensions {
  @JsonProperty("UnitOfMeasurement")
  private HandlingUnitsUnitOfMeasurement unitOfMeasurement = null;

  @JsonProperty("Length")
  private String length = null;

  @JsonProperty("Width")
  private String width = null;

  @JsonProperty("Height")
  private String height = null;

  public HandlingUnitsDimensions unitOfMeasurement(HandlingUnitsUnitOfMeasurement unitOfMeasurement) {
    this.unitOfMeasurement = unitOfMeasurement;
    return this;
  }

   /**
   * Get unitOfMeasurement
   * @return unitOfMeasurement
  **/
  public HandlingUnitsUnitOfMeasurement getUnitOfMeasurement() {
    return unitOfMeasurement;
  }

  public void setUnitOfMeasurement(HandlingUnitsUnitOfMeasurement unitOfMeasurement) {
    this.unitOfMeasurement = unitOfMeasurement;
  }

  public HandlingUnitsDimensions length(String length) {
    this.length = length;
    return this;
  }

   /**
   * The length of the line item used to determine dimensional weight.
   * @return length
  **/
  public String getLength() {
    return length;
  }

  public void setLength(String length) {
    this.length = length;
  }

  public HandlingUnitsDimensions width(String width) {
    this.width = width;
    return this;
  }

   /**
   * The width of the line item used to determine dimensional weight.
   * @return width
  **/
  public String getWidth() {
    return width;
  }

  public void setWidth(String width) {
    this.width = width;
  }

  public HandlingUnitsDimensions height(String height) {
    this.height = height;
    return this;
  }

   /**
   * The height of the line item used to determine dimensional weight.
   * @return height
  **/
  public String getHeight() {
    return height;
  }

  public void setHeight(String height) {
    this.height = height;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HandlingUnitsDimensions handlingUnitsDimensions = (HandlingUnitsDimensions) o;
    return Objects.equals(this.unitOfMeasurement, handlingUnitsDimensions.unitOfMeasurement) &&
        Objects.equals(this.length, handlingUnitsDimensions.length) &&
        Objects.equals(this.width, handlingUnitsDimensions.width) &&
        Objects.equals(this.height, handlingUnitsDimensions.height);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unitOfMeasurement, length, width, height);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandlingUnitsDimensions {\n");
    
    sb.append("    unitOfMeasurement: ").append(toIndentedString(unitOfMeasurement)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
