/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ContactsForwardAgent;
import com.ups.wwwcie.api.client.ContactsIntermediateConsignee;
import com.ups.wwwcie.api.client.ContactsProducer;
import com.ups.wwwcie.api.client.ContactsSoldTo;
import com.ups.wwwcie.api.client.ContactsUltimateConsignee;

/**
 * Holds the contact information of various parties.  Applicable for EEI and NAFTA CO only. Required for NAFTA CO and EEI. Ultimate consignee contact information is required for EEI.  Producer contact information is required for NAFTA CO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class InternationalFormsContacts {
  @JsonProperty("ForwardAgent")
  private ContactsForwardAgent forwardAgent = null;

  @JsonProperty("UltimateConsignee")
  private ContactsUltimateConsignee ultimateConsignee = null;

  @JsonProperty("IntermediateConsignee")
  private ContactsIntermediateConsignee intermediateConsignee = null;

  @JsonProperty("Producer")
  private ContactsProducer producer = null;

  @JsonProperty("SoldTo")
  private ContactsSoldTo soldTo = null;

  public InternationalFormsContacts forwardAgent(ContactsForwardAgent forwardAgent) {
    this.forwardAgent = forwardAgent;
    return this;
  }

   /**
   * Get forwardAgent
   * @return forwardAgent
  **/
  public ContactsForwardAgent getForwardAgent() {
    return forwardAgent;
  }

  public void setForwardAgent(ContactsForwardAgent forwardAgent) {
    this.forwardAgent = forwardAgent;
  }

  public InternationalFormsContacts ultimateConsignee(ContactsUltimateConsignee ultimateConsignee) {
    this.ultimateConsignee = ultimateConsignee;
    return this;
  }

   /**
   * Get ultimateConsignee
   * @return ultimateConsignee
  **/
  public ContactsUltimateConsignee getUltimateConsignee() {
    return ultimateConsignee;
  }

  public void setUltimateConsignee(ContactsUltimateConsignee ultimateConsignee) {
    this.ultimateConsignee = ultimateConsignee;
  }

  public InternationalFormsContacts intermediateConsignee(ContactsIntermediateConsignee intermediateConsignee) {
    this.intermediateConsignee = intermediateConsignee;
    return this;
  }

   /**
   * Get intermediateConsignee
   * @return intermediateConsignee
  **/
  public ContactsIntermediateConsignee getIntermediateConsignee() {
    return intermediateConsignee;
  }

  public void setIntermediateConsignee(ContactsIntermediateConsignee intermediateConsignee) {
    this.intermediateConsignee = intermediateConsignee;
  }

  public InternationalFormsContacts producer(ContactsProducer producer) {
    this.producer = producer;
    return this;
  }

   /**
   * Get producer
   * @return producer
  **/
  public ContactsProducer getProducer() {
    return producer;
  }

  public void setProducer(ContactsProducer producer) {
    this.producer = producer;
  }

  public InternationalFormsContacts soldTo(ContactsSoldTo soldTo) {
    this.soldTo = soldTo;
    return this;
  }

   /**
   * Get soldTo
   * @return soldTo
  **/
  public ContactsSoldTo getSoldTo() {
    return soldTo;
  }

  public void setSoldTo(ContactsSoldTo soldTo) {
    this.soldTo = soldTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternationalFormsContacts internationalFormsContacts = (InternationalFormsContacts) o;
    return Objects.equals(this.forwardAgent, internationalFormsContacts.forwardAgent) &&
        Objects.equals(this.ultimateConsignee, internationalFormsContacts.ultimateConsignee) &&
        Objects.equals(this.intermediateConsignee, internationalFormsContacts.intermediateConsignee) &&
        Objects.equals(this.producer, internationalFormsContacts.producer) &&
        Objects.equals(this.soldTo, internationalFormsContacts.soldTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forwardAgent, ultimateConsignee, intermediateConsignee, producer, soldTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternationalFormsContacts {\n");
    
    sb.append("    forwardAgent: ").append(toIndentedString(forwardAgent)).append("\n");
    sb.append("    ultimateConsignee: ").append(toIndentedString(ultimateConsignee)).append("\n");
    sb.append("    intermediateConsignee: ").append(toIndentedString(intermediateConsignee)).append("\n");
    sb.append("    producer: ").append(toIndentedString(producer)).append("\n");
    sb.append("    soldTo: ").append(toIndentedString(soldTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
