/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Delivery Confirmation container.  Refer to Delivery Confirmation Origin- Destination Pairs in the Appendix for a list of valid values.  Valid only for forward shipment only.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class PackageServiceOptionsDeliveryConfirmation {
  @JsonProperty("DCISType")
  private String dcISType = null;

  @JsonProperty("DCISNumber")
  private String dcISNumber = null;

  public PackageServiceOptionsDeliveryConfirmation dcISType(String dcISType) {
    this.dcISType = dcISType;
    return this;
  }

   /**
   * Type of delivery confirmation.  Valid values: 1 - Unsupported  2 - Delivery Confirmation Signature Required 3 - Delivery Confirmation Adult Signature Required
   * @return dcISType
  **/
  public String getDcISType() {
    return dcISType;
  }

  public void setDcISType(String dcISType) {
    this.dcISType = dcISType;
  }

  public PackageServiceOptionsDeliveryConfirmation dcISNumber(String dcISNumber) {
    this.dcISNumber = dcISNumber;
    return this;
  }

   /**
   * Delivery Confirmation Control number associated with the delivery confirmation for the package.  Valid for forward shipments only.
   * @return dcISNumber
  **/
  public String getDcISNumber() {
    return dcISNumber;
  }

  public void setDcISNumber(String dcISNumber) {
    this.dcISNumber = dcISNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageServiceOptionsDeliveryConfirmation packageServiceOptionsDeliveryConfirmation = (PackageServiceOptionsDeliveryConfirmation) o;
    return Objects.equals(this.dcISType, packageServiceOptionsDeliveryConfirmation.dcISType) &&
        Objects.equals(this.dcISNumber, packageServiceOptionsDeliveryConfirmation.dcISNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dcISType, dcISNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageServiceOptionsDeliveryConfirmation {\n");
    
    sb.append("    dcISType: ").append(toIndentedString(dcISType)).append("\n");
    sb.append("    dcISNumber: ").append(toIndentedString(dcISNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
