/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Required when number of hazmat containers in a package is greater than 1. It indicates whether all the hazmat materials are kept in a single box or multiple boxes.  Required when number of hazmat container in a package is greater than 1.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class PackageHazMatPackageInformation {
  @JsonProperty("AllPackedInOneIndicator")
  private String allPackedInOneIndicator = null;

  @JsonProperty("OverPackedIndicator")
  private String overPackedIndicator = null;

  @JsonProperty("QValue")
  private String qvalue = null;

  @JsonProperty("OuterPackagingType")
  private String outerPackagingType = null;

  public PackageHazMatPackageInformation allPackedInOneIndicator(String allPackedInOneIndicator) {
    this.allPackedInOneIndicator = allPackedInOneIndicator;
    return this;
  }

   /**
   * Presence/Absence Indicator. Any value is ignored. Presence indicates if multiple, different hazmat/chemicals are contained within one box in a package  When number of Hazmat containers in a package is more than one, either AllPackedInOneIndicator or OverPackedIndicator is needed
   * @return allPackedInOneIndicator
  **/
  public String getAllPackedInOneIndicator() {
    return allPackedInOneIndicator;
  }

  public void setAllPackedInOneIndicator(String allPackedInOneIndicator) {
    this.allPackedInOneIndicator = allPackedInOneIndicator;
  }

  public PackageHazMatPackageInformation overPackedIndicator(String overPackedIndicator) {
    this.overPackedIndicator = overPackedIndicator;
    return this;
  }

   /**
   * Presence/Absence Indicator. Any value is ignored. Presence indicates that one or more hazmat/chemicals are in separate boxes in a package.  When number of Hazmat containers in a package is more than one, either AllPackedInOneIndicator or OverPackedIndicator is needed
   * @return overPackedIndicator
  **/
  public String getOverPackedIndicator() {
    return overPackedIndicator;
  }

  public void setOverPackedIndicator(String overPackedIndicator) {
    this.overPackedIndicator = overPackedIndicator;
  }

  public PackageHazMatPackageInformation qvalue(String qvalue) {
    this.qvalue = qvalue;
    return this;
  }

   /**
   * When a HazMat shipment specifies AllPackedInOneIndicator and the regulation set for that shipment is IATA, Ship API must require the shipment to specify a Q-Value with exactly one of the following values: 0.1; 0.2; 0.3; 0.4; 0.5; 0.6; 0.7; 0.8; 0.9; 1.0
   * @return qvalue
  **/
  public String getQvalue() {
    return qvalue;
  }

  public void setQvalue(String qvalue) {
    this.qvalue = qvalue;
  }

  public PackageHazMatPackageInformation outerPackagingType(String outerPackagingType) {
    this.outerPackagingType = outerPackagingType;
    return this;
  }

   /**
   * This field is used for the Outer Hazmat packaging type.  Ex. FIBERBOARD BOX, WOOD(EN) BOX, PLASTIC JERRICAN, METAL BOX, STEEL DRUM, OTHER, PLASTIC BOX, PLASTIC DRUM, STYROFOAM BOX, CYLINDERS, ENVIROTAINER, PLYWOOD BOX, ALUMINUM DRUM, ALUMINUM CYLINDERS, PLASTIC PAIL, PLYWOOD DRUM, FIBER DRUM, STEEL JERRICAN, ALUMINUM JERRICAN, STEEL BOX, CARTON, ALUMINUM BOX
   * @return outerPackagingType
  **/
  public String getOuterPackagingType() {
    return outerPackagingType;
  }

  public void setOuterPackagingType(String outerPackagingType) {
    this.outerPackagingType = outerPackagingType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageHazMatPackageInformation packageHazMatPackageInformation = (PackageHazMatPackageInformation) o;
    return Objects.equals(this.allPackedInOneIndicator, packageHazMatPackageInformation.allPackedInOneIndicator) &&
        Objects.equals(this.overPackedIndicator, packageHazMatPackageInformation.overPackedIndicator) &&
        Objects.equals(this.qvalue, packageHazMatPackageInformation.qvalue) &&
        Objects.equals(this.outerPackagingType, packageHazMatPackageInformation.outerPackagingType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allPackedInOneIndicator, overPackedIndicator, qvalue, outerPackagingType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageHazMatPackageInformation {\n");
    
    sb.append("    allPackedInOneIndicator: ").append(toIndentedString(allPackedInOneIndicator)).append("\n");
    sb.append("    overPackedIndicator: ").append(toIndentedString(overPackedIndicator)).append("\n");
    sb.append("    qvalue: ").append(toIndentedString(qvalue)).append("\n");
    sb.append("    outerPackagingType: ").append(toIndentedString(outerPackagingType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
