/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * This container is used for Populating EMailMessage details for PreAlertNotification.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class PreAlertNotificationEMailMessage {
  @JsonProperty("EMailAddress")
  private String emailAddress = null;

  @JsonProperty("UndeliverableEMailAddress")
  private String undeliverableEMailAddress = null;

  public PreAlertNotificationEMailMessage emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * EMailAddress where PreAlertNotification is sent.
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public PreAlertNotificationEMailMessage undeliverableEMailAddress(String undeliverableEMailAddress) {
    this.undeliverableEMailAddress = undeliverableEMailAddress;
    return this;
  }

   /**
   * This is used for notification when EMailAddress for PreAlertNotification is undeliverable.
   * @return undeliverableEMailAddress
  **/
  public String getUndeliverableEMailAddress() {
    return undeliverableEMailAddress;
  }

  public void setUndeliverableEMailAddress(String undeliverableEMailAddress) {
    this.undeliverableEMailAddress = undeliverableEMailAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreAlertNotificationEMailMessage preAlertNotificationEMailMessage = (PreAlertNotificationEMailMessage) o;
    return Objects.equals(this.emailAddress, preAlertNotificationEMailMessage.emailAddress) &&
        Objects.equals(this.undeliverableEMailAddress, preAlertNotificationEMailMessage.undeliverableEMailAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailAddress, undeliverableEMailAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreAlertNotificationEMailMessage {\n");
    
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    undeliverableEMailAddress: ").append(toIndentedString(undeliverableEMailAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
