/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.EEIInformationDDTCInformation;
import com.ups.wwwcie.api.client.EEIInformationLicense;

/**
 * Required for EEI form.  Applies to EEI form only.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ProductEEIInformation {
  @JsonProperty("ExportInformation")
  private String exportInformation = null;

  @JsonProperty("License")
  private EEIInformationLicense license = null;

  @JsonProperty("DDTCInformation")
  private EEIInformationDDTCInformation ddTCInformation = null;

  public ProductEEIInformation exportInformation(String exportInformation) {
    this.exportInformation = exportInformation;
    return this;
  }

   /**
   * Required for EEI form id it is a SDL product. Valid values: LC, LV, SS,MS, GS, DP, HR, UG, IC, SC, DD, HH, SR, TE,TL, IS, CR, GP, RJ, TP, IP, IR, DB, CH, RS, OS  Applies to EEI form only. Required if EEIFilingOption code 3 specified for EEI form.
   * @return exportInformation
  **/
  public String getExportInformation() {
    return exportInformation;
  }

  public void setExportInformation(String exportInformation) {
    this.exportInformation = exportInformation;
  }

  public ProductEEIInformation license(EEIInformationLicense license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  public EEIInformationLicense getLicense() {
    return license;
  }

  public void setLicense(EEIInformationLicense license) {
    this.license = license;
  }

  public ProductEEIInformation ddTCInformation(EEIInformationDDTCInformation ddTCInformation) {
    this.ddTCInformation = ddTCInformation;
    return this;
  }

   /**
   * Get ddTCInformation
   * @return ddTCInformation
  **/
  public EEIInformationDDTCInformation getDdTCInformation() {
    return ddTCInformation;
  }

  public void setDdTCInformation(EEIInformationDDTCInformation ddTCInformation) {
    this.ddTCInformation = ddTCInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductEEIInformation productEEIInformation = (ProductEEIInformation) o;
    return Objects.equals(this.exportInformation, productEEIInformation.exportInformation) &&
        Objects.equals(this.license, productEEIInformation.license) &&
        Objects.equals(this.ddTCInformation, productEEIInformation.ddTCInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportInformation, license, ddTCInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductEEIInformation {\n");
    
    sb.append("    exportInformation: ").append(toIndentedString(exportInformation)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    ddTCInformation: ").append(toIndentedString(ddTCInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
