/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PackingListInfoPackageAssociated;

import java.util.ArrayList;
import java.util.List;
/**
 * Data Container holding package related information.  Required for packaging list and Air Freight Packing list.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ProductPackingListInfo {
  @JsonProperty("PackageAssociated")
  private List<PackingListInfoPackageAssociated> packageAssociated = new ArrayList<>();

  public ProductPackingListInfo packageAssociated(List<PackingListInfoPackageAssociated> packageAssociated) {
    this.packageAssociated = packageAssociated;
    return this;
  }

  public ProductPackingListInfo addPackageAssociatedItem(PackingListInfoPackageAssociated packageAssociatedItem) {
    this.packageAssociated.add(packageAssociatedItem);
    return this;
  }

   /**
   * Get packageAssociated
   * @return packageAssociated
  **/
  public List<PackingListInfoPackageAssociated> getPackageAssociated() {
    return packageAssociated;
  }

  public void setPackageAssociated(List<PackingListInfoPackageAssociated> packageAssociated) {
    this.packageAssociated = packageAssociated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductPackingListInfo productPackingListInfo = (ProductPackingListInfo) o;
    return Objects.equals(this.packageAssociated, productPackingListInfo.packageAssociated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageAssociated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductPackingListInfo {\n");
    
    sb.append("    packageAssociated: ").append(toIndentedString(packageAssociated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
