/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.InternationalFormsBlanketPeriod;
import com.ups.wwwcie.api.client.InternationalFormsCN22Form;
import com.ups.wwwcie.api.client.InternationalFormsContacts;
import com.ups.wwwcie.api.client.InternationalFormsDiscount;
import com.ups.wwwcie.api.client.InternationalFormsEEIFilingOption;
import com.ups.wwwcie.api.client.InternationalFormsFreightCharges;
import com.ups.wwwcie.api.client.InternationalFormsInsuranceCharges;
import com.ups.wwwcie.api.client.InternationalFormsOtherCharges;
import com.ups.wwwcie.api.client.InternationalFormsProduct;
import com.ups.wwwcie.api.client.InternationalFormsUPSPremiumCareForm;
import com.ups.wwwcie.api.client.InternationalFormsUserCreatedForm;

import java.util.ArrayList;
import java.util.List;
/**
 * International Forms information.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ShipmentServiceOptionsInternationalForms {
  @JsonProperty("FormType")
  private List<String> formType = new ArrayList<>();

  @JsonProperty("UserCreatedForm")
  private InternationalFormsUserCreatedForm userCreatedForm = null;

  @JsonProperty("UPSPremiumCareForm")
  private InternationalFormsUPSPremiumCareForm upSPremiumCareForm = null;

  @JsonProperty("CN22Form")
  private InternationalFormsCN22Form cn22Form = null;

  @JsonProperty("AdditionalDocumentIndicator")
  private String additionalDocumentIndicator = null;

  @JsonProperty("FormGroupIdName")
  private String formGroupIdName = null;

  @JsonProperty("EEIFilingOption")
  private InternationalFormsEEIFilingOption eeIFilingOption = null;

  @JsonProperty("Contacts")
  private InternationalFormsContacts contacts = null;

  @JsonProperty("Product")
  private List<InternationalFormsProduct> product = new ArrayList<>();

  @JsonProperty("InvoiceNumber")
  private String invoiceNumber = null;

  @JsonProperty("InvoiceDate")
  private String invoiceDate = null;

  @JsonProperty("PurchaseOrderNumber")
  private String purchaseOrderNumber = null;

  @JsonProperty("TermsOfShipment")
  private String termsOfShipment = null;

  @JsonProperty("ReasonForExport")
  private String reasonForExport = null;

  @JsonProperty("Comments")
  private String comments = null;

  @JsonProperty("DeclarationStatement")
  private String declarationStatement = null;

  @JsonProperty("Discount")
  private InternationalFormsDiscount discount = null;

  @JsonProperty("FreightCharges")
  private InternationalFormsFreightCharges freightCharges = null;

  @JsonProperty("InsuranceCharges")
  private InternationalFormsInsuranceCharges insuranceCharges = null;

  @JsonProperty("OtherCharges")
  private InternationalFormsOtherCharges otherCharges = null;

  @JsonProperty("CurrencyCode")
  private String currencyCode = null;

  @JsonProperty("BlanketPeriod")
  private InternationalFormsBlanketPeriod blanketPeriod = null;

  @JsonProperty("ExportDate")
  private String exportDate = null;

  @JsonProperty("ExportingCarrier")
  private String exportingCarrier = null;

  @JsonProperty("CarrierID")
  private String carrierID = null;

  @JsonProperty("InBondCode")
  private String inBondCode = null;

  @JsonProperty("EntryNumber")
  private String entryNumber = null;

  @JsonProperty("PointOfOrigin")
  private String pointOfOrigin = null;

  @JsonProperty("PointOfOriginType")
  private String pointOfOriginType = null;

  @JsonProperty("ModeOfTransport")
  private String modeOfTransport = null;

  @JsonProperty("PortOfExport")
  private String portOfExport = null;

  @JsonProperty("PortOfUnloading")
  private String portOfUnloading = null;

  @JsonProperty("LoadingPier")
  private String loadingPier = null;

  @JsonProperty("PartiesToTransaction")
  private String partiesToTransaction = null;

  @JsonProperty("RoutedExportTransactionIndicator")
  private String routedExportTransactionIndicator = null;

  @JsonProperty("ContainerizedIndicator")
  private String containerizedIndicator = null;

  @JsonProperty("OverridePaperlessIndicator")
  private String overridePaperlessIndicator = null;

  @JsonProperty("ShipperMemo")
  private String shipperMemo = null;

  @JsonProperty("HazardousMaterialsIndicator")
  private String hazardousMaterialsIndicator = null;

  public ShipmentServiceOptionsInternationalForms formType(List<String> formType) {
    this.formType = formType;
    return this;
  }

  public ShipmentServiceOptionsInternationalForms addFormTypeItem(String formTypeItem) {
    this.formType.add(formTypeItem);
    return this;
  }

   /**
   * Indicates the name of the International Form requested. Valid values:   01 - Invoice 03 - CO 04 - NAFTA CO 05 - Partial Invoice 06 - Packinglist 07 - Customer Generated Forms 08 - Air Freight Packing List 09 - CN22 Form 10 - UPS Premium Care Form 11 - EEI For shipment with return service, 01, 05 or 10 are the only valid values.  Note: 01 and 05 are mutually exclusive and 05 are only valid for return shipments only.
   * @return formType
  **/
  public List<String> getFormType() {
    return formType;
  }

  public void setFormType(List<String> formType) {
    this.formType = formType;
  }

  public ShipmentServiceOptionsInternationalForms userCreatedForm(InternationalFormsUserCreatedForm userCreatedForm) {
    this.userCreatedForm = userCreatedForm;
    return this;
  }

   /**
   * Get userCreatedForm
   * @return userCreatedForm
  **/
  public InternationalFormsUserCreatedForm getUserCreatedForm() {
    return userCreatedForm;
  }

  public void setUserCreatedForm(InternationalFormsUserCreatedForm userCreatedForm) {
    this.userCreatedForm = userCreatedForm;
  }

  public ShipmentServiceOptionsInternationalForms upSPremiumCareForm(InternationalFormsUPSPremiumCareForm upSPremiumCareForm) {
    this.upSPremiumCareForm = upSPremiumCareForm;
    return this;
  }

   /**
   * Get upSPremiumCareForm
   * @return upSPremiumCareForm
  **/
  public InternationalFormsUPSPremiumCareForm getUpSPremiumCareForm() {
    return upSPremiumCareForm;
  }

  public void setUpSPremiumCareForm(InternationalFormsUPSPremiumCareForm upSPremiumCareForm) {
    this.upSPremiumCareForm = upSPremiumCareForm;
  }

  public ShipmentServiceOptionsInternationalForms cn22Form(InternationalFormsCN22Form cn22Form) {
    this.cn22Form = cn22Form;
    return this;
  }

   /**
   * Get cn22Form
   * @return cn22Form
  **/
  public InternationalFormsCN22Form getCn22Form() {
    return cn22Form;
  }

  public void setCn22Form(InternationalFormsCN22Form cn22Form) {
    this.cn22Form = cn22Form;
  }

  public ShipmentServiceOptionsInternationalForms additionalDocumentIndicator(String additionalDocumentIndicator) {
    this.additionalDocumentIndicator = additionalDocumentIndicator;
    return this;
  }

   /**
   * Presence of the indicator means user will supply additional document, such as EEI, NAFTA_CO or CO.  This indicator should be set when the shipper intends to utilize UPS paperless invoice functionality AND the shipper has SELF-PREPARED other International Forms (EEI, CO, NAFTACO) to accompany the shipment.  It is evaluated only when:  1. Account is paperless enabled.  2. Movement requires an invoice. 3. Destination country or territory accepts paperless invoice.  4. Invoice data is supplied by the client and the data passes validation.
   * @return additionalDocumentIndicator
  **/
  public String getAdditionalDocumentIndicator() {
    return additionalDocumentIndicator;
  }

  public void setAdditionalDocumentIndicator(String additionalDocumentIndicator) {
    this.additionalDocumentIndicator = additionalDocumentIndicator;
  }

  public ShipmentServiceOptionsInternationalForms formGroupIdName(String formGroupIdName) {
    this.formGroupIdName = formGroupIdName;
    return this;
  }

   /**
   * Contains description text which identifies the group of International forms. This element does not appear on the forms.
   * @return formGroupIdName
  **/
  public String getFormGroupIdName() {
    return formGroupIdName;
  }

  public void setFormGroupIdName(String formGroupIdName) {
    this.formGroupIdName = formGroupIdName;
  }

  public ShipmentServiceOptionsInternationalForms eeIFilingOption(InternationalFormsEEIFilingOption eeIFilingOption) {
    this.eeIFilingOption = eeIFilingOption;
    return this;
  }

   /**
   * Get eeIFilingOption
   * @return eeIFilingOption
  **/
  public InternationalFormsEEIFilingOption getEeIFilingOption() {
    return eeIFilingOption;
  }

  public void setEeIFilingOption(InternationalFormsEEIFilingOption eeIFilingOption) {
    this.eeIFilingOption = eeIFilingOption;
  }

  public ShipmentServiceOptionsInternationalForms contacts(InternationalFormsContacts contacts) {
    this.contacts = contacts;
    return this;
  }

   /**
   * Get contacts
   * @return contacts
  **/
  public InternationalFormsContacts getContacts() {
    return contacts;
  }

  public void setContacts(InternationalFormsContacts contacts) {
    this.contacts = contacts;
  }

  public ShipmentServiceOptionsInternationalForms product(List<InternationalFormsProduct> product) {
    this.product = product;
    return this;
  }

  public ShipmentServiceOptionsInternationalForms addProductItem(InternationalFormsProduct productItem) {
    this.product.add(productItem);
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  public List<InternationalFormsProduct> getProduct() {
    return product;
  }

  public void setProduct(List<InternationalFormsProduct> product) {
    this.product = product;
  }

  public ShipmentServiceOptionsInternationalForms invoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * Commercial Invoice number assigned by the exporter.  Applies to Invoice and Partial Invoice forms only. Required for Invoice forms and optional for Partial Invoice.
   * @return invoiceNumber
  **/
  public String getInvoiceNumber() {
    return invoiceNumber;
  }

  public void setInvoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }

  public ShipmentServiceOptionsInternationalForms invoiceDate(String invoiceDate) {
    this.invoiceDate = invoiceDate;
    return this;
  }

   /**
   * Date when the Invoice is created. Ideally this is the same as the ship date.  Applies to Invoice and Partial Invoice forms only. Required for Invoice forms and optional for Partial Invoice. Required for Invoice form for forward shipments. For shipment with return service, the user input will be ignored, and the field will be blank on the invoice. Format is yyyyMMdd.
   * @return invoiceDate
  **/
  public String getInvoiceDate() {
    return invoiceDate;
  }

  public void setInvoiceDate(String invoiceDate) {
    this.invoiceDate = invoiceDate;
  }

  public ShipmentServiceOptionsInternationalForms purchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
    return this;
  }

   /**
   * The customer&#x27;s order reference number.  Applies to Invoice and Partial Invoice forms only.
   * @return purchaseOrderNumber
  **/
  public String getPurchaseOrderNumber() {
    return purchaseOrderNumber;
  }

  public void setPurchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
  }

  public ShipmentServiceOptionsInternationalForms termsOfShipment(String termsOfShipment) {
    this.termsOfShipment = termsOfShipment;
    return this;
  }

   /**
   * Indicates the rights to the seller from the buyer. Also, it refers to Terms of Sale.  Applies to Invoice and Partial Invoice forms only.   Valid values:  CFR: Cost and Freight  CIF: Cost Insurance and Freight  CIP: Carriage and Insurance Paid  CPT: Carriage Paid To  DAF: Delivered at Frontier  DDP: Delivery Duty Paid  DDU: Delivery Duty Unpaid  DEQ: Delivered Ex Quay  DES: Delivered Ex Ship  EXW: Ex Works  FAS: Free Alongside Ship  FCA: Free Carrier  FOB: Free On Board
   * @return termsOfShipment
  **/
  public String getTermsOfShipment() {
    return termsOfShipment;
  }

  public void setTermsOfShipment(String termsOfShipment) {
    this.termsOfShipment = termsOfShipment;
  }

  public ShipmentServiceOptionsInternationalForms reasonForExport(String reasonForExport) {
    this.reasonForExport = reasonForExport;
    return this;
  }

   /**
   * A reason to export the current international shipment. Valid values: SALE, GIFT, SAMPLE, RETURN, REPAIR, INTERCOMPANYDATA, Any other reason.  Applies to Invoice and Partial Invoice forms only. Required for Invoice forms and Optional for Partial Invoice. No validation.
   * @return reasonForExport
  **/
  public String getReasonForExport() {
    return reasonForExport;
  }

  public void setReasonForExport(String reasonForExport) {
    this.reasonForExport = reasonForExport;
  }

  public ShipmentServiceOptionsInternationalForms comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Any extra information about the current shipment.  Applies to Invoice and Partial Invoice forms only.
   * @return comments
  **/
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public ShipmentServiceOptionsInternationalForms declarationStatement(String declarationStatement) {
    this.declarationStatement = declarationStatement;
    return this;
  }

   /**
   * This is the legal explanation, used by Customs, for the delivering of this shipment. It must be identical to the set of declarations actually used by Customs. Examples of declarations that might be entered in this field are: I hereby certify that the goods covered by this shipment qualify as originating goods for purposes of preferential tariff treatment under the NAFTA. I hereby certify that the information on this invoice is true and correct and the contents and value of this shipment is as stated above.  EEA statement:  The exporter of the products covered by this document declares that except where otherwise clearly indicated these products are of EEA preferential origin.  Applies to Invoice and Partial Invoice forms only. On the invoice for return shipment, the verbiage is as follows (user input is ignored): The exporter of the products covered by this document declares that except where otherwise clearly indicated these products are of EEA preferential origin
   * @return declarationStatement
  **/
  public String getDeclarationStatement() {
    return declarationStatement;
  }

  public void setDeclarationStatement(String declarationStatement) {
    this.declarationStatement = declarationStatement;
  }

  public ShipmentServiceOptionsInternationalForms discount(InternationalFormsDiscount discount) {
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  public InternationalFormsDiscount getDiscount() {
    return discount;
  }

  public void setDiscount(InternationalFormsDiscount discount) {
    this.discount = discount;
  }

  public ShipmentServiceOptionsInternationalForms freightCharges(InternationalFormsFreightCharges freightCharges) {
    this.freightCharges = freightCharges;
    return this;
  }

   /**
   * Get freightCharges
   * @return freightCharges
  **/
  public InternationalFormsFreightCharges getFreightCharges() {
    return freightCharges;
  }

  public void setFreightCharges(InternationalFormsFreightCharges freightCharges) {
    this.freightCharges = freightCharges;
  }

  public ShipmentServiceOptionsInternationalForms insuranceCharges(InternationalFormsInsuranceCharges insuranceCharges) {
    this.insuranceCharges = insuranceCharges;
    return this;
  }

   /**
   * Get insuranceCharges
   * @return insuranceCharges
  **/
  public InternationalFormsInsuranceCharges getInsuranceCharges() {
    return insuranceCharges;
  }

  public void setInsuranceCharges(InternationalFormsInsuranceCharges insuranceCharges) {
    this.insuranceCharges = insuranceCharges;
  }

  public ShipmentServiceOptionsInternationalForms otherCharges(InternationalFormsOtherCharges otherCharges) {
    this.otherCharges = otherCharges;
    return this;
  }

   /**
   * Get otherCharges
   * @return otherCharges
  **/
  public InternationalFormsOtherCharges getOtherCharges() {
    return otherCharges;
  }

  public void setOtherCharges(InternationalFormsOtherCharges otherCharges) {
    this.otherCharges = otherCharges;
  }

  public ShipmentServiceOptionsInternationalForms currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Currency code for all the monetary values of the Invoice form.  Applies to Invoice and Partial Invoice forms only.
   * @return currencyCode
  **/
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public ShipmentServiceOptionsInternationalForms blanketPeriod(InternationalFormsBlanketPeriod blanketPeriod) {
    this.blanketPeriod = blanketPeriod;
    return this;
  }

   /**
   * Get blanketPeriod
   * @return blanketPeriod
  **/
  public InternationalFormsBlanketPeriod getBlanketPeriod() {
    return blanketPeriod;
  }

  public void setBlanketPeriod(InternationalFormsBlanketPeriod blanketPeriod) {
    this.blanketPeriod = blanketPeriod;
  }

  public ShipmentServiceOptionsInternationalForms exportDate(String exportDate) {
    this.exportDate = exportDate;
    return this;
  }

   /**
   * The date the goods will be exiting the country or territory.  Applies to CO and EEI forms only. Required for CO and EEI forms. Format is yyyyMMdd.
   * @return exportDate
  **/
  public String getExportDate() {
    return exportDate;
  }

  public void setExportDate(String exportDate) {
    this.exportDate = exportDate;
  }

  public ShipmentServiceOptionsInternationalForms exportingCarrier(String exportingCarrier) {
    this.exportingCarrier = exportingCarrier;
    return this;
  }

   /**
   * The name of the carrier that is exporting the shipment. The vessels flag number should also be entered, if the carrier is a vessel.  Applies to CO and EEI forms only. Required for CO and EEI forms.
   * @return exportingCarrier
  **/
  public String getExportingCarrier() {
    return exportingCarrier;
  }

  public void setExportingCarrier(String exportingCarrier) {
    this.exportingCarrier = exportingCarrier;
  }

  public ShipmentServiceOptionsInternationalForms carrierID(String carrierID) {
    this.carrierID = carrierID;
    return this;
  }

   /**
   * The four-character Standard Carrier Alpha Code (SCAC) for vessel, rail, and truck shipments. For air shipment, enter the two or three character International Air Transport Association (IATA) code.  Applies to EEI forms only. No Validations.
   * @return carrierID
  **/
  public String getCarrierID() {
    return carrierID;
  }

  public void setCarrierID(String carrierID) {
    this.carrierID = carrierID;
  }

  public ShipmentServiceOptionsInternationalForms inBondCode(String inBondCode) {
    this.inBondCode = inBondCode;
    return this;
  }

   /**
   * The two-character In Bond Code.  Applies to EEI forms only. Required for EEI forms. Valid values for EEI are: 70: Not in bond; 67: IE from a FTZ; 68: T&amp;E from a FTZ.
   * @return inBondCode
  **/
  public String getInBondCode() {
    return inBondCode;
  }

  public void setInBondCode(String inBondCode) {
    this.inBondCode = inBondCode;
  }

  public ShipmentServiceOptionsInternationalForms entryNumber(String entryNumber) {
    this.entryNumber = entryNumber;
    return this;
  }

   /**
   * The Import Entry Number when the export transaction is used as proof of export for import transactions (examples: In Bond, Temporary Import Bond or Drawbacks).  Applies to EEI forms only. Conditionally Required for EEI forms when In bond code value is other than 70 (Not In Bond)
   * @return entryNumber
  **/
  public String getEntryNumber() {
    return entryNumber;
  }

  public void setEntryNumber(String entryNumber) {
    this.entryNumber = entryNumber;
  }

  public ShipmentServiceOptionsInternationalForms pointOfOrigin(String pointOfOrigin) {
    this.pointOfOrigin = pointOfOrigin;
    return this;
  }

   /**
   * Contains one of the following:  The two-digit U.S. Postal Service abbreviation for the state from which the goods were shipped to the port of export. The state that is the source for the good with the highest value. The state of consolidation. The Foreign Trade Zone number of the zone from where the exports are leaving.  If the goods were shipped from Puerto Rico, enter PR.  Applies to EEI forms only. Required for EEI.
   * @return pointOfOrigin
  **/
  public String getPointOfOrigin() {
    return pointOfOrigin;
  }

  public void setPointOfOrigin(String pointOfOrigin) {
    this.pointOfOrigin = pointOfOrigin;
  }

  public ShipmentServiceOptionsInternationalForms pointOfOriginType(String pointOfOriginType) {
    this.pointOfOriginType = pointOfOriginType;
    return this;
  }

   /**
   * Valid values are : S (for state postal code abbreviation) , F : FTZ Identifier  Applies EEI forms only. Required for EEI form.
   * @return pointOfOriginType
  **/
  public String getPointOfOriginType() {
    return pointOfOriginType;
  }

  public void setPointOfOriginType(String pointOfOriginType) {
    this.pointOfOriginType = pointOfOriginType;
  }

  public ShipmentServiceOptionsInternationalForms modeOfTransport(String modeOfTransport) {
    this.modeOfTransport = modeOfTransport;
    return this;
  }

   /**
   * Mode of transport by which the goods are exported. Valid values: Air, AirContainerized, Auto, FixedTransportInstallations, Mail, PassengerHandcarried, Pedestrian, Rail, Rail, Containerized, RoadOther, SeaBarge, SeaContainerized, SeaNoncontainerized, Truck, TruckContainerized.  Applies to EEI forms only.  Required for EEI.  Only allowed values can be entered. Only 10 Characters can appear on the form. Anything greater than 10 characters will be truncated on the form.
   * @return modeOfTransport
  **/
  public String getModeOfTransport() {
    return modeOfTransport;
  }

  public void setModeOfTransport(String modeOfTransport) {
    this.modeOfTransport = modeOfTransport;
  }

  public ShipmentServiceOptionsInternationalForms portOfExport(String portOfExport) {
    this.portOfExport = portOfExport;
    return this;
  }

   /**
   * Should be one of the following-Overland: The U.S. Customs port where the carrier crosses the U.S. border, Vessel and Air: The U.S. Customs port where the goods are loaded on the carrier to be exported from the U.S., Postal: The U.S. Postal Office from where the goods are mailed.  Applies to EEI forms only. No validation is performed.
   * @return portOfExport
  **/
  public String getPortOfExport() {
    return portOfExport;
  }

  public void setPortOfExport(String portOfExport) {
    this.portOfExport = portOfExport;
  }

  public ShipmentServiceOptionsInternationalForms portOfUnloading(String portOfUnloading) {
    this.portOfUnloading = portOfUnloading;
    return this;
  }

   /**
   * The country or territory and the port where the goods will be unloaded from the exporting carrier. For vessel and air shipments only.  Applies to EEI forms only. No validation is performed.
   * @return portOfUnloading
  **/
  public String getPortOfUnloading() {
    return portOfUnloading;
  }

  public void setPortOfUnloading(String portOfUnloading) {
    this.portOfUnloading = portOfUnloading;
  }

  public ShipmentServiceOptionsInternationalForms loadingPier(String loadingPier) {
    this.loadingPier = loadingPier;
    return this;
  }

   /**
   * Pier where goods are loaded. For vessel shipments only.  Applies to EEI forms only. No validation is performed.
   * @return loadingPier
  **/
  public String getLoadingPier() {
    return loadingPier;
  }

  public void setLoadingPier(String loadingPier) {
    this.loadingPier = loadingPier;
  }

  public ShipmentServiceOptionsInternationalForms partiesToTransaction(String partiesToTransaction) {
    this.partiesToTransaction = partiesToTransaction;
    return this;
  }

   /**
   * Information about parties to transaction. Use Related, if the parties to the transaction are related. A related party is an export from a U.S. businessperson or business to a foreign business or from a U.S. business to a foreign person or business where the person has at least 10 percent of the voting shares of the business during the fiscal year. If unincorporated, then an equivalent interest in the business.  Applies to EEI forms only.   Valid values: R - Related, N - Non-related.
   * @return partiesToTransaction
  **/
  public String getPartiesToTransaction() {
    return partiesToTransaction;
  }

  public void setPartiesToTransaction(String partiesToTransaction) {
    this.partiesToTransaction = partiesToTransaction;
  }

  public ShipmentServiceOptionsInternationalForms routedExportTransactionIndicator(String routedExportTransactionIndicator) {
    this.routedExportTransactionIndicator = routedExportTransactionIndicator;
    return this;
  }

   /**
   * If Present, indicates that it is a routed export transaction. A routed export transaction is one, where the foreign principal party in interest authorizes a U.S. forwarding (or other) agent to export the merchandise outside the U.S.  Applies to EEI forms only.
   * @return routedExportTransactionIndicator
  **/
  public String getRoutedExportTransactionIndicator() {
    return routedExportTransactionIndicator;
  }

  public void setRoutedExportTransactionIndicator(String routedExportTransactionIndicator) {
    this.routedExportTransactionIndicator = routedExportTransactionIndicator;
  }

  public ShipmentServiceOptionsInternationalForms containerizedIndicator(String containerizedIndicator) {
    this.containerizedIndicator = containerizedIndicator;
    return this;
  }

   /**
   * If present indicates that the goods are containerized. This applies to vessel shipments only.  Applies to EEI forms only.
   * @return containerizedIndicator
  **/
  public String getContainerizedIndicator() {
    return containerizedIndicator;
  }

  public void setContainerizedIndicator(String containerizedIndicator) {
    this.containerizedIndicator = containerizedIndicator;
  }

  public ShipmentServiceOptionsInternationalForms overridePaperlessIndicator(String overridePaperlessIndicator) {
    this.overridePaperlessIndicator = overridePaperlessIndicator;
    return this;
  }

   /**
   * The application will automatically provide a copy of the invoice or NAFTA/CO with each response regardless of whether the user has enabled Paperless account. The user now has the option to print or ignore the copy provided.
   * @return overridePaperlessIndicator
  **/
  public String getOverridePaperlessIndicator() {
    return overridePaperlessIndicator;
  }

  public void setOverridePaperlessIndicator(String overridePaperlessIndicator) {
    this.overridePaperlessIndicator = overridePaperlessIndicator;
  }

  public ShipmentServiceOptionsInternationalForms shipperMemo(String shipperMemo) {
    this.shipperMemo = shipperMemo;
    return this;
  }

   /**
   * Text for the shipper to add additional information.  Forward shipment only.
   * @return shipperMemo
  **/
  public String getShipperMemo() {
    return shipperMemo;
  }

  public void setShipperMemo(String shipperMemo) {
    this.shipperMemo = shipperMemo;
  }

  public ShipmentServiceOptionsInternationalForms hazardousMaterialsIndicator(String hazardousMaterialsIndicator) {
    this.hazardousMaterialsIndicator = hazardousMaterialsIndicator;
    return this;
  }

   /**
   * This is an empty tag. Presence of the indicator for EEI form means shipment contains hazardous material.
   * @return hazardousMaterialsIndicator
  **/
  public String getHazardousMaterialsIndicator() {
    return hazardousMaterialsIndicator;
  }

  public void setHazardousMaterialsIndicator(String hazardousMaterialsIndicator) {
    this.hazardousMaterialsIndicator = hazardousMaterialsIndicator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentServiceOptionsInternationalForms shipmentServiceOptionsInternationalForms = (ShipmentServiceOptionsInternationalForms) o;
    return Objects.equals(this.formType, shipmentServiceOptionsInternationalForms.formType) &&
        Objects.equals(this.userCreatedForm, shipmentServiceOptionsInternationalForms.userCreatedForm) &&
        Objects.equals(this.upSPremiumCareForm, shipmentServiceOptionsInternationalForms.upSPremiumCareForm) &&
        Objects.equals(this.cn22Form, shipmentServiceOptionsInternationalForms.cn22Form) &&
        Objects.equals(this.additionalDocumentIndicator, shipmentServiceOptionsInternationalForms.additionalDocumentIndicator) &&
        Objects.equals(this.formGroupIdName, shipmentServiceOptionsInternationalForms.formGroupIdName) &&
        Objects.equals(this.eeIFilingOption, shipmentServiceOptionsInternationalForms.eeIFilingOption) &&
        Objects.equals(this.contacts, shipmentServiceOptionsInternationalForms.contacts) &&
        Objects.equals(this.product, shipmentServiceOptionsInternationalForms.product) &&
        Objects.equals(this.invoiceNumber, shipmentServiceOptionsInternationalForms.invoiceNumber) &&
        Objects.equals(this.invoiceDate, shipmentServiceOptionsInternationalForms.invoiceDate) &&
        Objects.equals(this.purchaseOrderNumber, shipmentServiceOptionsInternationalForms.purchaseOrderNumber) &&
        Objects.equals(this.termsOfShipment, shipmentServiceOptionsInternationalForms.termsOfShipment) &&
        Objects.equals(this.reasonForExport, shipmentServiceOptionsInternationalForms.reasonForExport) &&
        Objects.equals(this.comments, shipmentServiceOptionsInternationalForms.comments) &&
        Objects.equals(this.declarationStatement, shipmentServiceOptionsInternationalForms.declarationStatement) &&
        Objects.equals(this.discount, shipmentServiceOptionsInternationalForms.discount) &&
        Objects.equals(this.freightCharges, shipmentServiceOptionsInternationalForms.freightCharges) &&
        Objects.equals(this.insuranceCharges, shipmentServiceOptionsInternationalForms.insuranceCharges) &&
        Objects.equals(this.otherCharges, shipmentServiceOptionsInternationalForms.otherCharges) &&
        Objects.equals(this.currencyCode, shipmentServiceOptionsInternationalForms.currencyCode) &&
        Objects.equals(this.blanketPeriod, shipmentServiceOptionsInternationalForms.blanketPeriod) &&
        Objects.equals(this.exportDate, shipmentServiceOptionsInternationalForms.exportDate) &&
        Objects.equals(this.exportingCarrier, shipmentServiceOptionsInternationalForms.exportingCarrier) &&
        Objects.equals(this.carrierID, shipmentServiceOptionsInternationalForms.carrierID) &&
        Objects.equals(this.inBondCode, shipmentServiceOptionsInternationalForms.inBondCode) &&
        Objects.equals(this.entryNumber, shipmentServiceOptionsInternationalForms.entryNumber) &&
        Objects.equals(this.pointOfOrigin, shipmentServiceOptionsInternationalForms.pointOfOrigin) &&
        Objects.equals(this.pointOfOriginType, shipmentServiceOptionsInternationalForms.pointOfOriginType) &&
        Objects.equals(this.modeOfTransport, shipmentServiceOptionsInternationalForms.modeOfTransport) &&
        Objects.equals(this.portOfExport, shipmentServiceOptionsInternationalForms.portOfExport) &&
        Objects.equals(this.portOfUnloading, shipmentServiceOptionsInternationalForms.portOfUnloading) &&
        Objects.equals(this.loadingPier, shipmentServiceOptionsInternationalForms.loadingPier) &&
        Objects.equals(this.partiesToTransaction, shipmentServiceOptionsInternationalForms.partiesToTransaction) &&
        Objects.equals(this.routedExportTransactionIndicator, shipmentServiceOptionsInternationalForms.routedExportTransactionIndicator) &&
        Objects.equals(this.containerizedIndicator, shipmentServiceOptionsInternationalForms.containerizedIndicator) &&
        Objects.equals(this.overridePaperlessIndicator, shipmentServiceOptionsInternationalForms.overridePaperlessIndicator) &&
        Objects.equals(this.shipperMemo, shipmentServiceOptionsInternationalForms.shipperMemo) &&
        Objects.equals(this.hazardousMaterialsIndicator, shipmentServiceOptionsInternationalForms.hazardousMaterialsIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formType, userCreatedForm, upSPremiumCareForm, cn22Form, additionalDocumentIndicator, formGroupIdName, eeIFilingOption, contacts, product, invoiceNumber, invoiceDate, purchaseOrderNumber, termsOfShipment, reasonForExport, comments, declarationStatement, discount, freightCharges, insuranceCharges, otherCharges, currencyCode, blanketPeriod, exportDate, exportingCarrier, carrierID, inBondCode, entryNumber, pointOfOrigin, pointOfOriginType, modeOfTransport, portOfExport, portOfUnloading, loadingPier, partiesToTransaction, routedExportTransactionIndicator, containerizedIndicator, overridePaperlessIndicator, shipperMemo, hazardousMaterialsIndicator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentServiceOptionsInternationalForms {\n");
    
    sb.append("    formType: ").append(toIndentedString(formType)).append("\n");
    sb.append("    userCreatedForm: ").append(toIndentedString(userCreatedForm)).append("\n");
    sb.append("    upSPremiumCareForm: ").append(toIndentedString(upSPremiumCareForm)).append("\n");
    sb.append("    cn22Form: ").append(toIndentedString(cn22Form)).append("\n");
    sb.append("    additionalDocumentIndicator: ").append(toIndentedString(additionalDocumentIndicator)).append("\n");
    sb.append("    formGroupIdName: ").append(toIndentedString(formGroupIdName)).append("\n");
    sb.append("    eeIFilingOption: ").append(toIndentedString(eeIFilingOption)).append("\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    invoiceDate: ").append(toIndentedString(invoiceDate)).append("\n");
    sb.append("    purchaseOrderNumber: ").append(toIndentedString(purchaseOrderNumber)).append("\n");
    sb.append("    termsOfShipment: ").append(toIndentedString(termsOfShipment)).append("\n");
    sb.append("    reasonForExport: ").append(toIndentedString(reasonForExport)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    declarationStatement: ").append(toIndentedString(declarationStatement)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    freightCharges: ").append(toIndentedString(freightCharges)).append("\n");
    sb.append("    insuranceCharges: ").append(toIndentedString(insuranceCharges)).append("\n");
    sb.append("    otherCharges: ").append(toIndentedString(otherCharges)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    blanketPeriod: ").append(toIndentedString(blanketPeriod)).append("\n");
    sb.append("    exportDate: ").append(toIndentedString(exportDate)).append("\n");
    sb.append("    exportingCarrier: ").append(toIndentedString(exportingCarrier)).append("\n");
    sb.append("    carrierID: ").append(toIndentedString(carrierID)).append("\n");
    sb.append("    inBondCode: ").append(toIndentedString(inBondCode)).append("\n");
    sb.append("    entryNumber: ").append(toIndentedString(entryNumber)).append("\n");
    sb.append("    pointOfOrigin: ").append(toIndentedString(pointOfOrigin)).append("\n");
    sb.append("    pointOfOriginType: ").append(toIndentedString(pointOfOriginType)).append("\n");
    sb.append("    modeOfTransport: ").append(toIndentedString(modeOfTransport)).append("\n");
    sb.append("    portOfExport: ").append(toIndentedString(portOfExport)).append("\n");
    sb.append("    portOfUnloading: ").append(toIndentedString(portOfUnloading)).append("\n");
    sb.append("    loadingPier: ").append(toIndentedString(loadingPier)).append("\n");
    sb.append("    partiesToTransaction: ").append(toIndentedString(partiesToTransaction)).append("\n");
    sb.append("    routedExportTransactionIndicator: ").append(toIndentedString(routedExportTransactionIndicator)).append("\n");
    sb.append("    containerizedIndicator: ").append(toIndentedString(containerizedIndicator)).append("\n");
    sb.append("    overridePaperlessIndicator: ").append(toIndentedString(overridePaperlessIndicator)).append("\n");
    sb.append("    shipperMemo: ").append(toIndentedString(shipperMemo)).append("\n");
    sb.append("    hazardousMaterialsIndicator: ").append(toIndentedString(hazardousMaterialsIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
