/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PaymentInformationShipmentCharge;

import java.util.ArrayList;
import java.util.List;
/**
 * Payment information container for detailed shipment charges. The two shipment charges that are available for specification are Transportation charges and Duties and Taxes.  It is required for non-Ground Freight Pricing shipments only.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ShipmentPaymentInformation {
  @JsonProperty("ShipmentCharge")
  private List<PaymentInformationShipmentCharge> shipmentCharge = new ArrayList<>();

  @JsonProperty("SplitDutyVATIndicator")
  private String splitDutyVATIndicator = null;

  public ShipmentPaymentInformation shipmentCharge(List<PaymentInformationShipmentCharge> shipmentCharge) {
    this.shipmentCharge = shipmentCharge;
    return this;
  }

  public ShipmentPaymentInformation addShipmentChargeItem(PaymentInformationShipmentCharge shipmentChargeItem) {
    this.shipmentCharge.add(shipmentChargeItem);
    return this;
  }

   /**
   * Get shipmentCharge
   * @return shipmentCharge
  **/
  public List<PaymentInformationShipmentCharge> getShipmentCharge() {
    return shipmentCharge;
  }

  public void setShipmentCharge(List<PaymentInformationShipmentCharge> shipmentCharge) {
    this.shipmentCharge = shipmentCharge;
  }

  public ShipmentPaymentInformation splitDutyVATIndicator(String splitDutyVATIndicator) {
    this.splitDutyVATIndicator = splitDutyVATIndicator;
    return this;
  }

   /**
   * Split Duty VAT Indicator. The presence indicates the payer specified for Transportation Charges will pay transportation charges and any duties that apply to the shipment. The payer specified for Duties and Taxes will pay the VAT (Value-Added Tax) only.  This is an empty tag, any value inside is ignored. The payment method for Transportation charges must be UPS account. The UPS account must be a daily pickup account or an occasional account.
   * @return splitDutyVATIndicator
  **/
  public String getSplitDutyVATIndicator() {
    return splitDutyVATIndicator;
  }

  public void setSplitDutyVATIndicator(String splitDutyVATIndicator) {
    this.splitDutyVATIndicator = splitDutyVATIndicator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentPaymentInformation shipmentPaymentInformation = (ShipmentPaymentInformation) o;
    return Objects.equals(this.shipmentCharge, shipmentPaymentInformation.shipmentCharge) &&
        Objects.equals(this.splitDutyVATIndicator, shipmentPaymentInformation.splitDutyVATIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentCharge, splitDutyVATIndicator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentPaymentInformation {\n");
    
    sb.append("    shipmentCharge: ").append(toIndentedString(shipmentCharge)).append("\n");
    sb.append("    splitDutyVATIndicator: ").append(toIndentedString(splitDutyVATIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
