/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ShipmentResponseResponse;
import com.ups.wwwcie.api.client.ShipmentResponseShipmentResults;

/**
 * Shipment Response.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ShipmentResponse {
  @JsonProperty("Response")
  private ShipmentResponseResponse response = null;

  @JsonProperty("ShipmentResults")
  private ShipmentResponseShipmentResults shipmentResults = null;

  public ShipmentResponse response(ShipmentResponseResponse response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  public ShipmentResponseResponse getResponse() {
    return response;
  }

  public void setResponse(ShipmentResponseResponse response) {
    this.response = response;
  }

  public ShipmentResponse shipmentResults(ShipmentResponseShipmentResults shipmentResults) {
    this.shipmentResults = shipmentResults;
    return this;
  }

   /**
   * Get shipmentResults
   * @return shipmentResults
  **/
  public ShipmentResponseShipmentResults getShipmentResults() {
    return shipmentResults;
  }

  public void setShipmentResults(ShipmentResponseShipmentResults shipmentResults) {
    this.shipmentResults = shipmentResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentResponse shipmentResponse = (ShipmentResponse) o;
    return Objects.equals(this.response, shipmentResponse.response) &&
        Objects.equals(this.shipmentResults, shipmentResponse.shipmentResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, shipmentResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentResponse {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    shipmentResults: ").append(toIndentedString(shipmentResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
