/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ShipToAddress;
import com.ups.wwwcie.api.client.ShipToPhone;

/**
 * Ship To Container.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ShipmentShipTo {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("AttentionName")
  private String attentionName = null;

  @JsonProperty("CompanyDisplayableName")
  private String companyDisplayableName = null;

  @JsonProperty("TaxIdentificationNumber")
  private String taxIdentificationNumber = null;

  @JsonProperty("Phone")
  private ShipToPhone phone = null;

  @JsonProperty("FaxNumber")
  private String faxNumber = null;

  @JsonProperty("EMailAddress")
  private String emailAddress = null;

  @JsonProperty("Address")
  private ShipToAddress address = null;

  @JsonProperty("LocationID")
  private String locationID = null;

  public ShipmentShipTo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Consignee&#x27;s company name.  All other accounts must be either a daily pickup account or an occasional account.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ShipmentShipTo attentionName(String attentionName) {
    this.attentionName = attentionName;
    return this;
  }

   /**
   * Contact name at the consignee&#x27;s location.  Required for: UPS Next Day Air Early service, and when ShipTo country or territory is different than ShipFrom country or territory.   Required if Invoice International form is requested.
   * @return attentionName
  **/
  public String getAttentionName() {
    return attentionName;
  }

  public void setAttentionName(String attentionName) {
    this.attentionName = attentionName;
  }

  public ShipmentShipTo companyDisplayableName(String companyDisplayableName) {
    this.companyDisplayableName = companyDisplayableName;
    return this;
  }

   /**
   * Not applicable for ShipTo
   * @return companyDisplayableName
  **/
  public String getCompanyDisplayableName() {
    return companyDisplayableName;
  }

  public void setCompanyDisplayableName(String companyDisplayableName) {
    this.companyDisplayableName = companyDisplayableName;
  }

  public ShipmentShipTo taxIdentificationNumber(String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
    return this;
  }

   /**
   * Consignee&#x27;s tax identification number.
   * @return taxIdentificationNumber
  **/
  public String getTaxIdentificationNumber() {
    return taxIdentificationNumber;
  }

  public void setTaxIdentificationNumber(String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
  }

  public ShipmentShipTo phone(ShipToPhone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public ShipToPhone getPhone() {
    return phone;
  }

  public void setPhone(ShipToPhone phone) {
    this.phone = phone;
  }

  public ShipmentShipTo faxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

   /**
   * Consignee&#x27;s fax number.  If ShipTo country or territory is US 10 digits allowed, otherwise 1-15 digits allowed.
   * @return faxNumber
  **/
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
  }

  public ShipmentShipTo emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Consignee&#x27;s email address.
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public ShipmentShipTo address(ShipToAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public ShipToAddress getAddress() {
    return address;
  }

  public void setAddress(ShipToAddress address) {
    this.address = address;
  }

  public ShipmentShipTo locationID(String locationID) {
    this.locationID = locationID;
    return this;
  }

   /**
   * Location ID is a unique identifier referring to a specific shipping/receiving location.  Location ID must be alphanumeric characters. All letters must be capitalized.
   * @return locationID
  **/
  public String getLocationID() {
    return locationID;
  }

  public void setLocationID(String locationID) {
    this.locationID = locationID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentShipTo shipmentShipTo = (ShipmentShipTo) o;
    return Objects.equals(this.name, shipmentShipTo.name) &&
        Objects.equals(this.attentionName, shipmentShipTo.attentionName) &&
        Objects.equals(this.companyDisplayableName, shipmentShipTo.companyDisplayableName) &&
        Objects.equals(this.taxIdentificationNumber, shipmentShipTo.taxIdentificationNumber) &&
        Objects.equals(this.phone, shipmentShipTo.phone) &&
        Objects.equals(this.faxNumber, shipmentShipTo.faxNumber) &&
        Objects.equals(this.emailAddress, shipmentShipTo.emailAddress) &&
        Objects.equals(this.address, shipmentShipTo.address) &&
        Objects.equals(this.locationID, shipmentShipTo.locationID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, attentionName, companyDisplayableName, taxIdentificationNumber, phone, faxNumber, emailAddress, address, locationID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentShipTo {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    attentionName: ").append(toIndentedString(attentionName)).append("\n");
    sb.append("    companyDisplayableName: ").append(toIndentedString(companyDisplayableName)).append("\n");
    sb.append("    taxIdentificationNumber: ").append(toIndentedString(taxIdentificationNumber)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    locationID: ").append(toIndentedString(locationID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
