/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.CODCODAmount;

/**
 * COD container  Indicates COD is requested. Shipment COD is only available for EU origin countries or territories and for shippers account type Daily Pickup and Drop Shipping. Not available to shipment with return service.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ShipmentServiceOptionsCOD {
  @JsonProperty("CODFundsCode")
  private String coDFundsCode = null;

  @JsonProperty("CODAmount")
  private CODCODAmount coDAmount = null;

  public ShipmentServiceOptionsCOD coDFundsCode(String coDFundsCode) {
    this.coDFundsCode = coDFundsCode;
    return this;
  }

   /**
   * For valid values refer to: Rating and Shipping COD Supported Countries or Territories in the Appendix.
   * @return coDFundsCode
  **/
  public String getCoDFundsCode() {
    return coDFundsCode;
  }

  public void setCoDFundsCode(String coDFundsCode) {
    this.coDFundsCode = coDFundsCode;
  }

  public ShipmentServiceOptionsCOD coDAmount(CODCODAmount coDAmount) {
    this.coDAmount = coDAmount;
    return this;
  }

   /**
   * Get coDAmount
   * @return coDAmount
  **/
  public CODCODAmount getCoDAmount() {
    return coDAmount;
  }

  public void setCoDAmount(CODCODAmount coDAmount) {
    this.coDAmount = coDAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentServiceOptionsCOD shipmentServiceOptionsCOD = (ShipmentServiceOptionsCOD) o;
    return Objects.equals(this.coDFundsCode, shipmentServiceOptionsCOD.coDFundsCode) &&
        Objects.equals(this.coDAmount, shipmentServiceOptionsCOD.coDAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coDFundsCode, coDAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentServiceOptionsCOD {\n");
    
    sb.append("    coDFundsCode: ").append(toIndentedString(coDFundsCode)).append("\n");
    sb.append("    coDAmount: ").append(toIndentedString(coDAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
