/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ShipmentResultsBillingWeight;
import com.ups.wwwcie.api.client.ShipmentResultsCODTurnInPage;
import com.ups.wwwcie.api.client.ShipmentResultsControlLogReceipt;
import com.ups.wwwcie.api.client.ShipmentResultsDisclaimer;
import com.ups.wwwcie.api.client.ShipmentResultsFRSShipmentData;
import com.ups.wwwcie.api.client.ShipmentResultsForm;
import com.ups.wwwcie.api.client.ShipmentResultsHighValueReport;
import com.ups.wwwcie.api.client.ShipmentResultsNegotiatedRateCharges;
import com.ups.wwwcie.api.client.ShipmentResultsPackageResults;
import com.ups.wwwcie.api.client.ShipmentResultsShipmentCharges;

import java.util.ArrayList;
import java.util.List;
/**
 * Shipment Results container.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ShipmentResponseShipmentResults {
  @JsonProperty("Disclaimer")
  private List<ShipmentResultsDisclaimer> disclaimer = null;

  @JsonProperty("ShipmentCharges")
  private ShipmentResultsShipmentCharges shipmentCharges = null;

  @JsonProperty("NegotiatedRateCharges")
  private ShipmentResultsNegotiatedRateCharges negotiatedRateCharges = null;

  @JsonProperty("FRSShipmentData")
  private ShipmentResultsFRSShipmentData frSShipmentData = null;

  @JsonProperty("RatingMethod")
  private String ratingMethod = null;

  @JsonProperty("BillableWeightCalculationMethod")
  private String billableWeightCalculationMethod = null;

  @JsonProperty("BillingWeight")
  private ShipmentResultsBillingWeight billingWeight = null;

  @JsonProperty("ShipmentIdentificationNumber")
  private String shipmentIdentificationNumber = null;

  @JsonProperty("MIDualReturnShipmentKey")
  private String miDualReturnShipmentKey = null;

  @JsonProperty("BarCodeImage")
  private String barCodeImage = null;

  @JsonProperty("PackageResults")
  private List<ShipmentResultsPackageResults> packageResults = null;

  @JsonProperty("ControlLogReceipt")
  private List<ShipmentResultsControlLogReceipt> controlLogReceipt = null;

  @JsonProperty("Form")
  private ShipmentResultsForm form = null;

  @JsonProperty("CODTurnInPage")
  private ShipmentResultsCODTurnInPage coDTurnInPage = null;

  @JsonProperty("HighValueReport")
  private ShipmentResultsHighValueReport highValueReport = null;

  @JsonProperty("LabelURL")
  private String labelURL = null;

  @JsonProperty("LocalLanguageLabelURL")
  private String localLanguageLabelURL = null;

  @JsonProperty("ReceiptURL")
  private String receiptURL = null;

  @JsonProperty("LocalLanguageReceiptURL")
  private String localLanguageReceiptURL = null;

  @JsonProperty("DGPaperImage")
  private List<String> dgPaperImage = null;

  @JsonProperty("MasterCartonID")
  private String masterCartonID = null;

  @JsonProperty("RoarRatedIndicator")
  private String roarRatedIndicator = null;

  public ShipmentResponseShipmentResults disclaimer(List<ShipmentResultsDisclaimer> disclaimer) {
    this.disclaimer = disclaimer;
    return this;
  }

  public ShipmentResponseShipmentResults addDisclaimerItem(ShipmentResultsDisclaimer disclaimerItem) {
    if (this.disclaimer == null) {
      this.disclaimer = new ArrayList<>();
    }
    this.disclaimer.add(disclaimerItem);
    return this;
  }

   /**
   * Get disclaimer
   * @return disclaimer
  **/
  public List<ShipmentResultsDisclaimer> getDisclaimer() {
    return disclaimer;
  }

  public void setDisclaimer(List<ShipmentResultsDisclaimer> disclaimer) {
    this.disclaimer = disclaimer;
  }

  public ShipmentResponseShipmentResults shipmentCharges(ShipmentResultsShipmentCharges shipmentCharges) {
    this.shipmentCharges = shipmentCharges;
    return this;
  }

   /**
   * Get shipmentCharges
   * @return shipmentCharges
  **/
  public ShipmentResultsShipmentCharges getShipmentCharges() {
    return shipmentCharges;
  }

  public void setShipmentCharges(ShipmentResultsShipmentCharges shipmentCharges) {
    this.shipmentCharges = shipmentCharges;
  }

  public ShipmentResponseShipmentResults negotiatedRateCharges(ShipmentResultsNegotiatedRateCharges negotiatedRateCharges) {
    this.negotiatedRateCharges = negotiatedRateCharges;
    return this;
  }

   /**
   * Get negotiatedRateCharges
   * @return negotiatedRateCharges
  **/
  public ShipmentResultsNegotiatedRateCharges getNegotiatedRateCharges() {
    return negotiatedRateCharges;
  }

  public void setNegotiatedRateCharges(ShipmentResultsNegotiatedRateCharges negotiatedRateCharges) {
    this.negotiatedRateCharges = negotiatedRateCharges;
  }

  public ShipmentResponseShipmentResults frSShipmentData(ShipmentResultsFRSShipmentData frSShipmentData) {
    this.frSShipmentData = frSShipmentData;
    return this;
  }

   /**
   * Get frSShipmentData
   * @return frSShipmentData
  **/
  public ShipmentResultsFRSShipmentData getFrSShipmentData() {
    return frSShipmentData;
  }

  public void setFrSShipmentData(ShipmentResultsFRSShipmentData frSShipmentData) {
    this.frSShipmentData = frSShipmentData;
  }

  public ShipmentResponseShipmentResults ratingMethod(String ratingMethod) {
    this.ratingMethod = ratingMethod;
    return this;
  }

   /**
   * RatingMethod is to indicate whether the Shipment was rated as shipment level or package level. This information will be returned only if RatingMethodRequestedIndicator is present in the request.  Valid values: 01 &#x3D; Shipment level 02 &#x3D; Package level
   * @return ratingMethod
  **/
  public String getRatingMethod() {
    return ratingMethod;
  }

  public void setRatingMethod(String ratingMethod) {
    this.ratingMethod = ratingMethod;
  }

  public ShipmentResponseShipmentResults billableWeightCalculationMethod(String billableWeightCalculationMethod) {
    this.billableWeightCalculationMethod = billableWeightCalculationMethod;
    return this;
  }

   /**
   * BillableWeightCalculationMethod is to indicate whether the billable weight calculation method utilized was - the package level or shipment level. This information will be returned only if RatingMethodRequestedIndicator is present in the request.  Valid values: 01 &#x3D; Shipment Billable Weight 02 &#x3D; Package Billable Weight
   * @return billableWeightCalculationMethod
  **/
  public String getBillableWeightCalculationMethod() {
    return billableWeightCalculationMethod;
  }

  public void setBillableWeightCalculationMethod(String billableWeightCalculationMethod) {
    this.billableWeightCalculationMethod = billableWeightCalculationMethod;
  }

  public ShipmentResponseShipmentResults billingWeight(ShipmentResultsBillingWeight billingWeight) {
    this.billingWeight = billingWeight;
    return this;
  }

   /**
   * Get billingWeight
   * @return billingWeight
  **/
  public ShipmentResultsBillingWeight getBillingWeight() {
    return billingWeight;
  }

  public void setBillingWeight(ShipmentResultsBillingWeight billingWeight) {
    this.billingWeight = billingWeight;
  }

  public ShipmentResponseShipmentResults shipmentIdentificationNumber(String shipmentIdentificationNumber) {
    this.shipmentIdentificationNumber = shipmentIdentificationNumber;
    return this;
  }

   /**
   * Returned UPS shipment ID number.1Z Number of the first package in the shipment.
   * @return shipmentIdentificationNumber
  **/
  public String getShipmentIdentificationNumber() {
    return shipmentIdentificationNumber;
  }

  public void setShipmentIdentificationNumber(String shipmentIdentificationNumber) {
    this.shipmentIdentificationNumber = shipmentIdentificationNumber;
  }

  public ShipmentResponseShipmentResults miDualReturnShipmentKey(String miDualReturnShipmentKey) {
    this.miDualReturnShipmentKey = miDualReturnShipmentKey;
    return this;
  }

   /**
   * MIDualReturnShipmentKey is unique key required to process Mail Innovations Dual Return Shipment.   The unique identifier (key) would be returned in response of first phase of Mail Innovations Dual Return Shipments.   This unique identifier (key) would be part of request for second phase of Mail Innovations Dual Return Shipments and would be played back in response for second phase of Mail Innovations Dual Return Shipment.  If the shipment is a Package return shipment, the package tracking number will be concatenated with the system time (in the format YYYY-MM-DDHH.MM.SS.NNN) and followed by service code.   If the shipment is an MI Returns shipment, the Mail Manifest ID (MMI) will be concatenated with the system time.
   * @return miDualReturnShipmentKey
  **/
  public String getMiDualReturnShipmentKey() {
    return miDualReturnShipmentKey;
  }

  public void setMiDualReturnShipmentKey(String miDualReturnShipmentKey) {
    this.miDualReturnShipmentKey = miDualReturnShipmentKey;
  }

  public ShipmentResponseShipmentResults barCodeImage(String barCodeImage) {
    this.barCodeImage = barCodeImage;
    return this;
  }

   /**
   * Bar Code Image will be returned as Base 64 encoded graphic image. Bar Code Image will be returned if BarCodeImageIndicator or BarCodeAndLabelIndicator is present.
   * @return barCodeImage
  **/
  public String getBarCodeImage() {
    return barCodeImage;
  }

  public void setBarCodeImage(String barCodeImage) {
    this.barCodeImage = barCodeImage;
  }

  public ShipmentResponseShipmentResults packageResults(List<ShipmentResultsPackageResults> packageResults) {
    this.packageResults = packageResults;
    return this;
  }

  public ShipmentResponseShipmentResults addPackageResultsItem(ShipmentResultsPackageResults packageResultsItem) {
    if (this.packageResults == null) {
      this.packageResults = new ArrayList<>();
    }
    this.packageResults.add(packageResultsItem);
    return this;
  }

   /**
   * Get packageResults
   * @return packageResults
  **/
  public List<ShipmentResultsPackageResults> getPackageResults() {
    return packageResults;
  }

  public void setPackageResults(List<ShipmentResultsPackageResults> packageResults) {
    this.packageResults = packageResults;
  }

  public ShipmentResponseShipmentResults controlLogReceipt(List<ShipmentResultsControlLogReceipt> controlLogReceipt) {
    this.controlLogReceipt = controlLogReceipt;
    return this;
  }

  public ShipmentResponseShipmentResults addControlLogReceiptItem(ShipmentResultsControlLogReceipt controlLogReceiptItem) {
    if (this.controlLogReceipt == null) {
      this.controlLogReceipt = new ArrayList<>();
    }
    this.controlLogReceipt.add(controlLogReceiptItem);
    return this;
  }

   /**
   * Get controlLogReceipt
   * @return controlLogReceipt
  **/
  public List<ShipmentResultsControlLogReceipt> getControlLogReceipt() {
    return controlLogReceipt;
  }

  public void setControlLogReceipt(List<ShipmentResultsControlLogReceipt> controlLogReceipt) {
    this.controlLogReceipt = controlLogReceipt;
  }

  public ShipmentResponseShipmentResults form(ShipmentResultsForm form) {
    this.form = form;
    return this;
  }

   /**
   * Get form
   * @return form
  **/
  public ShipmentResultsForm getForm() {
    return form;
  }

  public void setForm(ShipmentResultsForm form) {
    this.form = form;
  }

  public ShipmentResponseShipmentResults coDTurnInPage(ShipmentResultsCODTurnInPage coDTurnInPage) {
    this.coDTurnInPage = coDTurnInPage;
    return this;
  }

   /**
   * Get coDTurnInPage
   * @return coDTurnInPage
  **/
  public ShipmentResultsCODTurnInPage getCoDTurnInPage() {
    return coDTurnInPage;
  }

  public void setCoDTurnInPage(ShipmentResultsCODTurnInPage coDTurnInPage) {
    this.coDTurnInPage = coDTurnInPage;
  }

  public ShipmentResponseShipmentResults highValueReport(ShipmentResultsHighValueReport highValueReport) {
    this.highValueReport = highValueReport;
    return this;
  }

   /**
   * Get highValueReport
   * @return highValueReport
  **/
  public ShipmentResultsHighValueReport getHighValueReport() {
    return highValueReport;
  }

  public void setHighValueReport(ShipmentResultsHighValueReport highValueReport) {
    this.highValueReport = highValueReport;
  }

  public ShipmentResponseShipmentResults labelURL(String labelURL) {
    this.labelURL = labelURL;
    return this;
  }

   /**
   * URL will point to a page wherein label, receipt and other documents, if applicable, such as HighValueReport, CustomsInvoice and ImportControl instructions can be requested. LabelURL is returned only if the LabelLinksIndicator is requested for following shipments: Print/Electronic ImportControl shipment Print/Electronic Return shipment.  Forward shipment except for Mail Innovations Forward.
   * @return labelURL
  **/
  public String getLabelURL() {
    return labelURL;
  }

  public void setLabelURL(String labelURL) {
    this.labelURL = labelURL;
  }

  public ShipmentResponseShipmentResults localLanguageLabelURL(String localLanguageLabelURL) {
    this.localLanguageLabelURL = localLanguageLabelURL;
    return this;
  }

   /**
   * URL will point to a page wherein label, receipt and other documents, if applicable, such as HighValueReport, CustomsInvoice and ImportControl instructions can be requested. LocalLanguageLabelURL is returned only if the LabelLinksIndicator is requested for following shipments: Print/Electronic ImportControl shipment Print/Electronic Return shipment.  Forward shipment except for Mail Innovations Forward.  Not returned if LabelLinksIndicator is requested with Locale element.
   * @return localLanguageLabelURL
  **/
  public String getLocalLanguageLabelURL() {
    return localLanguageLabelURL;
  }

  public void setLocalLanguageLabelURL(String localLanguageLabelURL) {
    this.localLanguageLabelURL = localLanguageLabelURL;
  }

  public ShipmentResponseShipmentResults receiptURL(String receiptURL) {
    this.receiptURL = receiptURL;
    return this;
  }

   /**
   * URL will point to a page wherein label, receipt and other documents, if applicable, such as HighValueReport, CustomsInvoice and ImportControl instructions can be requested. ReceiptURL is returned only if the LabelLinksIndicator is requested for following shipments: Print/Electronic ImportControl shipment Print/Electronic Return shipment.
   * @return receiptURL
  **/
  public String getReceiptURL() {
    return receiptURL;
  }

  public void setReceiptURL(String receiptURL) {
    this.receiptURL = receiptURL;
  }

  public ShipmentResponseShipmentResults localLanguageReceiptURL(String localLanguageReceiptURL) {
    this.localLanguageReceiptURL = localLanguageReceiptURL;
    return this;
  }

   /**
   * URL will point to a page wherein label, receipt and other documents, if applicable, such as HighValueReport, CustomsInvoice and ImportControl instructions can be requested. LocalLanguageReceiptURL is returned only if the LabelLinksIndicator is requested for following shipments: Print/Electronic ImportControl shipment Print/Electronic Return shipment.   Not returned if LabelLinksIndicator is requested with Locale element.
   * @return localLanguageReceiptURL
  **/
  public String getLocalLanguageReceiptURL() {
    return localLanguageReceiptURL;
  }

  public void setLocalLanguageReceiptURL(String localLanguageReceiptURL) {
    this.localLanguageReceiptURL = localLanguageReceiptURL;
  }

  public ShipmentResponseShipmentResults dgPaperImage(List<String> dgPaperImage) {
    this.dgPaperImage = dgPaperImage;
    return this;
  }

  public ShipmentResponseShipmentResults addDgPaperImageItem(String dgPaperImageItem) {
    if (this.dgPaperImage == null) {
      this.dgPaperImage = new ArrayList<>();
    }
    this.dgPaperImage.add(dgPaperImageItem);
    return this;
  }

   /**
   * Dangrous Good Paper Image in pdf format. One multipage PDF document will be returned that will contain all required Dangrous Goods shipping paper copies for all Dangerous Goods packages.  Only returned when DGSignatoryInfo is present.
   * @return dgPaperImage
  **/
  public List<String> getDgPaperImage() {
    return dgPaperImage;
  }

  public void setDgPaperImage(List<String> dgPaperImage) {
    this.dgPaperImage = dgPaperImage;
  }

  public ShipmentResponseShipmentResults masterCartonID(String masterCartonID) {
    this.masterCartonID = masterCartonID;
    return this;
  }

   /**
   * Master Carton ID. MasterCartonID will be return if MasterCartonIndicator is present in request.
   * @return masterCartonID
  **/
  public String getMasterCartonID() {
    return masterCartonID;
  }

  public void setMasterCartonID(String masterCartonID) {
    this.masterCartonID = masterCartonID;
  }

  public ShipmentResponseShipmentResults roarRatedIndicator(String roarRatedIndicator) {
    this.roarRatedIndicator = roarRatedIndicator;
    return this;
  }

   /**
   * Informational only
   * @return roarRatedIndicator
  **/
  public String getRoarRatedIndicator() {
    return roarRatedIndicator;
  }

  public void setRoarRatedIndicator(String roarRatedIndicator) {
    this.roarRatedIndicator = roarRatedIndicator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentResponseShipmentResults shipmentResponseShipmentResults = (ShipmentResponseShipmentResults) o;
    return Objects.equals(this.disclaimer, shipmentResponseShipmentResults.disclaimer) &&
        Objects.equals(this.shipmentCharges, shipmentResponseShipmentResults.shipmentCharges) &&
        Objects.equals(this.negotiatedRateCharges, shipmentResponseShipmentResults.negotiatedRateCharges) &&
        Objects.equals(this.frSShipmentData, shipmentResponseShipmentResults.frSShipmentData) &&
        Objects.equals(this.ratingMethod, shipmentResponseShipmentResults.ratingMethod) &&
        Objects.equals(this.billableWeightCalculationMethod, shipmentResponseShipmentResults.billableWeightCalculationMethod) &&
        Objects.equals(this.billingWeight, shipmentResponseShipmentResults.billingWeight) &&
        Objects.equals(this.shipmentIdentificationNumber, shipmentResponseShipmentResults.shipmentIdentificationNumber) &&
        Objects.equals(this.miDualReturnShipmentKey, shipmentResponseShipmentResults.miDualReturnShipmentKey) &&
        Objects.equals(this.barCodeImage, shipmentResponseShipmentResults.barCodeImage) &&
        Objects.equals(this.packageResults, shipmentResponseShipmentResults.packageResults) &&
        Objects.equals(this.controlLogReceipt, shipmentResponseShipmentResults.controlLogReceipt) &&
        Objects.equals(this.form, shipmentResponseShipmentResults.form) &&
        Objects.equals(this.coDTurnInPage, shipmentResponseShipmentResults.coDTurnInPage) &&
        Objects.equals(this.highValueReport, shipmentResponseShipmentResults.highValueReport) &&
        Objects.equals(this.labelURL, shipmentResponseShipmentResults.labelURL) &&
        Objects.equals(this.localLanguageLabelURL, shipmentResponseShipmentResults.localLanguageLabelURL) &&
        Objects.equals(this.receiptURL, shipmentResponseShipmentResults.receiptURL) &&
        Objects.equals(this.localLanguageReceiptURL, shipmentResponseShipmentResults.localLanguageReceiptURL) &&
        Objects.equals(this.dgPaperImage, shipmentResponseShipmentResults.dgPaperImage) &&
        Objects.equals(this.masterCartonID, shipmentResponseShipmentResults.masterCartonID) &&
        Objects.equals(this.roarRatedIndicator, shipmentResponseShipmentResults.roarRatedIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disclaimer, shipmentCharges, negotiatedRateCharges, frSShipmentData, ratingMethod, billableWeightCalculationMethod, billingWeight, shipmentIdentificationNumber, miDualReturnShipmentKey, barCodeImage, packageResults, controlLogReceipt, form, coDTurnInPage, highValueReport, labelURL, localLanguageLabelURL, receiptURL, localLanguageReceiptURL, dgPaperImage, masterCartonID, roarRatedIndicator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentResponseShipmentResults {\n");
    
    sb.append("    disclaimer: ").append(toIndentedString(disclaimer)).append("\n");
    sb.append("    shipmentCharges: ").append(toIndentedString(shipmentCharges)).append("\n");
    sb.append("    negotiatedRateCharges: ").append(toIndentedString(negotiatedRateCharges)).append("\n");
    sb.append("    frSShipmentData: ").append(toIndentedString(frSShipmentData)).append("\n");
    sb.append("    ratingMethod: ").append(toIndentedString(ratingMethod)).append("\n");
    sb.append("    billableWeightCalculationMethod: ").append(toIndentedString(billableWeightCalculationMethod)).append("\n");
    sb.append("    billingWeight: ").append(toIndentedString(billingWeight)).append("\n");
    sb.append("    shipmentIdentificationNumber: ").append(toIndentedString(shipmentIdentificationNumber)).append("\n");
    sb.append("    miDualReturnShipmentKey: ").append(toIndentedString(miDualReturnShipmentKey)).append("\n");
    sb.append("    barCodeImage: ").append(toIndentedString(barCodeImage)).append("\n");
    sb.append("    packageResults: ").append(toIndentedString(packageResults)).append("\n");
    sb.append("    controlLogReceipt: ").append(toIndentedString(controlLogReceipt)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    coDTurnInPage: ").append(toIndentedString(coDTurnInPage)).append("\n");
    sb.append("    highValueReport: ").append(toIndentedString(highValueReport)).append("\n");
    sb.append("    labelURL: ").append(toIndentedString(labelURL)).append("\n");
    sb.append("    localLanguageLabelURL: ").append(toIndentedString(localLanguageLabelURL)).append("\n");
    sb.append("    receiptURL: ").append(toIndentedString(receiptURL)).append("\n");
    sb.append("    localLanguageReceiptURL: ").append(toIndentedString(localLanguageReceiptURL)).append("\n");
    sb.append("    dgPaperImage: ").append(toIndentedString(dgPaperImage)).append("\n");
    sb.append("    masterCartonID: ").append(toIndentedString(masterCartonID)).append("\n");
    sb.append("    roarRatedIndicator: ").append(toIndentedString(roarRatedIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
