/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ShipmentRatingOptions container.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ShipmentShipmentRatingOptions {
  @JsonProperty("NegotiatedRatesIndicator")
  private String negotiatedRatesIndicator = null;

  @JsonProperty("FRSShipmentIndicator")
  private String frSShipmentIndicator = null;

  @JsonProperty("RateChartIndicator")
  private String rateChartIndicator = null;

  @JsonProperty("TPFCNegotiatedRatesIndicator")
  private String tpFCNegotiatedRatesIndicator = null;

  @JsonProperty("UserLevelDiscountIndicator")
  private String userLevelDiscountIndicator = null;

  public ShipmentShipmentRatingOptions negotiatedRatesIndicator(String negotiatedRatesIndicator) {
    this.negotiatedRatesIndicator = negotiatedRatesIndicator;
    return this;
  }

   /**
   * Negotiated Rates option indicator. If the indicator is present and the Shipper is authorized then Negotiated Rates should be returned in the response.  Negotiated Rates are of two types Account Based Rates (ABR) and Web Discount Rates. Negotiated Rates are only returned for qualified Shipper Account Numbers.   Eligibility is determined using the combination of UserId and the Shipper&#x27;s Shipper Account Number. If the user is qualified, both Published rates and Negotiated rates are returned to the user. If the UserId and Shipper Account   Number are not qualified for Negotiated rates, a warning message is returned that indicates ineligibility and only the Published rates are returned in the response. As per discount eligibility of user, negotiated rates in the response may contain ABR or Web discount rates.
   * @return negotiatedRatesIndicator
  **/
  public String getNegotiatedRatesIndicator() {
    return negotiatedRatesIndicator;
  }

  public void setNegotiatedRatesIndicator(String negotiatedRatesIndicator) {
    this.negotiatedRatesIndicator = negotiatedRatesIndicator;
  }

  public ShipmentShipmentRatingOptions frSShipmentIndicator(String frSShipmentIndicator) {
    this.frSShipmentIndicator = frSShipmentIndicator;
    return this;
  }

   /**
   * Ground Freight Pricing Rates option indicator. If the Ground Freight Pricing Shipment indicator is enabled and Shipper number is authorized then Ground Freight Pricing rates should be returned in the response.  The Shipper account number must be qualified to receive Ground Freight Pricing Density Based Shipment rates. Only the Shipper account number taken from /ShipmentRequest/Shipment/FRSPaymentInformation/AccountNumber is used when checking qualification for Ground Freight Pricing Density Based rates.
   * @return frSShipmentIndicator
  **/
  public String getFrSShipmentIndicator() {
    return frSShipmentIndicator;
  }

  public void setFrSShipmentIndicator(String frSShipmentIndicator) {
    this.frSShipmentIndicator = frSShipmentIndicator;
  }

  public ShipmentShipmentRatingOptions rateChartIndicator(String rateChartIndicator) {
    this.rateChartIndicator = rateChartIndicator;
    return this;
  }

   /**
   * RateChartIndicator, if present in request, response will contain RateChart element.
   * @return rateChartIndicator
  **/
  public String getRateChartIndicator() {
    return rateChartIndicator;
  }

  public void setRateChartIndicator(String rateChartIndicator) {
    this.rateChartIndicator = rateChartIndicator;
  }

  public ShipmentShipmentRatingOptions tpFCNegotiatedRatesIndicator(String tpFCNegotiatedRatesIndicator) {
    this.tpFCNegotiatedRatesIndicator = tpFCNegotiatedRatesIndicator;
    return this;
  }

   /**
   * This indicator applies for a third party (3P) / Freight collect (FC) shipment only.   For 3P/FC shipment if the shipper wishes to request for the negotiated rates of the third party then this indicator should be included in the request.   If authorized the 3P/FC negotiated rates will be applied to the shipment and rates will be returned in response.
   * @return tpFCNegotiatedRatesIndicator
  **/
  public String getTpFCNegotiatedRatesIndicator() {
    return tpFCNegotiatedRatesIndicator;
  }

  public void setTpFCNegotiatedRatesIndicator(String tpFCNegotiatedRatesIndicator) {
    this.tpFCNegotiatedRatesIndicator = tpFCNegotiatedRatesIndicator;
  }

  public ShipmentShipmentRatingOptions userLevelDiscountIndicator(String userLevelDiscountIndicator) {
    this.userLevelDiscountIndicator = userLevelDiscountIndicator;
    return this;
  }

   /**
   * If this indicator is present user level discount will be applied to rates if applicable  Conditions checked: This indicator should be present Shipper number should not be present User should be eligible for user level discount
   * @return userLevelDiscountIndicator
  **/
  public String getUserLevelDiscountIndicator() {
    return userLevelDiscountIndicator;
  }

  public void setUserLevelDiscountIndicator(String userLevelDiscountIndicator) {
    this.userLevelDiscountIndicator = userLevelDiscountIndicator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentShipmentRatingOptions shipmentShipmentRatingOptions = (ShipmentShipmentRatingOptions) o;
    return Objects.equals(this.negotiatedRatesIndicator, shipmentShipmentRatingOptions.negotiatedRatesIndicator) &&
        Objects.equals(this.frSShipmentIndicator, shipmentShipmentRatingOptions.frSShipmentIndicator) &&
        Objects.equals(this.rateChartIndicator, shipmentShipmentRatingOptions.rateChartIndicator) &&
        Objects.equals(this.tpFCNegotiatedRatesIndicator, shipmentShipmentRatingOptions.tpFCNegotiatedRatesIndicator) &&
        Objects.equals(this.userLevelDiscountIndicator, shipmentShipmentRatingOptions.userLevelDiscountIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(negotiatedRatesIndicator, frSShipmentIndicator, rateChartIndicator, tpFCNegotiatedRatesIndicator, userLevelDiscountIndicator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentShipmentRatingOptions {\n");
    
    sb.append("    negotiatedRatesIndicator: ").append(toIndentedString(negotiatedRatesIndicator)).append("\n");
    sb.append("    frSShipmentIndicator: ").append(toIndentedString(frSShipmentIndicator)).append("\n");
    sb.append("    rateChartIndicator: ").append(toIndentedString(rateChartIndicator)).append("\n");
    sb.append("    tpFCNegotiatedRatesIndicator: ").append(toIndentedString(tpFCNegotiatedRatesIndicator)).append("\n");
    sb.append("    userLevelDiscountIndicator: ").append(toIndentedString(userLevelDiscountIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
