/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.FRSShipmentDataFreightDensityRate;
import com.ups.wwwcie.api.client.FRSShipmentDataHandlingUnits;
import com.ups.wwwcie.api.client.FRSShipmentDataTransportationCharges;

import java.util.ArrayList;
import java.util.List;
/**
 * Ground Freight Pricing Shipment data container. Ground Freight Pricing shipment data is only guaranteed to be returned for Ground Freight Pricing shipments only.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class ShipmentResultsFRSShipmentData {
  @JsonProperty("TransportationCharges")
  private FRSShipmentDataTransportationCharges transportationCharges = null;

  @JsonProperty("FreightDensityRate")
  private FRSShipmentDataFreightDensityRate freightDensityRate = null;

  @JsonProperty("HandlingUnits")
  private List<FRSShipmentDataHandlingUnits> handlingUnits = null;

  public ShipmentResultsFRSShipmentData transportationCharges(FRSShipmentDataTransportationCharges transportationCharges) {
    this.transportationCharges = transportationCharges;
    return this;
  }

   /**
   * Get transportationCharges
   * @return transportationCharges
  **/
  public FRSShipmentDataTransportationCharges getTransportationCharges() {
    return transportationCharges;
  }

  public void setTransportationCharges(FRSShipmentDataTransportationCharges transportationCharges) {
    this.transportationCharges = transportationCharges;
  }

  public ShipmentResultsFRSShipmentData freightDensityRate(FRSShipmentDataFreightDensityRate freightDensityRate) {
    this.freightDensityRate = freightDensityRate;
    return this;
  }

   /**
   * Get freightDensityRate
   * @return freightDensityRate
  **/
  public FRSShipmentDataFreightDensityRate getFreightDensityRate() {
    return freightDensityRate;
  }

  public void setFreightDensityRate(FRSShipmentDataFreightDensityRate freightDensityRate) {
    this.freightDensityRate = freightDensityRate;
  }

  public ShipmentResultsFRSShipmentData handlingUnits(List<FRSShipmentDataHandlingUnits> handlingUnits) {
    this.handlingUnits = handlingUnits;
    return this;
  }

  public ShipmentResultsFRSShipmentData addHandlingUnitsItem(FRSShipmentDataHandlingUnits handlingUnitsItem) {
    if (this.handlingUnits == null) {
      this.handlingUnits = new ArrayList<>();
    }
    this.handlingUnits.add(handlingUnitsItem);
    return this;
  }

   /**
   * Get handlingUnits
   * @return handlingUnits
  **/
  public List<FRSShipmentDataHandlingUnits> getHandlingUnits() {
    return handlingUnits;
  }

  public void setHandlingUnits(List<FRSShipmentDataHandlingUnits> handlingUnits) {
    this.handlingUnits = handlingUnits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentResultsFRSShipmentData shipmentResultsFRSShipmentData = (ShipmentResultsFRSShipmentData) o;
    return Objects.equals(this.transportationCharges, shipmentResultsFRSShipmentData.transportationCharges) &&
        Objects.equals(this.freightDensityRate, shipmentResultsFRSShipmentData.freightDensityRate) &&
        Objects.equals(this.handlingUnits, shipmentResultsFRSShipmentData.handlingUnits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transportationCharges, freightDensityRate, handlingUnits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentResultsFRSShipmentData {\n");
    
    sb.append("    transportationCharges: ").append(toIndentedString(transportationCharges)).append("\n");
    sb.append("    freightDensityRate: ").append(toIndentedString(freightDensityRate)).append("\n");
    sb.append("    handlingUnits: ").append(toIndentedString(handlingUnits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
