/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A range of time the package was picked up.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class TrackingCandidatePickupDateRange {
  @JsonProperty("BeginDate")
  private String beginDate = null;

  @JsonProperty("EndDate")
  private String endDate = null;

  public TrackingCandidatePickupDateRange beginDate(String beginDate) {
    this.beginDate = beginDate;
    return this;
  }

   /**
   * The beginning of the date range for the candidate. Format: YYYYMMDD  Service is only supported for 30 days
   * @return beginDate
  **/
  public String getBeginDate() {
    return beginDate;
  }

  public void setBeginDate(String beginDate) {
    this.beginDate = beginDate;
  }

  public TrackingCandidatePickupDateRange endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * The end of the date range for the candidate. Format: YYYYMMDD
   * @return endDate
  **/
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackingCandidatePickupDateRange trackingCandidatePickupDateRange = (TrackingCandidatePickupDateRange) o;
    return Objects.equals(this.beginDate, trackingCandidatePickupDateRange.beginDate) &&
        Objects.equals(this.endDate, trackingCandidatePickupDateRange.endDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beginDate, endDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackingCandidatePickupDateRange {\n");
    
    sb.append("    beginDate: ").append(toIndentedString(beginDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
