/*
 * Ship
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.VoidShipmentResponsePackageLevelResult;
import com.ups.wwwcie.api.client.VoidShipmentResponseResponse;
import com.ups.wwwcie.api.client.VoidShipmentResponseSummaryResult;

import java.util.ArrayList;
import java.util.List;
/**
 * Void Response Container.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:52.173749300+07:00[Asia/Bangkok]")
public class VoidShipmentResponse {
  @JsonProperty("Response")
  private VoidShipmentResponseResponse response = null;

  @JsonProperty("SummaryResult")
  private VoidShipmentResponseSummaryResult summaryResult = null;

  @JsonProperty("PackageLevelResult")
  private List<VoidShipmentResponsePackageLevelResult> packageLevelResult = null;

  public VoidShipmentResponse response(VoidShipmentResponseResponse response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  public VoidShipmentResponseResponse getResponse() {
    return response;
  }

  public void setResponse(VoidShipmentResponseResponse response) {
    this.response = response;
  }

  public VoidShipmentResponse summaryResult(VoidShipmentResponseSummaryResult summaryResult) {
    this.summaryResult = summaryResult;
    return this;
  }

   /**
   * Get summaryResult
   * @return summaryResult
  **/
  public VoidShipmentResponseSummaryResult getSummaryResult() {
    return summaryResult;
  }

  public void setSummaryResult(VoidShipmentResponseSummaryResult summaryResult) {
    this.summaryResult = summaryResult;
  }

  public VoidShipmentResponse packageLevelResult(List<VoidShipmentResponsePackageLevelResult> packageLevelResult) {
    this.packageLevelResult = packageLevelResult;
    return this;
  }

  public VoidShipmentResponse addPackageLevelResultItem(VoidShipmentResponsePackageLevelResult packageLevelResultItem) {
    if (this.packageLevelResult == null) {
      this.packageLevelResult = new ArrayList<>();
    }
    this.packageLevelResult.add(packageLevelResultItem);
    return this;
  }

   /**
   * Get packageLevelResult
   * @return packageLevelResult
  **/
  public List<VoidShipmentResponsePackageLevelResult> getPackageLevelResult() {
    return packageLevelResult;
  }

  public void setPackageLevelResult(List<VoidShipmentResponsePackageLevelResult> packageLevelResult) {
    this.packageLevelResult = packageLevelResult;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoidShipmentResponse voidShipmentResponse = (VoidShipmentResponse) o;
    return Objects.equals(this.response, voidShipmentResponse.response) &&
        Objects.equals(this.summaryResult, voidShipmentResponse.summaryResult) &&
        Objects.equals(this.packageLevelResult, voidShipmentResponse.packageLevelResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, summaryResult, packageLevelResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoidShipmentResponse {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    summaryResult: ").append(toIndentedString(summaryResult)).append("\n");
    sb.append("    packageLevelResult: ").append(toIndentedString(packageLevelResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
