/*
 * Address Validation - Street Level
 * The Address Validation Street Level API can be used to check addresses against the United States Postal Service database of valid addresses in the U.S. and Puerto Rico.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * AddressKeyFormat container. The Key format is based on addressing standards jointly developed by the Postal Service and mailing industry.  The information provided in the Address Key container will be returned in the same format.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:02:35.133666300+07:00[Asia/Bangkok]")
public class XAVRequestAddressKeyFormat {
  @JsonProperty("ConsigneeName")
  private String consigneeName = null;

  @JsonProperty("AttentionName")
  private String attentionName = null;

  @JsonProperty("AddressLine")
  private List<String> addressLine = null;

  @JsonProperty("Region")
  private String region = null;

  @JsonProperty("PoliticalDivision2")
  private String politicalDivision2 = null;

  @JsonProperty("PoliticalDivision1")
  private String politicalDivision1 = null;

  @JsonProperty("PostcodePrimaryLow")
  private String postcodePrimaryLow = null;

  @JsonProperty("PostcodeExtendedLow")
  private String postcodeExtendedLow = null;

  @JsonProperty("Urbanization")
  private String urbanization = null;

  @JsonProperty("CountryCode")
  private String countryCode = null;

  public XAVRequestAddressKeyFormat consigneeName(String consigneeName) {
    this.consigneeName = consigneeName;
    return this;
  }

   /**
   * Name of business, company or person. Not returned if user selects the RegionalRequestIndicator.
   * @return consigneeName
  **/
  public String getConsigneeName() {
    return consigneeName;
  }

  public void setConsigneeName(String consigneeName) {
    this.consigneeName = consigneeName;
  }

  public XAVRequestAddressKeyFormat attentionName(String attentionName) {
    this.attentionName = attentionName;
    return this;
  }

   /**
   * Name of building. Not returned if user selects the RegionalRequestIndicator.
   * @return attentionName
  **/
  public String getAttentionName() {
    return attentionName;
  }

  public void setAttentionName(String attentionName) {
    this.attentionName = attentionName;
  }

  public XAVRequestAddressKeyFormat addressLine(List<String> addressLine) {
    this.addressLine = addressLine;
    return this;
  }

  public XAVRequestAddressKeyFormat addAddressLineItem(String addressLineItem) {
    if (this.addressLine == null) {
      this.addressLine = new ArrayList<>();
    }
    this.addressLine.add(addressLineItem);
    return this;
  }

   /**
   * Address line (street number, street name and street type, and political division 1, political division 2 and postal code) used for street level information. Additional secondary information (apartment, suite, floor, etc.) Applicable to US and PR only.  Not returned if user selects the RegionalRequestIndicator.
   * @return addressLine
  **/
  public List<String> getAddressLine() {
    return addressLine;
  }

  public void setAddressLine(List<String> addressLine) {
    this.addressLine = addressLine;
  }

  public XAVRequestAddressKeyFormat region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Single entry containing in this order  Political Division 2, Political Division 1 and Post Code Primary Low and/or PostcodeExtendedLow.
   * @return region
  **/
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public XAVRequestAddressKeyFormat politicalDivision2(String politicalDivision2) {
    this.politicalDivision2 = politicalDivision2;
    return this;
  }

   /**
   * City or Town name.
   * @return politicalDivision2
  **/
  public String getPoliticalDivision2() {
    return politicalDivision2;
  }

  public void setPoliticalDivision2(String politicalDivision2) {
    this.politicalDivision2 = politicalDivision2;
  }

  public XAVRequestAddressKeyFormat politicalDivision1(String politicalDivision1) {
    this.politicalDivision1 = politicalDivision1;
    return this;
  }

   /**
   * State/Province.  Returned if the location is within a State/Province/Territory.  For International: returned if user enters valid Country or Territory Code, and City/postal code and it has a match.  For Domestic addresses, the value must be a valid 2-character value (per US Mail standards).  For International the full State or Province name will be returned.
   * @return politicalDivision1
  **/
  public String getPoliticalDivision1() {
    return politicalDivision1;
  }

  public void setPoliticalDivision1(String politicalDivision1) {
    this.politicalDivision1 = politicalDivision1;
  }

  public XAVRequestAddressKeyFormat postcodePrimaryLow(String postcodePrimaryLow) {
    this.postcodePrimaryLow = postcodePrimaryLow;
    return this;
  }

   /**
   * Low-end Postal Code. Returned for countries or territories with Postal Codes. May be alphanumeric.
   * @return postcodePrimaryLow
  **/
  public String getPostcodePrimaryLow() {
    return postcodePrimaryLow;
  }

  public void setPostcodePrimaryLow(String postcodePrimaryLow) {
    this.postcodePrimaryLow = postcodePrimaryLow;
  }

  public XAVRequestAddressKeyFormat postcodeExtendedLow(String postcodeExtendedLow) {
    this.postcodeExtendedLow = postcodeExtendedLow;
    return this;
  }

   /**
   * Low-end extended postal code in a range. Example in quotes: Postal Code 30076-&#x27;1234&#x27;.  Only returned in candidate list. May be alphanumeric
   * @return postcodeExtendedLow
  **/
  public String getPostcodeExtendedLow() {
    return postcodeExtendedLow;
  }

  public void setPostcodeExtendedLow(String postcodeExtendedLow) {
    this.postcodeExtendedLow = postcodeExtendedLow;
  }

  public XAVRequestAddressKeyFormat urbanization(String urbanization) {
    this.urbanization = urbanization;
    return this;
  }

   /**
   * Puerto Rico Political Division 3. Only Valid for Puerto Rico.
   * @return urbanization
  **/
  public String getUrbanization() {
    return urbanization;
  }

  public void setUrbanization(String urbanization) {
    this.urbanization = urbanization;
  }

  public XAVRequestAddressKeyFormat countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * A country or territory code. Required to be returned.
   * @return countryCode
  **/
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XAVRequestAddressKeyFormat xaVRequestAddressKeyFormat = (XAVRequestAddressKeyFormat) o;
    return Objects.equals(this.consigneeName, xaVRequestAddressKeyFormat.consigneeName) &&
        Objects.equals(this.attentionName, xaVRequestAddressKeyFormat.attentionName) &&
        Objects.equals(this.addressLine, xaVRequestAddressKeyFormat.addressLine) &&
        Objects.equals(this.region, xaVRequestAddressKeyFormat.region) &&
        Objects.equals(this.politicalDivision2, xaVRequestAddressKeyFormat.politicalDivision2) &&
        Objects.equals(this.politicalDivision1, xaVRequestAddressKeyFormat.politicalDivision1) &&
        Objects.equals(this.postcodePrimaryLow, xaVRequestAddressKeyFormat.postcodePrimaryLow) &&
        Objects.equals(this.postcodeExtendedLow, xaVRequestAddressKeyFormat.postcodeExtendedLow) &&
        Objects.equals(this.urbanization, xaVRequestAddressKeyFormat.urbanization) &&
        Objects.equals(this.countryCode, xaVRequestAddressKeyFormat.countryCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consigneeName, attentionName, addressLine, region, politicalDivision2, politicalDivision1, postcodePrimaryLow, postcodeExtendedLow, urbanization, countryCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XAVRequestAddressKeyFormat {\n");
    
    sb.append("    consigneeName: ").append(toIndentedString(consigneeName)).append("\n");
    sb.append("    attentionName: ").append(toIndentedString(attentionName)).append("\n");
    sb.append("    addressLine: ").append(toIndentedString(addressLine)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    politicalDivision2: ").append(toIndentedString(politicalDivision2)).append("\n");
    sb.append("    politicalDivision1: ").append(toIndentedString(politicalDivision1)).append("\n");
    sb.append("    postcodePrimaryLow: ").append(toIndentedString(postcodePrimaryLow)).append("\n");
    sb.append("    postcodeExtendedLow: ").append(toIndentedString(postcodeExtendedLow)).append("\n");
    sb.append("    urbanization: ").append(toIndentedString(urbanization)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
