/*
 * Address Validation - Street Level
 * The Address Validation Street Level API can be used to check addresses against the United States Postal Service database of valid addresses in the U.S. and Puerto Rico.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ResponseAlert;
import com.ups.wwwcie.api.client.ResponseResponseStatus;
import com.ups.wwwcie.api.client.ResponseTransactionReference;

/**
 * Response Container.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:02:35.133666300+07:00[Asia/Bangkok]")
public class XAVResponseResponse {
  @JsonProperty("ResponseStatus")
  private ResponseResponseStatus responseStatus = null;

  @JsonProperty("Alert")
  private ResponseAlert alert = null;

  @JsonProperty("TransactionReference")
  private ResponseTransactionReference transactionReference = null;

  public XAVResponseResponse responseStatus(ResponseResponseStatus responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

   /**
   * Get responseStatus
   * @return responseStatus
  **/
  public ResponseResponseStatus getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(ResponseResponseStatus responseStatus) {
    this.responseStatus = responseStatus;
  }

  public XAVResponseResponse alert(ResponseAlert alert) {
    this.alert = alert;
    return this;
  }

   /**
   * Get alert
   * @return alert
  **/
  public ResponseAlert getAlert() {
    return alert;
  }

  public void setAlert(ResponseAlert alert) {
    this.alert = alert;
  }

  public XAVResponseResponse transactionReference(ResponseTransactionReference transactionReference) {
    this.transactionReference = transactionReference;
    return this;
  }

   /**
   * Get transactionReference
   * @return transactionReference
  **/
  public ResponseTransactionReference getTransactionReference() {
    return transactionReference;
  }

  public void setTransactionReference(ResponseTransactionReference transactionReference) {
    this.transactionReference = transactionReference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XAVResponseResponse xaVResponseResponse = (XAVResponseResponse) o;
    return Objects.equals(this.responseStatus, xaVResponseResponse.responseStatus) &&
        Objects.equals(this.alert, xaVResponseResponse.alert) &&
        Objects.equals(this.transactionReference, xaVResponseResponse.transactionReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseStatus, alert, transactionReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XAVResponseResponse {\n");
    
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    alert: ").append(toIndentedString(alert)).append("\n");
    sb.append("    transactionReference: ").append(toIndentedString(transactionReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
