/*
 * Time In Transit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.Services;

import java.util.ArrayList;
import java.util.List;
/**
 * EmsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T11:05:10.812142200+07:00[Asia/Bangkok]")
public class EmsResponse {
  @JsonProperty("shipDate")
  private String shipDate = null;

  @JsonProperty("shipTime")
  private String shipTime = null;

  @JsonProperty("serviceLevel")
  private String serviceLevel = null;

  @JsonProperty("billType")
  private String billType = null;

  @JsonProperty("dutyType")
  private String dutyType = null;

  @JsonProperty("residentialIndicator")
  private String residentialIndicator = null;

  @JsonProperty("destinationCountryName")
  private String destinationCountryName = null;

  @JsonProperty("destinationCountryCode")
  private String destinationCountryCode = null;

  @JsonProperty("destinationPostalCode")
  private String destinationPostalCode = null;

  @JsonProperty("destinationPostalCodeLow")
  private String destinationPostalCodeLow = null;

  @JsonProperty("destinationPostalCodeHigh")
  private String destinationPostalCodeHigh = null;

  @JsonProperty("destinationStateProvince")
  private String destinationStateProvince = null;

  @JsonProperty("destinationCityName")
  private String destinationCityName = null;

  @JsonProperty("originCountryName")
  private String originCountryName = null;

  @JsonProperty("originCountryCode")
  private String originCountryCode = null;

  @JsonProperty("originPostalCode")
  private String originPostalCode = null;

  @JsonProperty("originPostalCodeLow")
  private String originPostalCodeLow = null;

  @JsonProperty("originPostalCodeHigh")
  private String originPostalCodeHigh = null;

  @JsonProperty("originStateProvince")
  private String originStateProvince = null;

  @JsonProperty("originCityName")
  private String originCityName = null;

  @JsonProperty("weight")
  private String weight = null;

  @JsonProperty("weightUnitOfMeasure")
  private String weightUnitOfMeasure = null;

  @JsonProperty("shipmentContentsValue")
  private String shipmentContentsValue = null;

  @JsonProperty("shipmentContentsCurrencyCode")
  private String shipmentContentsCurrencyCode = null;

  @JsonProperty("guaranteeSuspended")
  private Boolean guaranteeSuspended = null;

  @JsonProperty("numberOfServices")
  private Integer numberOfServices = null;

  @JsonProperty("services")
  private List<Services> services = null;

  public EmsResponse shipDate(String shipDate) {
    this.shipDate = shipDate;
    return this;
  }

   /**
   * The date the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up by UPS).  This date may or may not be the UPS business date.     Valid Format: YYYY-MM-DD
   * @return shipDate
  **/
  public String getShipDate() {
    return shipDate;
  }

  public void setShipDate(String shipDate) {
    this.shipDate = shipDate;
  }

  public EmsResponse shipTime(String shipTime) {
    this.shipTime = shipTime;
    return this;
  }

   /**
   * The time the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up by UPS).      Valid Format: HH:MM:SS
   * @return shipTime
  **/
  public String getShipTime() {
    return shipTime;
  }

  public void setShipTime(String shipTime) {
    this.shipTime = shipTime;
  }

  public EmsResponse serviceLevel(String serviceLevel) {
    this.serviceLevel = serviceLevel;
    return this;
  }

   /**
   * Service Levels being returned.     A &#x3D; all service levels.     Blank is the default for all Service Level values.
   * @return serviceLevel
  **/
  public String getServiceLevel() {
    return serviceLevel;
  }

  public void setServiceLevel(String serviceLevel) {
    this.serviceLevel = serviceLevel;
  }

  public EmsResponse billType(String billType) {
    this.billType = billType;
    return this;
  }

   /**
   * Represents the shipment type.     Valid values: \&quot;02\&quot;,\&quot;03\&quot;,\&quot;04\&quot;,\&quot;07\&quot;   02 - Document   03 - Non-Document   04 - WWEF   07 - Pallet
   * @return billType
  **/
  public String getBillType() {
    return billType;
  }

  public void setBillType(String billType) {
    this.billType = billType;
  }

  public EmsResponse dutyType(String dutyType) {
    this.dutyType = dutyType;
    return this;
  }

   /**
   * Populated with valid duty types for international transactions only.      Valid Duty Types: \&quot;01\&quot;,\&quot;02\&quot;,\&quot;03\&quot;,\&quot;04\&quot;,\&quot;05\&quot;,\&quot;06\&quot;,\&quot;07\&quot;,\&quot;08\&quot;,\&quot;09\&quot;   01 - Dutiable   02 - Non Dutiable   03 - Low Value   04 - Courier Remission   05 - Gift   06 - Military   07 - Exception   08 - Line Release   09 - Low Value
   * @return dutyType
  **/
  public String getDutyType() {
    return dutyType;
  }

  public void setDutyType(String dutyType) {
    this.dutyType = dutyType;
  }

  public EmsResponse residentialIndicator(String residentialIndicator) {
    this.residentialIndicator = residentialIndicator;
    return this;
  }

   /**
   * residential Indicator that was sent in on the request.     Valid values: \&quot;01\&quot;,\&quot;02\&quot;     01 - Residential   02 - Commercial
   * @return residentialIndicator
  **/
  public String getResidentialIndicator() {
    return residentialIndicator;
  }

  public void setResidentialIndicator(String residentialIndicator) {
    this.residentialIndicator = residentialIndicator;
  }

  public EmsResponse destinationCountryName(String destinationCountryName) {
    this.destinationCountryName = destinationCountryName;
    return this;
  }

   /**
   * Destination country name value
   * @return destinationCountryName
  **/
  public String getDestinationCountryName() {
    return destinationCountryName;
  }

  public void setDestinationCountryName(String destinationCountryName) {
    this.destinationCountryName = destinationCountryName;
  }

  public EmsResponse destinationCountryCode(String destinationCountryCode) {
    this.destinationCountryCode = destinationCountryCode;
    return this;
  }

   /**
   * Destination country code, conforms to ISO-defined country codes.
   * @return destinationCountryCode
  **/
  public String getDestinationCountryCode() {
    return destinationCountryCode;
  }

  public void setDestinationCountryCode(String destinationCountryCode) {
    this.destinationCountryCode = destinationCountryCode;
  }

  public EmsResponse destinationPostalCode(String destinationPostalCode) {
    this.destinationPostalCode = destinationPostalCode;
    return this;
  }

   /**
   * The shipment destination postal code.  Required for US domestic requests.     Either 5- or 9-digit US zip codes must be used for U.S. addresses.  For non-US addresses, this is recommended for all countries that utilize postal codes.
   * @return destinationPostalCode
  **/
  public String getDestinationPostalCode() {
    return destinationPostalCode;
  }

  public void setDestinationPostalCode(String destinationPostalCode) {
    this.destinationPostalCode = destinationPostalCode;
  }

  public EmsResponse destinationPostalCodeLow(String destinationPostalCodeLow) {
    this.destinationPostalCodeLow = destinationPostalCodeLow;
    return this;
  }

   /**
   * The shipment destination postal code low range.  Value may or may not differ from destinationPostalCode.      Either 5- or 9-digit US zip codes must be used for U.S. addresses.  For non-US addresses, this is recommended for all countries that utilize postal codes.
   * @return destinationPostalCodeLow
  **/
  public String getDestinationPostalCodeLow() {
    return destinationPostalCodeLow;
  }

  public void setDestinationPostalCodeLow(String destinationPostalCodeLow) {
    this.destinationPostalCodeLow = destinationPostalCodeLow;
  }

  public EmsResponse destinationPostalCodeHigh(String destinationPostalCodeHigh) {
    this.destinationPostalCodeHigh = destinationPostalCodeHigh;
    return this;
  }

   /**
   * The shipment destination postal code high range.  Value may or may not differ from destinationPostalCode.      Either 5- or 9-digit US zip codes must be used for U.S. addresses.  For non-US addresses, this is recommended for all countries that utilize postal codes.
   * @return destinationPostalCodeHigh
  **/
  public String getDestinationPostalCodeHigh() {
    return destinationPostalCodeHigh;
  }

  public void setDestinationPostalCodeHigh(String destinationPostalCodeHigh) {
    this.destinationPostalCodeHigh = destinationPostalCodeHigh;
  }

  public EmsResponse destinationStateProvince(String destinationStateProvince) {
    this.destinationStateProvince = destinationStateProvince;
    return this;
  }

   /**
   * The shipment destination state or province.     For U.S. addresses, the value will be a valid 2-Character value (per U.S. Mail Standards).     For non-U.S. addresses the full State or Province name will be returned.
   * @return destinationStateProvince
  **/
  public String getDestinationStateProvince() {
    return destinationStateProvince;
  }

  public void setDestinationStateProvince(String destinationStateProvince) {
    this.destinationStateProvince = destinationStateProvince;
  }

  public EmsResponse destinationCityName(String destinationCityName) {
    this.destinationCityName = destinationCityName;
    return this;
  }

   /**
   * The shipment destination city.     Required for International requests for thsoe countries that do not utilize postal codes.
   * @return destinationCityName
  **/
  public String getDestinationCityName() {
    return destinationCityName;
  }

  public void setDestinationCityName(String destinationCityName) {
    this.destinationCityName = destinationCityName;
  }

  public EmsResponse originCountryName(String originCountryName) {
    this.originCountryName = originCountryName;
    return this;
  }

   /**
   * Origin country name value
   * @return originCountryName
  **/
  public String getOriginCountryName() {
    return originCountryName;
  }

  public void setOriginCountryName(String originCountryName) {
    this.originCountryName = originCountryName;
  }

  public EmsResponse originCountryCode(String originCountryCode) {
    this.originCountryCode = originCountryCode;
    return this;
  }

   /**
   * Origin country code, conforms to ISO-defined country codes.
   * @return originCountryCode
  **/
  public String getOriginCountryCode() {
    return originCountryCode;
  }

  public void setOriginCountryCode(String originCountryCode) {
    this.originCountryCode = originCountryCode;
  }

  public EmsResponse originPostalCode(String originPostalCode) {
    this.originPostalCode = originPostalCode;
    return this;
  }

   /**
   * The shipment origin postal code.  Required for US domestic requests.     Either 5- or 9-digit US zip codes must be used for U.S. addresses.  For non-US addresses, this is recommended for all countries that utilize postal codes.
   * @return originPostalCode
  **/
  public String getOriginPostalCode() {
    return originPostalCode;
  }

  public void setOriginPostalCode(String originPostalCode) {
    this.originPostalCode = originPostalCode;
  }

  public EmsResponse originPostalCodeLow(String originPostalCodeLow) {
    this.originPostalCodeLow = originPostalCodeLow;
    return this;
  }

   /**
   * The shipment origin postal code low range.  Value may or may not differ from destinationPostalCode.      Either 5- or 9-digit US zip codes must be used for U.S. addresses.  For non-US addresses, this is recommended for all countries that utilize postal codes.
   * @return originPostalCodeLow
  **/
  public String getOriginPostalCodeLow() {
    return originPostalCodeLow;
  }

  public void setOriginPostalCodeLow(String originPostalCodeLow) {
    this.originPostalCodeLow = originPostalCodeLow;
  }

  public EmsResponse originPostalCodeHigh(String originPostalCodeHigh) {
    this.originPostalCodeHigh = originPostalCodeHigh;
    return this;
  }

   /**
   * The shipment origin postal code high range.  Value may or may not differ from destinationPostalCode.      Either 5- or 9-digit US zip codes must be used for U.S. addresses.  For non-US addresses, this is recommended for all countries that utilize postal codes.
   * @return originPostalCodeHigh
  **/
  public String getOriginPostalCodeHigh() {
    return originPostalCodeHigh;
  }

  public void setOriginPostalCodeHigh(String originPostalCodeHigh) {
    this.originPostalCodeHigh = originPostalCodeHigh;
  }

  public EmsResponse originStateProvince(String originStateProvince) {
    this.originStateProvince = originStateProvince;
    return this;
  }

   /**
   * The shipment origin state or province.     For U.S. addresses, the value will be a valid 2-Character value (per U.S. Mail Standards).     For non-U.S. addresses the full State or Province name will be returned.
   * @return originStateProvince
  **/
  public String getOriginStateProvince() {
    return originStateProvince;
  }

  public void setOriginStateProvince(String originStateProvince) {
    this.originStateProvince = originStateProvince;
  }

  public EmsResponse originCityName(String originCityName) {
    this.originCityName = originCityName;
    return this;
  }

   /**
   * The shipment origin city.     Required for International requests for thsoe countries that do not utilize postal codes.
   * @return originCityName
  **/
  public String getOriginCityName() {
    return originCityName;
  }

  public void setOriginCityName(String originCityName) {
    this.originCityName = originCityName;
  }

  public EmsResponse weight(String weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Shipment weight.  Value is only requried for international shipment.      Defaults to 0.0
   * @return weight
  **/
  public String getWeight() {
    return weight;
  }

  public void setWeight(String weight) {
    this.weight = weight;
  }

  public EmsResponse weightUnitOfMeasure(String weightUnitOfMeasure) {
    this.weightUnitOfMeasure = weightUnitOfMeasure;
    return this;
  }

   /**
   * Returned on response when weight was present on the request.
   * @return weightUnitOfMeasure
  **/
  public String getWeightUnitOfMeasure() {
    return weightUnitOfMeasure;
  }

  public void setWeightUnitOfMeasure(String weightUnitOfMeasure) {
    this.weightUnitOfMeasure = weightUnitOfMeasure;
  }

  public EmsResponse shipmentContentsValue(String shipmentContentsValue) {
    this.shipmentContentsValue = shipmentContentsValue;
    return this;
  }

   /**
   * Shipment contents value. Value is only required for international shipment.     Defaults to 0.0
   * @return shipmentContentsValue
  **/
  public String getShipmentContentsValue() {
    return shipmentContentsValue;
  }

  public void setShipmentContentsValue(String shipmentContentsValue) {
    this.shipmentContentsValue = shipmentContentsValue;
  }

  public EmsResponse shipmentContentsCurrencyCode(String shipmentContentsCurrencyCode) {
    this.shipmentContentsCurrencyCode = shipmentContentsCurrencyCode;
    return this;
  }

   /**
   * Returned on response when shipmentContentsValue was present on the request.
   * @return shipmentContentsCurrencyCode
  **/
  public String getShipmentContentsCurrencyCode() {
    return shipmentContentsCurrencyCode;
  }

  public void setShipmentContentsCurrencyCode(String shipmentContentsCurrencyCode) {
    this.shipmentContentsCurrencyCode = shipmentContentsCurrencyCode;
  }

  public EmsResponse guaranteeSuspended(Boolean guaranteeSuspended) {
    this.guaranteeSuspended = guaranteeSuspended;
    return this;
  }

   /**
   * Returns TRUE if the shipment dates fall within a defined peak date range. When the guarantee is suspended, it is suspended for all services in the response.      The logic for determining if guarantees are suspended applies per origin country.     The following wil be used to determine if a shipment falls within a defined peak date range: shipDate (from the response), deliveryDate (from the response), server Date.     Defined peak date range (range for when guarantees are suspended) is inclusive of start and end dates.
   * @return guaranteeSuspended
  **/
  public Boolean isGuaranteeSuspended() {
    return guaranteeSuspended;
  }

  public void setGuaranteeSuspended(Boolean guaranteeSuspended) {
    this.guaranteeSuspended = guaranteeSuspended;
  }

  public EmsResponse numberOfServices(Integer numberOfServices) {
    this.numberOfServices = numberOfServices;
    return this;
  }

   /**
   * Number of services being returned in the services array.
   * maximum: 1
   * @return numberOfServices
  **/
  public Integer getNumberOfServices() {
    return numberOfServices;
  }

  public void setNumberOfServices(Integer numberOfServices) {
    this.numberOfServices = numberOfServices;
  }

  public EmsResponse services(List<Services> services) {
    this.services = services;
    return this;
  }

  public EmsResponse addServicesItem(Services servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  public List<Services> getServices() {
    return services;
  }

  public void setServices(List<Services> services) {
    this.services = services;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmsResponse emsResponse = (EmsResponse) o;
    return Objects.equals(this.shipDate, emsResponse.shipDate) &&
        Objects.equals(this.shipTime, emsResponse.shipTime) &&
        Objects.equals(this.serviceLevel, emsResponse.serviceLevel) &&
        Objects.equals(this.billType, emsResponse.billType) &&
        Objects.equals(this.dutyType, emsResponse.dutyType) &&
        Objects.equals(this.residentialIndicator, emsResponse.residentialIndicator) &&
        Objects.equals(this.destinationCountryName, emsResponse.destinationCountryName) &&
        Objects.equals(this.destinationCountryCode, emsResponse.destinationCountryCode) &&
        Objects.equals(this.destinationPostalCode, emsResponse.destinationPostalCode) &&
        Objects.equals(this.destinationPostalCodeLow, emsResponse.destinationPostalCodeLow) &&
        Objects.equals(this.destinationPostalCodeHigh, emsResponse.destinationPostalCodeHigh) &&
        Objects.equals(this.destinationStateProvince, emsResponse.destinationStateProvince) &&
        Objects.equals(this.destinationCityName, emsResponse.destinationCityName) &&
        Objects.equals(this.originCountryName, emsResponse.originCountryName) &&
        Objects.equals(this.originCountryCode, emsResponse.originCountryCode) &&
        Objects.equals(this.originPostalCode, emsResponse.originPostalCode) &&
        Objects.equals(this.originPostalCodeLow, emsResponse.originPostalCodeLow) &&
        Objects.equals(this.originPostalCodeHigh, emsResponse.originPostalCodeHigh) &&
        Objects.equals(this.originStateProvince, emsResponse.originStateProvince) &&
        Objects.equals(this.originCityName, emsResponse.originCityName) &&
        Objects.equals(this.weight, emsResponse.weight) &&
        Objects.equals(this.weightUnitOfMeasure, emsResponse.weightUnitOfMeasure) &&
        Objects.equals(this.shipmentContentsValue, emsResponse.shipmentContentsValue) &&
        Objects.equals(this.shipmentContentsCurrencyCode, emsResponse.shipmentContentsCurrencyCode) &&
        Objects.equals(this.guaranteeSuspended, emsResponse.guaranteeSuspended) &&
        Objects.equals(this.numberOfServices, emsResponse.numberOfServices) &&
        Objects.equals(this.services, emsResponse.services);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipDate, shipTime, serviceLevel, billType, dutyType, residentialIndicator, destinationCountryName, destinationCountryCode, destinationPostalCode, destinationPostalCodeLow, destinationPostalCodeHigh, destinationStateProvince, destinationCityName, originCountryName, originCountryCode, originPostalCode, originPostalCodeLow, originPostalCodeHigh, originStateProvince, originCityName, weight, weightUnitOfMeasure, shipmentContentsValue, shipmentContentsCurrencyCode, guaranteeSuspended, numberOfServices, services);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmsResponse {\n");
    
    sb.append("    shipDate: ").append(toIndentedString(shipDate)).append("\n");
    sb.append("    shipTime: ").append(toIndentedString(shipTime)).append("\n");
    sb.append("    serviceLevel: ").append(toIndentedString(serviceLevel)).append("\n");
    sb.append("    billType: ").append(toIndentedString(billType)).append("\n");
    sb.append("    dutyType: ").append(toIndentedString(dutyType)).append("\n");
    sb.append("    residentialIndicator: ").append(toIndentedString(residentialIndicator)).append("\n");
    sb.append("    destinationCountryName: ").append(toIndentedString(destinationCountryName)).append("\n");
    sb.append("    destinationCountryCode: ").append(toIndentedString(destinationCountryCode)).append("\n");
    sb.append("    destinationPostalCode: ").append(toIndentedString(destinationPostalCode)).append("\n");
    sb.append("    destinationPostalCodeLow: ").append(toIndentedString(destinationPostalCodeLow)).append("\n");
    sb.append("    destinationPostalCodeHigh: ").append(toIndentedString(destinationPostalCodeHigh)).append("\n");
    sb.append("    destinationStateProvince: ").append(toIndentedString(destinationStateProvince)).append("\n");
    sb.append("    destinationCityName: ").append(toIndentedString(destinationCityName)).append("\n");
    sb.append("    originCountryName: ").append(toIndentedString(originCountryName)).append("\n");
    sb.append("    originCountryCode: ").append(toIndentedString(originCountryCode)).append("\n");
    sb.append("    originPostalCode: ").append(toIndentedString(originPostalCode)).append("\n");
    sb.append("    originPostalCodeLow: ").append(toIndentedString(originPostalCodeLow)).append("\n");
    sb.append("    originPostalCodeHigh: ").append(toIndentedString(originPostalCodeHigh)).append("\n");
    sb.append("    originStateProvince: ").append(toIndentedString(originStateProvince)).append("\n");
    sb.append("    originCityName: ").append(toIndentedString(originCityName)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    weightUnitOfMeasure: ").append(toIndentedString(weightUnitOfMeasure)).append("\n");
    sb.append("    shipmentContentsValue: ").append(toIndentedString(shipmentContentsValue)).append("\n");
    sb.append("    shipmentContentsCurrencyCode: ").append(toIndentedString(shipmentContentsCurrencyCode)).append("\n");
    sb.append("    guaranteeSuspended: ").append(toIndentedString(guaranteeSuspended)).append("\n");
    sb.append("    numberOfServices: ").append(toIndentedString(numberOfServices)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
