/*
 * Time In Transit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * ValidationList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T11:05:10.812142200+07:00[Asia/Bangkok]")
public class ValidationList {
  @JsonProperty("invalidFieldList")
  private List<String> invalidFieldList = null;

  @JsonProperty("invalidFieldListCodes")
  private List<String> invalidFieldListCodes = null;

  @JsonProperty("destinationAmbiguous")
  private Boolean destinationAmbiguous = null;

  @JsonProperty("originAmbiguous")
  private Boolean originAmbiguous = null;

  public ValidationList invalidFieldList(List<String> invalidFieldList) {
    this.invalidFieldList = invalidFieldList;
    return this;
  }

  public ValidationList addInvalidFieldListItem(String invalidFieldListItem) {
    if (this.invalidFieldList == null) {
      this.invalidFieldList = new ArrayList<>();
    }
    this.invalidFieldList.add(invalidFieldListItem);
    return this;
  }

   /**
   * Get invalidFieldList
   * @return invalidFieldList
  **/
  public List<String> getInvalidFieldList() {
    return invalidFieldList;
  }

  public void setInvalidFieldList(List<String> invalidFieldList) {
    this.invalidFieldList = invalidFieldList;
  }

  public ValidationList invalidFieldListCodes(List<String> invalidFieldListCodes) {
    this.invalidFieldListCodes = invalidFieldListCodes;
    return this;
  }

  public ValidationList addInvalidFieldListCodesItem(String invalidFieldListCodesItem) {
    if (this.invalidFieldListCodes == null) {
      this.invalidFieldListCodes = new ArrayList<>();
    }
    this.invalidFieldListCodes.add(invalidFieldListCodesItem);
    return this;
  }

   /**
   * Get invalidFieldListCodes
   * @return invalidFieldListCodes
  **/
  public List<String> getInvalidFieldListCodes() {
    return invalidFieldListCodes;
  }

  public void setInvalidFieldListCodes(List<String> invalidFieldListCodes) {
    this.invalidFieldListCodes = invalidFieldListCodes;
  }

  public ValidationList destinationAmbiguous(Boolean destinationAmbiguous) {
    this.destinationAmbiguous = destinationAmbiguous;
    return this;
  }

   /**
   * Returned as true when destination address has a candidate list
   * @return destinationAmbiguous
  **/
  public Boolean isDestinationAmbiguous() {
    return destinationAmbiguous;
  }

  public void setDestinationAmbiguous(Boolean destinationAmbiguous) {
    this.destinationAmbiguous = destinationAmbiguous;
  }

  public ValidationList originAmbiguous(Boolean originAmbiguous) {
    this.originAmbiguous = originAmbiguous;
    return this;
  }

   /**
   * Returned as true when origina ddress has a candidate list.
   * @return originAmbiguous
  **/
  public Boolean isOriginAmbiguous() {
    return originAmbiguous;
  }

  public void setOriginAmbiguous(Boolean originAmbiguous) {
    this.originAmbiguous = originAmbiguous;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationList validationList = (ValidationList) o;
    return Objects.equals(this.invalidFieldList, validationList.invalidFieldList) &&
        Objects.equals(this.invalidFieldListCodes, validationList.invalidFieldListCodes) &&
        Objects.equals(this.destinationAmbiguous, validationList.destinationAmbiguous) &&
        Objects.equals(this.originAmbiguous, validationList.originAmbiguous);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invalidFieldList, invalidFieldListCodes, destinationAmbiguous, originAmbiguous);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationList {\n");
    
    sb.append("    invalidFieldList: ").append(toIndentedString(invalidFieldList)).append("\n");
    sb.append("    invalidFieldListCodes: ").append(toIndentedString(invalidFieldListCodes)).append("\n");
    sb.append("    destinationAmbiguous: ").append(toIndentedString(destinationAmbiguous)).append("\n");
    sb.append("    originAmbiguous: ").append(toIndentedString(originAmbiguous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
