/*
 * Quantum View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Container tag for package dimensional weight measurement units.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:44:48.184199400+07:00[Asia/Bangkok]")
public class DimensionalWeightUnitOfMeasurement {
  @JsonProperty("Code")
  private String code = null;

  @JsonProperty("Description")
  private String description = null;

  public DimensionalWeightUnitOfMeasurement code(String code) {
    this.code = code;
    return this;
  }

   /**
   * The code representing the unit of measure associated with the shipment&#x27;s dimensional weight. Valid values: LBS - Pounds (default) KGS - Kilograms Defaults Unit of Measurement used in the shipper&#x27;s country or territory.
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public DimensionalWeightUnitOfMeasurement description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A text description of the code representing the unit of measure associated with the package weight.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DimensionalWeightUnitOfMeasurement dimensionalWeightUnitOfMeasurement = (DimensionalWeightUnitOfMeasurement) o;
    return Objects.equals(this.code, dimensionalWeightUnitOfMeasurement.code) &&
        Objects.equals(this.description, dimensionalWeightUnitOfMeasurement.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DimensionalWeightUnitOfMeasurement {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
