/*
 * Quantum View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Package-level reference number.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:44:48.184199400+07:00[Asia/Bangkok]")
public class ExceptionPackageReferenceNumber {
  @JsonProperty("BarCodeIndicator")
  private String barCodeIndicator = null;

  @JsonProperty("Number")
  private String number = null;

  @JsonProperty("Code")
  private String code = null;

  @JsonProperty("Value")
  private String value = null;

  public ExceptionPackageReferenceNumber barCodeIndicator(String barCodeIndicator) {
    this.barCodeIndicator = barCodeIndicator;
    return this;
  }

   /**
   * Not used.
   * @return barCodeIndicator
  **/
  public String getBarCodeIndicator() {
    return barCodeIndicator;
  }

  public void setBarCodeIndicator(String barCodeIndicator) {
    this.barCodeIndicator = barCodeIndicator;
  }

  public ExceptionPackageReferenceNumber number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Number tag.
   * @return number
  **/
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public ExceptionPackageReferenceNumber code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Reflects what will go on the label as the name of the reference.  For addition information, refer to the Service Codes table in the Appendix.
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ExceptionPackageReferenceNumber value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Customer supplied reference number. Reference numbers are defined by the shipper and can contain any character string.
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExceptionPackageReferenceNumber exceptionPackageReferenceNumber = (ExceptionPackageReferenceNumber) o;
    return Objects.equals(this.barCodeIndicator, exceptionPackageReferenceNumber.barCodeIndicator) &&
        Objects.equals(this.number, exceptionPackageReferenceNumber.number) &&
        Objects.equals(this.code, exceptionPackageReferenceNumber.code) &&
        Objects.equals(this.value, exceptionPackageReferenceNumber.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(barCodeIndicator, number, code, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExceptionPackageReferenceNumber {\n");
    
    sb.append("    barCodeIndicator: ").append(toIndentedString(barCodeIndicator)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
