/*
 * Quantum View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ShipperAddress;

/**
 * Shipper&#x27;s record for a shipment.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:44:48.184199400+07:00[Asia/Bangkok]")
public class ManifestShipper {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("AttentionName")
  private String attentionName = null;

  @JsonProperty("TaxIdentificationNumber")
  private String taxIdentificationNumber = null;

  @JsonProperty("PhoneNumber")
  private String phoneNumber = null;

  @JsonProperty("FaxNumber")
  private String faxNumber = null;

  @JsonProperty("ShipperNumber")
  private String shipperNumber = null;

  @JsonProperty("EMailAddress")
  private String emailAddress = null;

  @JsonProperty("Address")
  private ShipperAddress address = null;

  public ManifestShipper name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Shipper&#x27;s company name.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ManifestShipper attentionName(String attentionName) {
    this.attentionName = attentionName;
    return this;
  }

   /**
   * Shipper&#x27;s Attention Name.
   * @return attentionName
  **/
  public String getAttentionName() {
    return attentionName;
  }

  public void setAttentionName(String attentionName) {
    this.attentionName = attentionName;
  }

  public ManifestShipper taxIdentificationNumber(String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
    return this;
  }

   /**
   * Shipper&#x27;s Tax Identification Number.
   * @return taxIdentificationNumber
  **/
  public String getTaxIdentificationNumber() {
    return taxIdentificationNumber;
  }

  public void setTaxIdentificationNumber(String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
  }

  public ManifestShipper phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Shipper&#x27;s Phone Number. US Phone numbers must be 10 digits. No formatting is allowed. Required if origin and destination countries or territories are different.
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public ManifestShipper faxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

   /**
   * Shipper&#x27;s Fax Number. US Fax numbers must be 10 digits. No formatting is allowed. Required if origin and destination countries or territories are different.
   * @return faxNumber
  **/
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
  }

  public ManifestShipper shipperNumber(String shipperNumber) {
    this.shipperNumber = shipperNumber;
    return this;
  }

   /**
   * Shipper&#x27;s six digit alphanumeric account number.
   * @return shipperNumber
  **/
  public String getShipperNumber() {
    return shipperNumber;
  }

  public void setShipperNumber(String shipperNumber) {
    this.shipperNumber = shipperNumber;
  }

  public ManifestShipper emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Shipper&#x27;s designated contact eMail address.
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public ManifestShipper address(ShipperAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public ShipperAddress getAddress() {
    return address;
  }

  public void setAddress(ShipperAddress address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManifestShipper manifestShipper = (ManifestShipper) o;
    return Objects.equals(this.name, manifestShipper.name) &&
        Objects.equals(this.attentionName, manifestShipper.attentionName) &&
        Objects.equals(this.taxIdentificationNumber, manifestShipper.taxIdentificationNumber) &&
        Objects.equals(this.phoneNumber, manifestShipper.phoneNumber) &&
        Objects.equals(this.faxNumber, manifestShipper.faxNumber) &&
        Objects.equals(this.shipperNumber, manifestShipper.shipperNumber) &&
        Objects.equals(this.emailAddress, manifestShipper.emailAddress) &&
        Objects.equals(this.address, manifestShipper.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, attentionName, taxIdentificationNumber, phoneNumber, faxNumber, shipperNumber, emailAddress, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManifestShipper {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    attentionName: ").append(toIndentedString(attentionName)).append("\n");
    sb.append("    taxIdentificationNumber: ").append(toIndentedString(taxIdentificationNumber)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    shipperNumber: ").append(toIndentedString(shipperNumber)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
