/*
 * Quantum View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ShipmentServiceOptionsCallTagARS;

/**
 * Container tag for optional UPS services related to a shipment.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:44:48.184199400+07:00[Asia/Bangkok]")
public class ManifestShipmentServiceOptions {
  @JsonProperty("SaturdayPickup")
  private String saturdayPickup = null;

  @JsonProperty("SaturdayDelivery")
  private String saturdayDelivery = null;

  @JsonProperty("CallTagARS")
  private ShipmentServiceOptionsCallTagARS callTagARS = null;

  public ManifestShipmentServiceOptions saturdayPickup(String saturdayPickup) {
    this.saturdayPickup = saturdayPickup;
    return this;
  }

   /**
   * A flag indicating if the shipment requires a Saturday pickup. True if tag exists, false otherwise.
   * @return saturdayPickup
  **/
  public String getSaturdayPickup() {
    return saturdayPickup;
  }

  public void setSaturdayPickup(String saturdayPickup) {
    this.saturdayPickup = saturdayPickup;
  }

  public ManifestShipmentServiceOptions saturdayDelivery(String saturdayDelivery) {
    this.saturdayDelivery = saturdayDelivery;
    return this;
  }

   /**
   * A flag indicating if the shipment requires a Saturday Delivery. True if tag exists, false otherwise.
   * @return saturdayDelivery
  **/
  public String getSaturdayDelivery() {
    return saturdayDelivery;
  }

  public void setSaturdayDelivery(String saturdayDelivery) {
    this.saturdayDelivery = saturdayDelivery;
  }

  public ManifestShipmentServiceOptions callTagARS(ShipmentServiceOptionsCallTagARS callTagARS) {
    this.callTagARS = callTagARS;
    return this;
  }

   /**
   * Get callTagARS
   * @return callTagARS
  **/
  public ShipmentServiceOptionsCallTagARS getCallTagARS() {
    return callTagARS;
  }

  public void setCallTagARS(ShipmentServiceOptionsCallTagARS callTagARS) {
    this.callTagARS = callTagARS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManifestShipmentServiceOptions manifestShipmentServiceOptions = (ManifestShipmentServiceOptions) o;
    return Objects.equals(this.saturdayPickup, manifestShipmentServiceOptions.saturdayPickup) &&
        Objects.equals(this.saturdayDelivery, manifestShipmentServiceOptions.saturdayDelivery) &&
        Objects.equals(this.callTagARS, manifestShipmentServiceOptions.callTagARS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saturdayPickup, saturdayDelivery, callTagARS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManifestShipmentServiceOptions {\n");
    
    sb.append("    saturdayPickup: ").append(toIndentedString(saturdayPickup)).append("\n");
    sb.append("    saturdayDelivery: ").append(toIndentedString(saturdayDelivery)).append("\n");
    sb.append("    callTagARS: ").append(toIndentedString(callTagARS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
