/*
 * Quantum View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ActivityLocationAddressArtifactFormat;

/**
 * Geographic location where an activity occurred during a movement of a package or shipment. (ActivityLocation in Origin is identical to the one in Manifest. But three of all elements in Origin/ActivityLocation/AddressArtifactFormat are populated in this release. Refer to Manifest for remaining unpopulated elements.)
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:44:48.184199400+07:00[Asia/Bangkok]")
public class OriginActivityLocation {
  @JsonProperty("AddressArtifactFormat")
  private ActivityLocationAddressArtifactFormat addressArtifactFormat = null;

  public OriginActivityLocation addressArtifactFormat(ActivityLocationAddressArtifactFormat addressArtifactFormat) {
    this.addressArtifactFormat = addressArtifactFormat;
    return this;
  }

   /**
   * Get addressArtifactFormat
   * @return addressArtifactFormat
  **/
  public ActivityLocationAddressArtifactFormat getAddressArtifactFormat() {
    return addressArtifactFormat;
  }

  public void setAddressArtifactFormat(ActivityLocationAddressArtifactFormat addressArtifactFormat) {
    this.addressArtifactFormat = addressArtifactFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OriginActivityLocation originActivityLocation = (OriginActivityLocation) o;
    return Objects.equals(this.addressArtifactFormat, originActivityLocation.addressArtifactFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressArtifactFormat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OriginActivityLocation {\n");
    
    sb.append("    addressArtifactFormat: ").append(toIndentedString(addressArtifactFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
