/*
 * Quantum View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ManifestBillToAccount;
import com.ups.wwwcie.api.client.ManifestCustomsValue;
import com.ups.wwwcie.api.client.ManifestPackage;
import com.ups.wwwcie.api.client.ManifestReferenceNumber;
import com.ups.wwwcie.api.client.ManifestService;
import com.ups.wwwcie.api.client.ManifestShipTo;
import com.ups.wwwcie.api.client.ManifestShipmentServiceOptions;
import com.ups.wwwcie.api.client.ManifestShipper;
import com.ups.wwwcie.api.client.ManifestUAPAddress;

import java.util.ArrayList;
import java.util.List;
/**
 * Container represents all data that is relevant for the shipment, such as origin, destination, shipper, payment method etc. It will be return when available.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:44:48.184199400+07:00[Asia/Bangkok]")
public class SubscriptionFileManifest {
  @JsonProperty("Shipper")
  private ManifestShipper shipper = null;

  @JsonProperty("ShipTo")
  private ManifestShipTo shipTo = null;

  @JsonProperty("ReferenceNumber")
  private List<ManifestReferenceNumber> referenceNumber = null;

  @JsonProperty("Service")
  private ManifestService service = null;

  @JsonProperty("PickupDate")
  private String pickupDate = null;

  @JsonProperty("ScheduledDeliveryDate")
  private String scheduledDeliveryDate = null;

  @JsonProperty("ScheduledDeliveryTime")
  private String scheduledDeliveryTime = null;

  @JsonProperty("DocumentsOnly")
  private String documentsOnly = null;

  @JsonProperty("Package")
  private List<ManifestPackage> _package = null;

  @JsonProperty("ShipmentServiceOptions")
  private ManifestShipmentServiceOptions shipmentServiceOptions = null;

  @JsonProperty("ManufactureCountry")
  private String manufactureCountry = null;

  @JsonProperty("HarmonizedCode")
  private String harmonizedCode = null;

  @JsonProperty("CustomsValue")
  private ManifestCustomsValue customsValue = null;

  @JsonProperty("SpecialInstructions")
  private String specialInstructions = null;

  @JsonProperty("ShipmentChargeType")
  private String shipmentChargeType = null;

  @JsonProperty("BillToAccount")
  private ManifestBillToAccount billToAccount = null;

  @JsonProperty("ConsigneeBillIndicator")
  private String consigneeBillIndicator = null;

  @JsonProperty("CollectBillIndicator")
  private String collectBillIndicator = null;

  @JsonProperty("LocationAssured")
  private String locationAssured = null;

  @JsonProperty("ImportControl")
  private String importControl = null;

  @JsonProperty("LabelDeliveryMethod")
  private String labelDeliveryMethod = null;

  @JsonProperty("CommercialInvoiceRemoval")
  private String commercialInvoiceRemoval = null;

  @JsonProperty("PostalServiceTrackingID")
  private String postalServiceTrackingID = null;

  @JsonProperty("ReturnsFlexibleAccess")
  private String returnsFlexibleAccess = null;

  @JsonProperty("UPScarbonneutral")
  private String upScarbonneutral = null;

  @JsonProperty("Product")
  private String product = null;

  @JsonProperty("UPSReturnsExchange")
  private String upSReturnsExchange = null;

  @JsonProperty("LiftGateOnDelivery")
  private String liftGateOnDelivery = null;

  @JsonProperty("LiftGateOnPickUp")
  private String liftGateOnPickUp = null;

  @JsonProperty("PickupPreference")
  private String pickupPreference = null;

  @JsonProperty("DeliveryPreference")
  private String deliveryPreference = null;

  @JsonProperty("HoldForPickupAtUPSAccessPoint")
  private String holdForPickupAtUPSAccessPoint = null;

  @JsonProperty("UAPAddress")
  private ManifestUAPAddress uaPAddress = null;

  @JsonProperty("DeliverToAddresseeOnlyIndicator")
  private String deliverToAddresseeOnlyIndicator = null;

  @JsonProperty("UPSAccessPointCODIndicator")
  private String upSAccessPointCODIndicator = null;

  @JsonProperty("ClinicalTrialIndicator")
  private String clinicalTrialIndicator = null;

  @JsonProperty("ClinicalTrialIndicationNumber")
  private String clinicalTrialIndicationNumber = null;

  @JsonProperty("CategoryAHazardousIndicator")
  private String categoryAHazardousIndicator = null;

  @JsonProperty("DirectDeliveryIndicator")
  private String directDeliveryIndicator = null;

  @JsonProperty("PackageReleaseCodeIndicator")
  private String packageReleaseCodeIndicator = null;

  @JsonProperty("ProactiveResponseIndicator")
  private String proactiveResponseIndicator = null;

  @JsonProperty("WhiteGloveDeliveryIndicator")
  private String whiteGloveDeliveryIndicator = null;

  @JsonProperty("RoomOfChoiceIndicator")
  private String roomOfChoiceIndicator = null;

  @JsonProperty("InstallationDeliveryIndicator")
  private String installationDeliveryIndicator = null;

  @JsonProperty("ItemDisposalIndicator")
  private String itemDisposalIndicator = null;

  @JsonProperty("LeadShipmentTrackingNumber")
  private String leadShipmentTrackingNumber = null;

  @JsonProperty("SaturdayNonPremiumCommercialDeliveryIndicator")
  private String saturdayNonPremiumCommercialDeliveryIndicator = null;

  @JsonProperty("SundayNonPremiumCommercialDeliveryIndicator")
  private String sundayNonPremiumCommercialDeliveryIndicator = null;

  @JsonProperty("UPSPremierAccessorialIndicator")
  private String upSPremierAccessorialIndicator = null;

  @JsonProperty("UPSPremierCategoryCode")
  private String upSPremierCategoryCode = null;

  public SubscriptionFileManifest shipper(ManifestShipper shipper) {
    this.shipper = shipper;
    return this;
  }

   /**
   * Get shipper
   * @return shipper
  **/
  public ManifestShipper getShipper() {
    return shipper;
  }

  public void setShipper(ManifestShipper shipper) {
    this.shipper = shipper;
  }

  public SubscriptionFileManifest shipTo(ManifestShipTo shipTo) {
    this.shipTo = shipTo;
    return this;
  }

   /**
   * Get shipTo
   * @return shipTo
  **/
  public ManifestShipTo getShipTo() {
    return shipTo;
  }

  public void setShipTo(ManifestShipTo shipTo) {
    this.shipTo = shipTo;
  }

  public SubscriptionFileManifest referenceNumber(List<ManifestReferenceNumber> referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

  public SubscriptionFileManifest addReferenceNumberItem(ManifestReferenceNumber referenceNumberItem) {
    if (this.referenceNumber == null) {
      this.referenceNumber = new ArrayList<>();
    }
    this.referenceNumber.add(referenceNumberItem);
    return this;
  }

   /**
   * Get referenceNumber
   * @return referenceNumber
  **/
  public List<ManifestReferenceNumber> getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(List<ManifestReferenceNumber> referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public SubscriptionFileManifest service(ManifestService service) {
    this.service = service;
    return this;
  }

   /**
   * Get service
   * @return service
  **/
  public ManifestService getService() {
    return service;
  }

  public void setService(ManifestService service) {
    this.service = service;
  }

  public SubscriptionFileManifest pickupDate(String pickupDate) {
    this.pickupDate = pickupDate;
    return this;
  }

   /**
   * Should be set equal to the date on while the packages were picked up (may be prior days date if the transmission occurs after midnight). Formatted as YYYYMMDD.
   * @return pickupDate
  **/
  public String getPickupDate() {
    return pickupDate;
  }

  public void setPickupDate(String pickupDate) {
    this.pickupDate = pickupDate;
  }

  public SubscriptionFileManifest scheduledDeliveryDate(String scheduledDeliveryDate) {
    this.scheduledDeliveryDate = scheduledDeliveryDate;
    return this;
  }

   /**
   * The date the shipment originally was scheduled for delivery. Formatted as YYYYMMDD.
   * @return scheduledDeliveryDate
  **/
  public String getScheduledDeliveryDate() {
    return scheduledDeliveryDate;
  }

  public void setScheduledDeliveryDate(String scheduledDeliveryDate) {
    this.scheduledDeliveryDate = scheduledDeliveryDate;
  }

  public SubscriptionFileManifest scheduledDeliveryTime(String scheduledDeliveryTime) {
    this.scheduledDeliveryTime = scheduledDeliveryTime;
    return this;
  }

   /**
   * Schedule delivery time. Time format is HHMMSS
   * @return scheduledDeliveryTime
  **/
  public String getScheduledDeliveryTime() {
    return scheduledDeliveryTime;
  }

  public void setScheduledDeliveryTime(String scheduledDeliveryTime) {
    this.scheduledDeliveryTime = scheduledDeliveryTime;
  }

  public SubscriptionFileManifest documentsOnly(String documentsOnly) {
    this.documentsOnly = documentsOnly;
    return this;
  }

   /**
   * If the tag is present then the shipment is a document, otherwise the shipment is a non-document.  Valid values:�  1 &#x3D; Letter 2 &#x3D; Document (Non-Letter Document) 3 &#x3D; Non-Document 4 &#x3D; Pallet
   * @return documentsOnly
  **/
  public String getDocumentsOnly() {
    return documentsOnly;
  }

  public void setDocumentsOnly(String documentsOnly) {
    this.documentsOnly = documentsOnly;
  }

  public SubscriptionFileManifest _package(List<ManifestPackage> _package) {
    this._package = _package;
    return this;
  }

  public SubscriptionFileManifest addPackageItem(ManifestPackage _packageItem) {
    if (this._package == null) {
      this._package = new ArrayList<>();
    }
    this._package.add(_packageItem);
    return this;
  }

   /**
   * Get _package
   * @return _package
  **/
  public List<ManifestPackage> getPackage() {
    return _package;
  }

  public void setPackage(List<ManifestPackage> _package) {
    this._package = _package;
  }

  public SubscriptionFileManifest shipmentServiceOptions(ManifestShipmentServiceOptions shipmentServiceOptions) {
    this.shipmentServiceOptions = shipmentServiceOptions;
    return this;
  }

   /**
   * Get shipmentServiceOptions
   * @return shipmentServiceOptions
  **/
  public ManifestShipmentServiceOptions getShipmentServiceOptions() {
    return shipmentServiceOptions;
  }

  public void setShipmentServiceOptions(ManifestShipmentServiceOptions shipmentServiceOptions) {
    this.shipmentServiceOptions = shipmentServiceOptions;
  }

  public SubscriptionFileManifest manufactureCountry(String manufactureCountry) {
    this.manufactureCountry = manufactureCountry;
    return this;
  }

   /**
   * Country or Territory  of Manufacture of the contents of the package.
   * @return manufactureCountry
  **/
  public String getManufactureCountry() {
    return manufactureCountry;
  }

  public void setManufactureCountry(String manufactureCountry) {
    this.manufactureCountry = manufactureCountry;
  }

  public SubscriptionFileManifest harmonizedCode(String harmonizedCode) {
    this.harmonizedCode = harmonizedCode;
    return this;
  }

   /**
   * Harmonized code of the package.
   * @return harmonizedCode
  **/
  public String getHarmonizedCode() {
    return harmonizedCode;
  }

  public void setHarmonizedCode(String harmonizedCode) {
    this.harmonizedCode = harmonizedCode;
  }

  public SubscriptionFileManifest customsValue(ManifestCustomsValue customsValue) {
    this.customsValue = customsValue;
    return this;
  }

   /**
   * Get customsValue
   * @return customsValue
  **/
  public ManifestCustomsValue getCustomsValue() {
    return customsValue;
  }

  public void setCustomsValue(ManifestCustomsValue customsValue) {
    this.customsValue = customsValue;
  }

  public SubscriptionFileManifest specialInstructions(String specialInstructions) {
    this.specialInstructions = specialInstructions;
    return this;
  }

   /**
   * User-defined special instructions for delivery.
   * @return specialInstructions
  **/
  public String getSpecialInstructions() {
    return specialInstructions;
  }

  public void setSpecialInstructions(String specialInstructions) {
    this.specialInstructions = specialInstructions;
  }

  public SubscriptionFileManifest shipmentChargeType(String shipmentChargeType) {
    this.shipmentChargeType = shipmentChargeType;
    return this;
  }

   /**
   * Shipment charge type. Valid values: C/F - Cost and Freight C/B - Consignee Billed Package F/C - Freight Collect DDP - Delivered Duty Paid VAT Unpaid FOB - Free On Board P/P - Prepaid F/D - Free Domicile T/P - Third Party Billing
   * @return shipmentChargeType
  **/
  public String getShipmentChargeType() {
    return shipmentChargeType;
  }

  public void setShipmentChargeType(String shipmentChargeType) {
    this.shipmentChargeType = shipmentChargeType;
  }

  public SubscriptionFileManifest billToAccount(ManifestBillToAccount billToAccount) {
    this.billToAccount = billToAccount;
    return this;
  }

   /**
   * Get billToAccount
   * @return billToAccount
  **/
  public ManifestBillToAccount getBillToAccount() {
    return billToAccount;
  }

  public void setBillToAccount(ManifestBillToAccount billToAccount) {
    this.billToAccount = billToAccount;
  }

  public SubscriptionFileManifest consigneeBillIndicator(String consigneeBillIndicator) {
    this.consigneeBillIndicator = consigneeBillIndicator;
    return this;
  }

   /**
   * Indicates if consignee will be billed the shipment.
   * @return consigneeBillIndicator
  **/
  public String getConsigneeBillIndicator() {
    return consigneeBillIndicator;
  }

  public void setConsigneeBillIndicator(String consigneeBillIndicator) {
    this.consigneeBillIndicator = consigneeBillIndicator;
  }

  public SubscriptionFileManifest collectBillIndicator(String collectBillIndicator) {
    this.collectBillIndicator = collectBillIndicator;
    return this;
  }

   /**
   * Indicates whether or not to collect bill at time of delivery.
   * @return collectBillIndicator
  **/
  public String getCollectBillIndicator() {
    return collectBillIndicator;
  }

  public void setCollectBillIndicator(String collectBillIndicator) {
    this.collectBillIndicator = collectBillIndicator;
  }

  public SubscriptionFileManifest locationAssured(String locationAssured) {
    this.locationAssured = locationAssured;
    return this;
  }

   /**
   * Indicates Location Assured Values: Y - Location Assured accessorial requested
   * @return locationAssured
  **/
  public String getLocationAssured() {
    return locationAssured;
  }

  public void setLocationAssured(String locationAssured) {
    this.locationAssured = locationAssured;
  }

  public SubscriptionFileManifest importControl(String importControl) {
    this.importControl = importControl;
    return this;
  }

   /**
   * Import Control Indication is used to designate that the shipment is an Import Control shipment. If the shipment is an import control shipment then this element will have value. For no import shipment this will not be appear
   * @return importControl
  **/
  public String getImportControl() {
    return importControl;
  }

  public void setImportControl(String importControl) {
    this.importControl = importControl;
  }

  public SubscriptionFileManifest labelDeliveryMethod(String labelDeliveryMethod) {
    this.labelDeliveryMethod = labelDeliveryMethod;
    return this;
  }

   /**
   * Indicates Label Delivery Method, Values are: LDE Electronic Label .LDO One Attempt. LDP Print Label. LDT Three Attempt. LPM� Print and Mail Label.
   * @return labelDeliveryMethod
  **/
  public String getLabelDeliveryMethod() {
    return labelDeliveryMethod;
  }

  public void setLabelDeliveryMethod(String labelDeliveryMethod) {
    this.labelDeliveryMethod = labelDeliveryMethod;
  }

  public SubscriptionFileManifest commercialInvoiceRemoval(String commercialInvoiceRemoval) {
    this.commercialInvoiceRemoval = commercialInvoiceRemoval;
    return this;
  }

   /**
   * Commercial Invoice Removal (CIR) is an accessorial or indication that will allow a shipper to dictate that UPS remove the Commercial Invoice from the user&#x27;s shipment before the shipment is delivered to the ultimate consignee. If shipment is CIR then this element will have value. For no CIR this element will not be appear
   * @return commercialInvoiceRemoval
  **/
  public String getCommercialInvoiceRemoval() {
    return commercialInvoiceRemoval;
  }

  public void setCommercialInvoiceRemoval(String commercialInvoiceRemoval) {
    this.commercialInvoiceRemoval = commercialInvoiceRemoval;
  }

  public SubscriptionFileManifest postalServiceTrackingID(String postalServiceTrackingID) {
    this.postalServiceTrackingID = postalServiceTrackingID;
    return this;
  }

   /**
   * Postal Service Tracking ID transport company tracking number.
   * @return postalServiceTrackingID
  **/
  public String getPostalServiceTrackingID() {
    return postalServiceTrackingID;
  }

  public void setPostalServiceTrackingID(String postalServiceTrackingID) {
    this.postalServiceTrackingID = postalServiceTrackingID;
  }

  public SubscriptionFileManifest returnsFlexibleAccess(String returnsFlexibleAccess) {
    this.returnsFlexibleAccess = returnsFlexibleAccess;
    return this;
  }

   /**
   * (RFA) UPS returns flexible access. This element will appear with value only when returns flexible access uploaded. For no returns flexible access this element will not be appear
   * @return returnsFlexibleAccess
  **/
  public String getReturnsFlexibleAccess() {
    return returnsFlexibleAccess;
  }

  public void setReturnsFlexibleAccess(String returnsFlexibleAccess) {
    this.returnsFlexibleAccess = returnsFlexibleAccess;
  }

  public SubscriptionFileManifest upScarbonneutral(String upScarbonneutral) {
    this.upScarbonneutral = upScarbonneutral;
    return this;
  }

   /**
   * UPS carbon neutral is a term used to reflect a generic term for the tagging to be included on any document, label, e-mail, etc. used to identify that the UPS carbon neutral fee is applied. This element will appear only when shipment is UPS carbon neutral with value. For non UPS carbon neutral shipping this element appear.
   * @return upScarbonneutral
  **/
  public String getUpScarbonneutral() {
    return upScarbonneutral;
  }

  public void setUpScarbonneutral(String upScarbonneutral) {
    this.upScarbonneutral = upScarbonneutral;
  }

  public SubscriptionFileManifest product(String product) {
    this.product = product;
    return this;
  }

   /**
   * This element will have value �PAC� for CAR shipments. For no CAR shipments this element will not be appeared.
   * @return product
  **/
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public SubscriptionFileManifest upSReturnsExchange(String upSReturnsExchange) {
    this.upSReturnsExchange = upSReturnsExchange;
    return this;
  }

   /**
   * UPS Return and Exchange � This element will appear with value Y only when UPS Return and Exchange was requested. For no UPS Returns and Exchange then this element will not be appeared
   * @return upSReturnsExchange
  **/
  public String getUpSReturnsExchange() {
    return upSReturnsExchange;
  }

  public void setUpSReturnsExchange(String upSReturnsExchange) {
    this.upSReturnsExchange = upSReturnsExchange;
  }

  public SubscriptionFileManifest liftGateOnDelivery(String liftGateOnDelivery) {
    this.liftGateOnDelivery = liftGateOnDelivery;
    return this;
  }

   /**
   * Lift Gate On Delivery - This element will appear only when Lift Gate For Delivery was requested for UPS World Wide Express Freight Shipments. If no Lift Gate for Delivery was requested, this element will not appear.
   * @return liftGateOnDelivery
  **/
  public String getLiftGateOnDelivery() {
    return liftGateOnDelivery;
  }

  public void setLiftGateOnDelivery(String liftGateOnDelivery) {
    this.liftGateOnDelivery = liftGateOnDelivery;
  }

  public SubscriptionFileManifest liftGateOnPickUp(String liftGateOnPickUp) {
    this.liftGateOnPickUp = liftGateOnPickUp;
    return this;
  }

   /**
   * Lift Gate On PickUp - This element will appear only when Lift Gate For PickUp was requested for UPS World Wide Express Freight Shipments. If no Lift Gate for PickUp was requested, this element will not appear.
   * @return liftGateOnPickUp
  **/
  public String getLiftGateOnPickUp() {
    return liftGateOnPickUp;
  }

  public void setLiftGateOnPickUp(String liftGateOnPickUp) {
    this.liftGateOnPickUp = liftGateOnPickUp;
  }

  public SubscriptionFileManifest pickupPreference(String pickupPreference) {
    this.pickupPreference = pickupPreference;
    return this;
  }

   /**
   * Pickup Preference -This element will appear only when Dropoff At UPS Facility was requested for UPS World Wide Express Freight Shipments. If no Dropoff At UPS Facility was requested, this element will not appear.
   * @return pickupPreference
  **/
  public String getPickupPreference() {
    return pickupPreference;
  }

  public void setPickupPreference(String pickupPreference) {
    this.pickupPreference = pickupPreference;
  }

  public SubscriptionFileManifest deliveryPreference(String deliveryPreference) {
    this.deliveryPreference = deliveryPreference;
    return this;
  }

   /**
   * Delivery Preference - This element will appear only when Hold for pick up was requested for UPS World Wide Express Freight Shipments. If no Hold for pick up was requested, this element will not appear.
   * @return deliveryPreference
  **/
  public String getDeliveryPreference() {
    return deliveryPreference;
  }

  public void setDeliveryPreference(String deliveryPreference) {
    this.deliveryPreference = deliveryPreference;
  }

  public SubscriptionFileManifest holdForPickupAtUPSAccessPoint(String holdForPickupAtUPSAccessPoint) {
    this.holdForPickupAtUPSAccessPoint = holdForPickupAtUPSAccessPoint;
    return this;
  }

   /**
   * \&quot;Y\&quot; Indicates Shipment is Direct to Retail.
   * @return holdForPickupAtUPSAccessPoint
  **/
  public String getHoldForPickupAtUPSAccessPoint() {
    return holdForPickupAtUPSAccessPoint;
  }

  public void setHoldForPickupAtUPSAccessPoint(String holdForPickupAtUPSAccessPoint) {
    this.holdForPickupAtUPSAccessPoint = holdForPickupAtUPSAccessPoint;
  }

  public SubscriptionFileManifest uaPAddress(ManifestUAPAddress uaPAddress) {
    this.uaPAddress = uaPAddress;
    return this;
  }

   /**
   * Get uaPAddress
   * @return uaPAddress
  **/
  public ManifestUAPAddress getUaPAddress() {
    return uaPAddress;
  }

  public void setUaPAddress(ManifestUAPAddress uaPAddress) {
    this.uaPAddress = uaPAddress;
  }

  public SubscriptionFileManifest deliverToAddresseeOnlyIndicator(String deliverToAddresseeOnlyIndicator) {
    this.deliverToAddresseeOnlyIndicator = deliverToAddresseeOnlyIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot; Indicates Shipment is Deliver to Addressee.
   * @return deliverToAddresseeOnlyIndicator
  **/
  public String getDeliverToAddresseeOnlyIndicator() {
    return deliverToAddresseeOnlyIndicator;
  }

  public void setDeliverToAddresseeOnlyIndicator(String deliverToAddresseeOnlyIndicator) {
    this.deliverToAddresseeOnlyIndicator = deliverToAddresseeOnlyIndicator;
  }

  public SubscriptionFileManifest upSAccessPointCODIndicator(String upSAccessPointCODIndicator) {
    this.upSAccessPointCODIndicator = upSAccessPointCODIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot; Indicates Shipment is Cash on Delivery in Direct to Retail
   * @return upSAccessPointCODIndicator
  **/
  public String getUpSAccessPointCODIndicator() {
    return upSAccessPointCODIndicator;
  }

  public void setUpSAccessPointCODIndicator(String upSAccessPointCODIndicator) {
    this.upSAccessPointCODIndicator = upSAccessPointCODIndicator;
  }

  public SubscriptionFileManifest clinicalTrialIndicator(String clinicalTrialIndicator) {
    this.clinicalTrialIndicator = clinicalTrialIndicator;
    return this;
  }

   /**
   * An accessorial Indicator flag: Y &#x3D; Clinical Trial accessorial provided in Manifest. Spaces &#x3D; Clinical Trial accessorial not provided in Manifest.
   * @return clinicalTrialIndicator
  **/
  public String getClinicalTrialIndicator() {
    return clinicalTrialIndicator;
  }

  public void setClinicalTrialIndicator(String clinicalTrialIndicator) {
    this.clinicalTrialIndicator = clinicalTrialIndicator;
  }

  public SubscriptionFileManifest clinicalTrialIndicationNumber(String clinicalTrialIndicationNumber) {
    this.clinicalTrialIndicationNumber = clinicalTrialIndicationNumber;
    return this;
  }

   /**
   * An unique Clinical Trial associated with the shipment provided in Manifest.
   * @return clinicalTrialIndicationNumber
  **/
  public String getClinicalTrialIndicationNumber() {
    return clinicalTrialIndicationNumber;
  }

  public void setClinicalTrialIndicationNumber(String clinicalTrialIndicationNumber) {
    this.clinicalTrialIndicationNumber = clinicalTrialIndicationNumber;
  }

  public SubscriptionFileManifest categoryAHazardousIndicator(String categoryAHazardousIndicator) {
    this.categoryAHazardousIndicator = categoryAHazardousIndicator;
    return this;
  }

   /**
   * An accessorial Indicator flag: Y &#x3D; Category A Hazardous materials accessorial provided in Manifest. Spaces &#x3D; Category A Hazardous materials accessorial not provided in Manifest.
   * @return categoryAHazardousIndicator
  **/
  public String getCategoryAHazardousIndicator() {
    return categoryAHazardousIndicator;
  }

  public void setCategoryAHazardousIndicator(String categoryAHazardousIndicator) {
    this.categoryAHazardousIndicator = categoryAHazardousIndicator;
  }

  public SubscriptionFileManifest directDeliveryIndicator(String directDeliveryIndicator) {
    this.directDeliveryIndicator = directDeliveryIndicator;
    return this;
  }

   /**
   * An accessorial Indicator flag: Y &#x3D; Direct Delivery accessorisal provided in Manifest. Spaces &#x3D; Direct Delivery accessorial not provided in Manifest.
   * @return directDeliveryIndicator
  **/
  public String getDirectDeliveryIndicator() {
    return directDeliveryIndicator;
  }

  public void setDirectDeliveryIndicator(String directDeliveryIndicator) {
    this.directDeliveryIndicator = directDeliveryIndicator;
  }

  public SubscriptionFileManifest packageReleaseCodeIndicator(String packageReleaseCodeIndicator) {
    this.packageReleaseCodeIndicator = packageReleaseCodeIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot; indicates Shipment has PackageReleaseCode Accessorial.
   * @return packageReleaseCodeIndicator
  **/
  public String getPackageReleaseCodeIndicator() {
    return packageReleaseCodeIndicator;
  }

  public void setPackageReleaseCodeIndicator(String packageReleaseCodeIndicator) {
    this.packageReleaseCodeIndicator = packageReleaseCodeIndicator;
  }

  public SubscriptionFileManifest proactiveResponseIndicator(String proactiveResponseIndicator) {
    this.proactiveResponseIndicator = proactiveResponseIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot; indicates that a UPS Proactive Response Accessorial is provided.
   * @return proactiveResponseIndicator
  **/
  public String getProactiveResponseIndicator() {
    return proactiveResponseIndicator;
  }

  public void setProactiveResponseIndicator(String proactiveResponseIndicator) {
    this.proactiveResponseIndicator = proactiveResponseIndicator;
  }

  public SubscriptionFileManifest whiteGloveDeliveryIndicator(String whiteGloveDeliveryIndicator) {
    this.whiteGloveDeliveryIndicator = whiteGloveDeliveryIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot; indicates that a Heavy Goods White Glove Delivery Accessorial is provided.
   * @return whiteGloveDeliveryIndicator
  **/
  public String getWhiteGloveDeliveryIndicator() {
    return whiteGloveDeliveryIndicator;
  }

  public void setWhiteGloveDeliveryIndicator(String whiteGloveDeliveryIndicator) {
    this.whiteGloveDeliveryIndicator = whiteGloveDeliveryIndicator;
  }

  public SubscriptionFileManifest roomOfChoiceIndicator(String roomOfChoiceIndicator) {
    this.roomOfChoiceIndicator = roomOfChoiceIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot; indicates that a Heavy Goods Room of Choice Accessorial is provided.
   * @return roomOfChoiceIndicator
  **/
  public String getRoomOfChoiceIndicator() {
    return roomOfChoiceIndicator;
  }

  public void setRoomOfChoiceIndicator(String roomOfChoiceIndicator) {
    this.roomOfChoiceIndicator = roomOfChoiceIndicator;
  }

  public SubscriptionFileManifest installationDeliveryIndicator(String installationDeliveryIndicator) {
    this.installationDeliveryIndicator = installationDeliveryIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot; indicates that a Heavy Goods Installation Delivery Accessorial is provided.
   * @return installationDeliveryIndicator
  **/
  public String getInstallationDeliveryIndicator() {
    return installationDeliveryIndicator;
  }

  public void setInstallationDeliveryIndicator(String installationDeliveryIndicator) {
    this.installationDeliveryIndicator = installationDeliveryIndicator;
  }

  public SubscriptionFileManifest itemDisposalIndicator(String itemDisposalIndicator) {
    this.itemDisposalIndicator = itemDisposalIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot; indicates that a Heavy Goods Item Disposal Accessorial is provided.
   * @return itemDisposalIndicator
  **/
  public String getItemDisposalIndicator() {
    return itemDisposalIndicator;
  }

  public void setItemDisposalIndicator(String itemDisposalIndicator) {
    this.itemDisposalIndicator = itemDisposalIndicator;
  }

  public SubscriptionFileManifest leadShipmentTrackingNumber(String leadShipmentTrackingNumber) {
    this.leadShipmentTrackingNumber = leadShipmentTrackingNumber;
    return this;
  }

   /**
   * Lead Tracking Number in shipment
   * @return leadShipmentTrackingNumber
  **/
  public String getLeadShipmentTrackingNumber() {
    return leadShipmentTrackingNumber;
  }

  public void setLeadShipmentTrackingNumber(String leadShipmentTrackingNumber) {
    this.leadShipmentTrackingNumber = leadShipmentTrackingNumber;
  }

  public SubscriptionFileManifest saturdayNonPremiumCommercialDeliveryIndicator(String saturdayNonPremiumCommercialDeliveryIndicator) {
    this.saturdayNonPremiumCommercialDeliveryIndicator = saturdayNonPremiumCommercialDeliveryIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot;  indicates that a SaturdayNonPremiumCommercialDeliveryIndicator is provided.
   * @return saturdayNonPremiumCommercialDeliveryIndicator
  **/
  public String getSaturdayNonPremiumCommercialDeliveryIndicator() {
    return saturdayNonPremiumCommercialDeliveryIndicator;
  }

  public void setSaturdayNonPremiumCommercialDeliveryIndicator(String saturdayNonPremiumCommercialDeliveryIndicator) {
    this.saturdayNonPremiumCommercialDeliveryIndicator = saturdayNonPremiumCommercialDeliveryIndicator;
  }

  public SubscriptionFileManifest sundayNonPremiumCommercialDeliveryIndicator(String sundayNonPremiumCommercialDeliveryIndicator) {
    this.sundayNonPremiumCommercialDeliveryIndicator = sundayNonPremiumCommercialDeliveryIndicator;
    return this;
  }

   /**
   * \&quot;Y\&quot;  indicates that a SundayNonPremiumCommercialDeliveryIndicator is provided.
   * @return sundayNonPremiumCommercialDeliveryIndicator
  **/
  public String getSundayNonPremiumCommercialDeliveryIndicator() {
    return sundayNonPremiumCommercialDeliveryIndicator;
  }

  public void setSundayNonPremiumCommercialDeliveryIndicator(String sundayNonPremiumCommercialDeliveryIndicator) {
    this.sundayNonPremiumCommercialDeliveryIndicator = sundayNonPremiumCommercialDeliveryIndicator;
  }

  public SubscriptionFileManifest upSPremierAccessorialIndicator(String upSPremierAccessorialIndicator) {
    this.upSPremierAccessorialIndicator = upSPremierAccessorialIndicator;
    return this;
  }

   /**
   * �Y� indicates that the UPS Premier accessorial is provided.
   * @return upSPremierAccessorialIndicator
  **/
  public String getUpSPremierAccessorialIndicator() {
    return upSPremierAccessorialIndicator;
  }

  public void setUpSPremierAccessorialIndicator(String upSPremierAccessorialIndicator) {
    this.upSPremierAccessorialIndicator = upSPremierAccessorialIndicator;
  }

  public SubscriptionFileManifest upSPremierCategoryCode(String upSPremierCategoryCode) {
    this.upSPremierCategoryCode = upSPremierCategoryCode;
    return this;
  }

   /**
   * Indicates the UPS Premier category applied to the package Valid values: &#x27;PRS&#x27; � UPS Premier Silver, &#x27;PRG&#x27; � UPS Premier Gold, &#x27;PRP&#x27; - UPS Premier Platinum
   * @return upSPremierCategoryCode
  **/
  public String getUpSPremierCategoryCode() {
    return upSPremierCategoryCode;
  }

  public void setUpSPremierCategoryCode(String upSPremierCategoryCode) {
    this.upSPremierCategoryCode = upSPremierCategoryCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionFileManifest subscriptionFileManifest = (SubscriptionFileManifest) o;
    return Objects.equals(this.shipper, subscriptionFileManifest.shipper) &&
        Objects.equals(this.shipTo, subscriptionFileManifest.shipTo) &&
        Objects.equals(this.referenceNumber, subscriptionFileManifest.referenceNumber) &&
        Objects.equals(this.service, subscriptionFileManifest.service) &&
        Objects.equals(this.pickupDate, subscriptionFileManifest.pickupDate) &&
        Objects.equals(this.scheduledDeliveryDate, subscriptionFileManifest.scheduledDeliveryDate) &&
        Objects.equals(this.scheduledDeliveryTime, subscriptionFileManifest.scheduledDeliveryTime) &&
        Objects.equals(this.documentsOnly, subscriptionFileManifest.documentsOnly) &&
        Objects.equals(this._package, subscriptionFileManifest._package) &&
        Objects.equals(this.shipmentServiceOptions, subscriptionFileManifest.shipmentServiceOptions) &&
        Objects.equals(this.manufactureCountry, subscriptionFileManifest.manufactureCountry) &&
        Objects.equals(this.harmonizedCode, subscriptionFileManifest.harmonizedCode) &&
        Objects.equals(this.customsValue, subscriptionFileManifest.customsValue) &&
        Objects.equals(this.specialInstructions, subscriptionFileManifest.specialInstructions) &&
        Objects.equals(this.shipmentChargeType, subscriptionFileManifest.shipmentChargeType) &&
        Objects.equals(this.billToAccount, subscriptionFileManifest.billToAccount) &&
        Objects.equals(this.consigneeBillIndicator, subscriptionFileManifest.consigneeBillIndicator) &&
        Objects.equals(this.collectBillIndicator, subscriptionFileManifest.collectBillIndicator) &&
        Objects.equals(this.locationAssured, subscriptionFileManifest.locationAssured) &&
        Objects.equals(this.importControl, subscriptionFileManifest.importControl) &&
        Objects.equals(this.labelDeliveryMethod, subscriptionFileManifest.labelDeliveryMethod) &&
        Objects.equals(this.commercialInvoiceRemoval, subscriptionFileManifest.commercialInvoiceRemoval) &&
        Objects.equals(this.postalServiceTrackingID, subscriptionFileManifest.postalServiceTrackingID) &&
        Objects.equals(this.returnsFlexibleAccess, subscriptionFileManifest.returnsFlexibleAccess) &&
        Objects.equals(this.upScarbonneutral, subscriptionFileManifest.upScarbonneutral) &&
        Objects.equals(this.product, subscriptionFileManifest.product) &&
        Objects.equals(this.upSReturnsExchange, subscriptionFileManifest.upSReturnsExchange) &&
        Objects.equals(this.liftGateOnDelivery, subscriptionFileManifest.liftGateOnDelivery) &&
        Objects.equals(this.liftGateOnPickUp, subscriptionFileManifest.liftGateOnPickUp) &&
        Objects.equals(this.pickupPreference, subscriptionFileManifest.pickupPreference) &&
        Objects.equals(this.deliveryPreference, subscriptionFileManifest.deliveryPreference) &&
        Objects.equals(this.holdForPickupAtUPSAccessPoint, subscriptionFileManifest.holdForPickupAtUPSAccessPoint) &&
        Objects.equals(this.uaPAddress, subscriptionFileManifest.uaPAddress) &&
        Objects.equals(this.deliverToAddresseeOnlyIndicator, subscriptionFileManifest.deliverToAddresseeOnlyIndicator) &&
        Objects.equals(this.upSAccessPointCODIndicator, subscriptionFileManifest.upSAccessPointCODIndicator) &&
        Objects.equals(this.clinicalTrialIndicator, subscriptionFileManifest.clinicalTrialIndicator) &&
        Objects.equals(this.clinicalTrialIndicationNumber, subscriptionFileManifest.clinicalTrialIndicationNumber) &&
        Objects.equals(this.categoryAHazardousIndicator, subscriptionFileManifest.categoryAHazardousIndicator) &&
        Objects.equals(this.directDeliveryIndicator, subscriptionFileManifest.directDeliveryIndicator) &&
        Objects.equals(this.packageReleaseCodeIndicator, subscriptionFileManifest.packageReleaseCodeIndicator) &&
        Objects.equals(this.proactiveResponseIndicator, subscriptionFileManifest.proactiveResponseIndicator) &&
        Objects.equals(this.whiteGloveDeliveryIndicator, subscriptionFileManifest.whiteGloveDeliveryIndicator) &&
        Objects.equals(this.roomOfChoiceIndicator, subscriptionFileManifest.roomOfChoiceIndicator) &&
        Objects.equals(this.installationDeliveryIndicator, subscriptionFileManifest.installationDeliveryIndicator) &&
        Objects.equals(this.itemDisposalIndicator, subscriptionFileManifest.itemDisposalIndicator) &&
        Objects.equals(this.leadShipmentTrackingNumber, subscriptionFileManifest.leadShipmentTrackingNumber) &&
        Objects.equals(this.saturdayNonPremiumCommercialDeliveryIndicator, subscriptionFileManifest.saturdayNonPremiumCommercialDeliveryIndicator) &&
        Objects.equals(this.sundayNonPremiumCommercialDeliveryIndicator, subscriptionFileManifest.sundayNonPremiumCommercialDeliveryIndicator) &&
        Objects.equals(this.upSPremierAccessorialIndicator, subscriptionFileManifest.upSPremierAccessorialIndicator) &&
        Objects.equals(this.upSPremierCategoryCode, subscriptionFileManifest.upSPremierCategoryCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipper, shipTo, referenceNumber, service, pickupDate, scheduledDeliveryDate, scheduledDeliveryTime, documentsOnly, _package, shipmentServiceOptions, manufactureCountry, harmonizedCode, customsValue, specialInstructions, shipmentChargeType, billToAccount, consigneeBillIndicator, collectBillIndicator, locationAssured, importControl, labelDeliveryMethod, commercialInvoiceRemoval, postalServiceTrackingID, returnsFlexibleAccess, upScarbonneutral, product, upSReturnsExchange, liftGateOnDelivery, liftGateOnPickUp, pickupPreference, deliveryPreference, holdForPickupAtUPSAccessPoint, uaPAddress, deliverToAddresseeOnlyIndicator, upSAccessPointCODIndicator, clinicalTrialIndicator, clinicalTrialIndicationNumber, categoryAHazardousIndicator, directDeliveryIndicator, packageReleaseCodeIndicator, proactiveResponseIndicator, whiteGloveDeliveryIndicator, roomOfChoiceIndicator, installationDeliveryIndicator, itemDisposalIndicator, leadShipmentTrackingNumber, saturdayNonPremiumCommercialDeliveryIndicator, sundayNonPremiumCommercialDeliveryIndicator, upSPremierAccessorialIndicator, upSPremierCategoryCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionFileManifest {\n");
    
    sb.append("    shipper: ").append(toIndentedString(shipper)).append("\n");
    sb.append("    shipTo: ").append(toIndentedString(shipTo)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    pickupDate: ").append(toIndentedString(pickupDate)).append("\n");
    sb.append("    scheduledDeliveryDate: ").append(toIndentedString(scheduledDeliveryDate)).append("\n");
    sb.append("    scheduledDeliveryTime: ").append(toIndentedString(scheduledDeliveryTime)).append("\n");
    sb.append("    documentsOnly: ").append(toIndentedString(documentsOnly)).append("\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    shipmentServiceOptions: ").append(toIndentedString(shipmentServiceOptions)).append("\n");
    sb.append("    manufactureCountry: ").append(toIndentedString(manufactureCountry)).append("\n");
    sb.append("    harmonizedCode: ").append(toIndentedString(harmonizedCode)).append("\n");
    sb.append("    customsValue: ").append(toIndentedString(customsValue)).append("\n");
    sb.append("    specialInstructions: ").append(toIndentedString(specialInstructions)).append("\n");
    sb.append("    shipmentChargeType: ").append(toIndentedString(shipmentChargeType)).append("\n");
    sb.append("    billToAccount: ").append(toIndentedString(billToAccount)).append("\n");
    sb.append("    consigneeBillIndicator: ").append(toIndentedString(consigneeBillIndicator)).append("\n");
    sb.append("    collectBillIndicator: ").append(toIndentedString(collectBillIndicator)).append("\n");
    sb.append("    locationAssured: ").append(toIndentedString(locationAssured)).append("\n");
    sb.append("    importControl: ").append(toIndentedString(importControl)).append("\n");
    sb.append("    labelDeliveryMethod: ").append(toIndentedString(labelDeliveryMethod)).append("\n");
    sb.append("    commercialInvoiceRemoval: ").append(toIndentedString(commercialInvoiceRemoval)).append("\n");
    sb.append("    postalServiceTrackingID: ").append(toIndentedString(postalServiceTrackingID)).append("\n");
    sb.append("    returnsFlexibleAccess: ").append(toIndentedString(returnsFlexibleAccess)).append("\n");
    sb.append("    upScarbonneutral: ").append(toIndentedString(upScarbonneutral)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    upSReturnsExchange: ").append(toIndentedString(upSReturnsExchange)).append("\n");
    sb.append("    liftGateOnDelivery: ").append(toIndentedString(liftGateOnDelivery)).append("\n");
    sb.append("    liftGateOnPickUp: ").append(toIndentedString(liftGateOnPickUp)).append("\n");
    sb.append("    pickupPreference: ").append(toIndentedString(pickupPreference)).append("\n");
    sb.append("    deliveryPreference: ").append(toIndentedString(deliveryPreference)).append("\n");
    sb.append("    holdForPickupAtUPSAccessPoint: ").append(toIndentedString(holdForPickupAtUPSAccessPoint)).append("\n");
    sb.append("    uaPAddress: ").append(toIndentedString(uaPAddress)).append("\n");
    sb.append("    deliverToAddresseeOnlyIndicator: ").append(toIndentedString(deliverToAddresseeOnlyIndicator)).append("\n");
    sb.append("    upSAccessPointCODIndicator: ").append(toIndentedString(upSAccessPointCODIndicator)).append("\n");
    sb.append("    clinicalTrialIndicator: ").append(toIndentedString(clinicalTrialIndicator)).append("\n");
    sb.append("    clinicalTrialIndicationNumber: ").append(toIndentedString(clinicalTrialIndicationNumber)).append("\n");
    sb.append("    categoryAHazardousIndicator: ").append(toIndentedString(categoryAHazardousIndicator)).append("\n");
    sb.append("    directDeliveryIndicator: ").append(toIndentedString(directDeliveryIndicator)).append("\n");
    sb.append("    packageReleaseCodeIndicator: ").append(toIndentedString(packageReleaseCodeIndicator)).append("\n");
    sb.append("    proactiveResponseIndicator: ").append(toIndentedString(proactiveResponseIndicator)).append("\n");
    sb.append("    whiteGloveDeliveryIndicator: ").append(toIndentedString(whiteGloveDeliveryIndicator)).append("\n");
    sb.append("    roomOfChoiceIndicator: ").append(toIndentedString(roomOfChoiceIndicator)).append("\n");
    sb.append("    installationDeliveryIndicator: ").append(toIndentedString(installationDeliveryIndicator)).append("\n");
    sb.append("    itemDisposalIndicator: ").append(toIndentedString(itemDisposalIndicator)).append("\n");
    sb.append("    leadShipmentTrackingNumber: ").append(toIndentedString(leadShipmentTrackingNumber)).append("\n");
    sb.append("    saturdayNonPremiumCommercialDeliveryIndicator: ").append(toIndentedString(saturdayNonPremiumCommercialDeliveryIndicator)).append("\n");
    sb.append("    sundayNonPremiumCommercialDeliveryIndicator: ").append(toIndentedString(sundayNonPremiumCommercialDeliveryIndicator)).append("\n");
    sb.append("    upSPremierAccessorialIndicator: ").append(toIndentedString(upSPremierAccessorialIndicator)).append("\n");
    sb.append("    upSPremierCategoryCode: ").append(toIndentedString(upSPremierCategoryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
