/*
 * Paperless Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.DeleteRequestRequest;

/**
 * Paperless Document API Request container for deleting user created forms.  N/A
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T11:17:47.935512400+07:00[Asia/Bangkok]")
public class DeleteRequest {
  @JsonProperty("Request")
  private DeleteRequestRequest request = null;

  @JsonProperty("ShipperNumber")
  private String shipperNumber = null;

  @JsonProperty("DocumentID")
  private String documentID = null;

  public DeleteRequest request(DeleteRequestRequest request) {
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  public DeleteRequestRequest getRequest() {
    return request;
  }

  public void setRequest(DeleteRequestRequest request) {
    this.request = request;
  }

  public DeleteRequest shipperNumber(String shipperNumber) {
    this.shipperNumber = shipperNumber;
    return this;
  }

   /**
   * The Shipper&#x27;s UPS Account Number.  Your UPS Account Number must have &#x27;Upload Forms Created Offline&#x27; enabled to use this webservice.
   * @return shipperNumber
  **/
  public String getShipperNumber() {
    return shipperNumber;
  }

  public void setShipperNumber(String shipperNumber) {
    this.shipperNumber = shipperNumber;
  }

  public DeleteRequest documentID(String documentID) {
    this.documentID = documentID;
    return this;
  }

   /**
   * DocumentId representing uploaded document to Forms History.  Only one DocumentID will be accepted for delete request.
   * @return documentID
  **/
  public String getDocumentID() {
    return documentID;
  }

  public void setDocumentID(String documentID) {
    this.documentID = documentID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteRequest deleteRequest = (DeleteRequest) o;
    return Objects.equals(this.request, deleteRequest.request) &&
        Objects.equals(this.shipperNumber, deleteRequest.shipperNumber) &&
        Objects.equals(this.documentID, deleteRequest.documentID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, shipperNumber, documentID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteRequest {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    shipperNumber: ").append(toIndentedString(shipperNumber)).append("\n");
    sb.append("    documentID: ").append(toIndentedString(documentID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
