/*
 * Paperless Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.DeleteRequest;

/**
 * N/A  
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T11:17:47.935512400+07:00[Asia/Bangkok]")
public class PAPERLESSDOCUMENTDeleteRequestWrapper {
  @JsonProperty("DeleteRequest")
  private DeleteRequest deleteRequest = null;

  public PAPERLESSDOCUMENTDeleteRequestWrapper deleteRequest(DeleteRequest deleteRequest) {
    this.deleteRequest = deleteRequest;
    return this;
  }

   /**
   * Get deleteRequest
   * @return deleteRequest
  **/
  public DeleteRequest getDeleteRequest() {
    return deleteRequest;
  }

  public void setDeleteRequest(DeleteRequest deleteRequest) {
    this.deleteRequest = deleteRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PAPERLESSDOCUMENTDeleteRequestWrapper paPERLESSDOCUMENTDeleteRequestWrapper = (PAPERLESSDOCUMENTDeleteRequestWrapper) o;
    return Objects.equals(this.deleteRequest, paPERLESSDOCUMENTDeleteRequestWrapper.deleteRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deleteRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PAPERLESSDOCUMENTDeleteRequestWrapper {\n");
    
    sb.append("    deleteRequest: ").append(toIndentedString(deleteRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
