/*
 * Paperless Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PushToImageRepositoryResponseResponse;

/**
 * Paperless Document API response container for Push To Image Repository request.  N/A
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T11:17:47.935512400+07:00[Asia/Bangkok]")
public class PushToImageRepositoryResponse {
  @JsonProperty("Response")
  private PushToImageRepositoryResponseResponse response = null;

  @JsonProperty("FormsGroupID")
  private String formsGroupID = null;

  public PushToImageRepositoryResponse response(PushToImageRepositoryResponseResponse response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  public PushToImageRepositoryResponseResponse getResponse() {
    return response;
  }

  public void setResponse(PushToImageRepositoryResponseResponse response) {
    this.response = response;
  }

  public PushToImageRepositoryResponse formsGroupID(String formsGroupID) {
    this.formsGroupID = formsGroupID;
    return this;
  }

   /**
   * FormsGroupID is a consolidated ID representing one or multiple DocumentID(s).  N/A
   * @return formsGroupID
  **/
  public String getFormsGroupID() {
    return formsGroupID;
  }

  public void setFormsGroupID(String formsGroupID) {
    this.formsGroupID = formsGroupID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushToImageRepositoryResponse pushToImageRepositoryResponse = (PushToImageRepositoryResponse) o;
    return Objects.equals(this.response, pushToImageRepositoryResponse.response) &&
        Objects.equals(this.formsGroupID, pushToImageRepositoryResponse.formsGroupID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, formsGroupID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushToImageRepositoryResponse {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    formsGroupID: ").append(toIndentedString(formsGroupID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
