/*
 * Paperless Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.UploadRequestRequest;
import com.ups.wwwcie.api.client.UploadRequestUserCreatedForm;

import java.util.ArrayList;
import java.util.List;
/**
 * Paperless Document API Request container for uploading User Created Forms.  N/A
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T11:17:47.935512400+07:00[Asia/Bangkok]")
public class UploadRequest {
  @JsonProperty("Request")
  private UploadRequestRequest request = null;

  @JsonProperty("ShipperNumber")
  private String shipperNumber = null;

  @JsonProperty("UserCreatedForm")
  private List<UploadRequestUserCreatedForm> userCreatedForm = new ArrayList<>();

  public UploadRequest request(UploadRequestRequest request) {
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  public UploadRequestRequest getRequest() {
    return request;
  }

  public void setRequest(UploadRequestRequest request) {
    this.request = request;
  }

  public UploadRequest shipperNumber(String shipperNumber) {
    this.shipperNumber = shipperNumber;
    return this;
  }

   /**
   * The Shipper&#x27;s UPS Account Number.  Your UPS Account Number must have &#x27;Upload Forms Created Offline&#x27; enabled to use this webservice.
   * @return shipperNumber
  **/
  public String getShipperNumber() {
    return shipperNumber;
  }

  public void setShipperNumber(String shipperNumber) {
    this.shipperNumber = shipperNumber;
  }

  public UploadRequest userCreatedForm(List<UploadRequestUserCreatedForm> userCreatedForm) {
    this.userCreatedForm = userCreatedForm;
    return this;
  }

  public UploadRequest addUserCreatedFormItem(UploadRequestUserCreatedForm userCreatedFormItem) {
    this.userCreatedForm.add(userCreatedFormItem);
    return this;
  }

   /**
   * Get userCreatedForm
   * @return userCreatedForm
  **/
  public List<UploadRequestUserCreatedForm> getUserCreatedForm() {
    return userCreatedForm;
  }

  public void setUserCreatedForm(List<UploadRequestUserCreatedForm> userCreatedForm) {
    this.userCreatedForm = userCreatedForm;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadRequest uploadRequest = (UploadRequest) o;
    return Objects.equals(this.request, uploadRequest.request) &&
        Objects.equals(this.shipperNumber, uploadRequest.shipperNumber) &&
        Objects.equals(this.userCreatedForm, uploadRequest.userCreatedForm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, shipperNumber, userCreatedForm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadRequest {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    shipperNumber: ").append(toIndentedString(shipperNumber)).append("\n");
    sb.append("    userCreatedForm: ").append(toIndentedString(userCreatedForm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
