# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:

  ups-connector:
  
      # Url to UPS connector
      Url: "https://wwwcie.ups.com/api"
      
      # Your UPS Auth base URI
      authUri: "https://wwwcie.ups.com/security/v1/oauth"
  
      # Your UPS Application (client) ID
      appId: "ZItPy7z8Ep1bZBpGLVQbW3CPiMk9rGFJDpRLjgocLCJbQ5Tw"
  
      # Secret key from your applications "certificates & secrets"
      # [password]
      secretKey: "rLLiUjXI5j59kjvCWBfmXspBNCeW7Oo6x0RhOL0EyDSnADF7Vj4kHjx0JNAK3Jvi"
      
