/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.OptionCodeTransportationPickUpSchedule;

/**
 * Option code is a container that contains the information of a particular retail location type or additional service or program type that is available currently. One or more of this container will be returned to give all the available codes for Retail Type or Additional Services or Program Type.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class AvailableLocationAttributesOptionCode {
  @JsonProperty("Code")
  private String code = null;

  @JsonProperty("Description")
  private String description = null;

  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("Category")
  private String category = null;

  @JsonProperty("TransportationPickUpSchedule")
  private OptionCodeTransportationPickUpSchedule transportationPickUpSchedule = null;

  public AvailableLocationAttributesOptionCode code(String code) {
    this.code = code;
    return this;
  }

   /**
   * The valid list of codes and description for Retail Locations or Additional Services or Pro-gram Types that are currently available in the database. This can be obtained by a separate type of request (Request Option 8, 16, 24, 32, 40, 48 and 56).
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public AvailableLocationAttributesOptionCode description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description is only applicable for Program types and Additional Services. It is not provided with Location detail. It is only provided when the request is for All available additional ser-vices or all available Program types. Text will be displayed in the locale requested.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AvailableLocationAttributesOptionCode name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name will indicate the name of Location/Retail Location or Additional Services or Program Types depending on the option code. Text will be displayed in the locale requested.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AvailableLocationAttributesOptionCode category(String category) {
    this.category = category;
    return this;
  }

   /**
   * N/A
   * @return category
  **/
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public AvailableLocationAttributesOptionCode transportationPickUpSchedule(OptionCodeTransportationPickUpSchedule transportationPickUpSchedule) {
    this.transportationPickUpSchedule = transportationPickUpSchedule;
    return this;
  }

   /**
   * Get transportationPickUpSchedule
   * @return transportationPickUpSchedule
  **/
  public OptionCodeTransportationPickUpSchedule getTransportationPickUpSchedule() {
    return transportationPickUpSchedule;
  }

  public void setTransportationPickUpSchedule(OptionCodeTransportationPickUpSchedule transportationPickUpSchedule) {
    this.transportationPickUpSchedule = transportationPickUpSchedule;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailableLocationAttributesOptionCode availableLocationAttributesOptionCode = (AvailableLocationAttributesOptionCode) o;
    return Objects.equals(this.code, availableLocationAttributesOptionCode.code) &&
        Objects.equals(this.description, availableLocationAttributesOptionCode.description) &&
        Objects.equals(this.name, availableLocationAttributesOptionCode.name) &&
        Objects.equals(this.category, availableLocationAttributesOptionCode.category) &&
        Objects.equals(this.transportationPickUpSchedule, availableLocationAttributesOptionCode.transportationPickUpSchedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description, name, category, transportationPickUpSchedule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableLocationAttributesOptionCode {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    transportationPickUpSchedule: ").append(toIndentedString(transportationPickUpSchedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
