/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Contains all of the basic information about a location, Consignee Name, Building Name, Address Lines, City, State/Province, Postal Code and Country or Terriotry Code.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class DropLocationAddressKeyFormat {
  @JsonProperty("ConsigneeName")
  private String consigneeName = null;

  @JsonProperty("AddressLine")
  private String addressLine = null;

  @JsonProperty("PoliticalDivision3")
  private String politicalDivision3 = null;

  @JsonProperty("PoliticalDivision2")
  private String politicalDivision2 = null;

  @JsonProperty("PoliticalDivision1")
  private String politicalDivision1 = null;

  @JsonProperty("PostcodePrimaryLow")
  private String postcodePrimaryLow = null;

  @JsonProperty("PostcodeExtendedLow")
  private String postcodeExtendedLow = null;

  @JsonProperty("CountryCode")
  private String countryCode = null;

  public DropLocationAddressKeyFormat consigneeName(String consigneeName) {
    this.consigneeName = consigneeName;
    return this;
  }

   /**
   * Name. (Also includes the building name)Return if available.
   * @return consigneeName
  **/
  public String getConsigneeName() {
    return consigneeName;
  }

  public void setConsigneeName(String consigneeName) {
    this.consigneeName = consigneeName;
  }

  public DropLocationAddressKeyFormat addressLine(String addressLine) {
    this.addressLine = addressLine;
    return this;
  }

   /**
   * Address Line Information of the UPS location The address level or Intersection information. Only two address lines will be returned. The second line may contain such information as the building name, the suite, and room.
   * @return addressLine
  **/
  public String getAddressLine() {
    return addressLine;
  }

  public void setAddressLine(String addressLine) {
    this.addressLine = addressLine;
  }

  public DropLocationAddressKeyFormat politicalDivision3(String politicalDivision3) {
    this.politicalDivision3 = politicalDivision3;
    return this;
  }

   /**
   * Subdivision within a City.� e.g., a Barrio.
   * @return politicalDivision3
  **/
  public String getPoliticalDivision3() {
    return politicalDivision3;
  }

  public void setPoliticalDivision3(String politicalDivision3) {
    this.politicalDivision3 = politicalDivision3;
  }

  public DropLocationAddressKeyFormat politicalDivision2(String politicalDivision2) {
    this.politicalDivision2 = politicalDivision2;
    return this;
  }

   /**
   * City.
   * @return politicalDivision2
  **/
  public String getPoliticalDivision2() {
    return politicalDivision2;
  }

  public void setPoliticalDivision2(String politicalDivision2) {
    this.politicalDivision2 = politicalDivision2;
  }

  public DropLocationAddressKeyFormat politicalDivision1(String politicalDivision1) {
    this.politicalDivision1 = politicalDivision1;
    return this;
  }

   /**
   * State/Province.
   * @return politicalDivision1
  **/
  public String getPoliticalDivision1() {
    return politicalDivision1;
  }

  public void setPoliticalDivision1(String politicalDivision1) {
    this.politicalDivision1 = politicalDivision1;
  }

  public DropLocationAddressKeyFormat postcodePrimaryLow(String postcodePrimaryLow) {
    this.postcodePrimaryLow = postcodePrimaryLow;
    return this;
  }

   /**
   * Postal Code.
   * @return postcodePrimaryLow
  **/
  public String getPostcodePrimaryLow() {
    return postcodePrimaryLow;
  }

  public void setPostcodePrimaryLow(String postcodePrimaryLow) {
    this.postcodePrimaryLow = postcodePrimaryLow;
  }

  public DropLocationAddressKeyFormat postcodeExtendedLow(String postcodeExtendedLow) {
    this.postcodeExtendedLow = postcodeExtendedLow;
    return this;
  }

   /**
   * 4 Digit postal code extension. Valid for US only.
   * @return postcodeExtendedLow
  **/
  public String getPostcodeExtendedLow() {
    return postcodeExtendedLow;
  }

  public void setPostcodeExtendedLow(String postcodeExtendedLow) {
    this.postcodeExtendedLow = postcodeExtendedLow;
  }

  public DropLocationAddressKeyFormat countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * A country or territory code. Valid values to be returned are: US-United States (meaning US 50).
   * @return countryCode
  **/
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DropLocationAddressKeyFormat dropLocationAddressKeyFormat = (DropLocationAddressKeyFormat) o;
    return Objects.equals(this.consigneeName, dropLocationAddressKeyFormat.consigneeName) &&
        Objects.equals(this.addressLine, dropLocationAddressKeyFormat.addressLine) &&
        Objects.equals(this.politicalDivision3, dropLocationAddressKeyFormat.politicalDivision3) &&
        Objects.equals(this.politicalDivision2, dropLocationAddressKeyFormat.politicalDivision2) &&
        Objects.equals(this.politicalDivision1, dropLocationAddressKeyFormat.politicalDivision1) &&
        Objects.equals(this.postcodePrimaryLow, dropLocationAddressKeyFormat.postcodePrimaryLow) &&
        Objects.equals(this.postcodeExtendedLow, dropLocationAddressKeyFormat.postcodeExtendedLow) &&
        Objects.equals(this.countryCode, dropLocationAddressKeyFormat.countryCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consigneeName, addressLine, politicalDivision3, politicalDivision2, politicalDivision1, postcodePrimaryLow, postcodeExtendedLow, countryCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DropLocationAddressKeyFormat {\n");
    
    sb.append("    consigneeName: ").append(toIndentedString(consigneeName)).append("\n");
    sb.append("    addressLine: ").append(toIndentedString(addressLine)).append("\n");
    sb.append("    politicalDivision3: ").append(toIndentedString(politicalDivision3)).append("\n");
    sb.append("    politicalDivision2: ").append(toIndentedString(politicalDivision2)).append("\n");
    sb.append("    politicalDivision1: ").append(toIndentedString(politicalDivision1)).append("\n");
    sb.append("    postcodePrimaryLow: ").append(toIndentedString(postcodePrimaryLow)).append("\n");
    sb.append("    postcodeExtendedLow: ").append(toIndentedString(postcodeExtendedLow)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
