/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Location Image container.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class DropLocationLocationImage {
  @JsonProperty("SecureURL")
  private String secureURL = null;

  @JsonProperty("NonSecureURL")
  private String nonSecureURL = null;

  public DropLocationLocationImage secureURL(String secureURL) {
    this.secureURL = secureURL;
    return this;
  }

   /**
   * Secure URL for Location Image.
   * @return secureURL
  **/
  public String getSecureURL() {
    return secureURL;
  }

  public void setSecureURL(String secureURL) {
    this.secureURL = secureURL;
  }

  public DropLocationLocationImage nonSecureURL(String nonSecureURL) {
    this.nonSecureURL = nonSecureURL;
    return this;
  }

   /**
   * Non Secure URL for Location Image.
   * @return nonSecureURL
  **/
  public String getNonSecureURL() {
    return nonSecureURL;
  }

  public void setNonSecureURL(String nonSecureURL) {
    this.nonSecureURL = nonSecureURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DropLocationLocationImage dropLocationLocationImage = (DropLocationLocationImage) o;
    return Objects.equals(this.secureURL, dropLocationLocationImage.secureURL) &&
        Objects.equals(this.nonSecureURL, dropLocationLocationImage.nonSecureURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secureURL, nonSecureURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DropLocationLocationImage {\n");
    
    sb.append("    secureURL: ").append(toIndentedString(secureURL)).append("\n");
    sb.append("    nonSecureURL: ").append(toIndentedString(nonSecureURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
