/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.OperatingHoursStandardHours;

import java.util.ArrayList;
import java.util.List;
/**
 * Operating Hours.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class DropLocationOperatingHours {
  @JsonProperty("StandardHours")
  private List<OperatingHoursStandardHours> standardHours = null;

  public DropLocationOperatingHours standardHours(List<OperatingHoursStandardHours> standardHours) {
    this.standardHours = standardHours;
    return this;
  }

  public DropLocationOperatingHours addStandardHoursItem(OperatingHoursStandardHours standardHoursItem) {
    if (this.standardHours == null) {
      this.standardHours = new ArrayList<>();
    }
    this.standardHours.add(standardHoursItem);
    return this;
  }

   /**
   * Get standardHours
   * @return standardHours
  **/
  public List<OperatingHoursStandardHours> getStandardHours() {
    return standardHours;
  }

  public void setStandardHours(List<OperatingHoursStandardHours> standardHours) {
    this.standardHours = standardHours;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DropLocationOperatingHours dropLocationOperatingHours = (DropLocationOperatingHours) o;
    return Objects.equals(this.standardHours, dropLocationOperatingHours.standardHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(standardHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DropLocationOperatingHours {\n");
    
    sb.append("    standardHours: ").append(toIndentedString(standardHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
