/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Identifies the element in error.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class ErrorErrorLocation {
  @JsonProperty("ErrorLocationElementName")
  private String errorLocationElementName = null;

  @JsonProperty("ErrorLocationAttributeName")
  private String errorLocationAttributeName = null;

  public ErrorErrorLocation errorLocationElementName(String errorLocationElementName) {
    this.errorLocationElementName = errorLocationElementName;
    return this;
  }

   /**
   * The Xpath name of the element in error. This is a valid Xpath pointing to an element in the request document.
   * @return errorLocationElementName
  **/
  public String getErrorLocationElementName() {
    return errorLocationElementName;
  }

  public void setErrorLocationElementName(String errorLocationElementName) {
    this.errorLocationElementName = errorLocationElementName;
  }

  public ErrorErrorLocation errorLocationAttributeName(String errorLocationAttributeName) {
    this.errorLocationAttributeName = errorLocationAttributeName;
    return this;
  }

   /**
   * The name of the attribute in error. This is the name of the attribute contained by the Error Location element.
   * @return errorLocationAttributeName
  **/
  public String getErrorLocationAttributeName() {
    return errorLocationAttributeName;
  }

  public void setErrorLocationAttributeName(String errorLocationAttributeName) {
    this.errorLocationAttributeName = errorLocationAttributeName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorErrorLocation errorErrorLocation = (ErrorErrorLocation) o;
    return Objects.equals(this.errorLocationElementName, errorErrorLocation.errorLocationElementName) &&
        Objects.equals(this.errorLocationAttributeName, errorErrorLocation.errorLocationAttributeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorLocationElementName, errorLocationAttributeName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorErrorLocation {\n");
    
    sb.append("    errorLocationElementName: ").append(toIndentedString(errorLocationElementName)).append("\n");
    sb.append("    errorLocationAttributeName: ").append(toIndentedString(errorLocationAttributeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
