/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PostalCodeListPostalCode;

import java.util.ArrayList;
import java.util.List;
/**
 * Container to hold a list of postal codes to exclude from the access point address or geocode search.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class ExcludeFromResultPostalCodeList {
  @JsonProperty("PostalCode")
  private List<PostalCodeListPostalCode> postalCode = new ArrayList<>();

  public ExcludeFromResultPostalCodeList postalCode(List<PostalCodeListPostalCode> postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  public ExcludeFromResultPostalCodeList addPostalCodeItem(PostalCodeListPostalCode postalCodeItem) {
    this.postalCode.add(postalCodeItem);
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  public List<PostalCodeListPostalCode> getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(List<PostalCodeListPostalCode> postalCode) {
    this.postalCode = postalCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExcludeFromResultPostalCodeList excludeFromResultPostalCodeList = (ExcludeFromResultPostalCodeList) o;
    return Objects.equals(this.postalCode, excludeFromResultPostalCodeList.postalCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postalCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExcludeFromResultPostalCodeList {\n");
    
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
