/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.LocationSearchCriteriaAccessPointSearch;
import com.ups.wwwcie.api.client.LocationSearchCriteriaFreightWillCallSearch;
import com.ups.wwwcie.api.client.LocationSearchCriteriaOpenTimeCriteria;
import com.ups.wwwcie.api.client.LocationSearchCriteriaSearchOption;
import com.ups.wwwcie.api.client.LocationSearchCriteriaServiceSearch;

import java.util.ArrayList;
import java.util.List;
/**
 * The Location search criteria container allows the user to further define the basis to which they wish to receive the UPS locations.  Only relevant when the user requests a Location search (request option 1).
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class LocatorRequestLocationSearchCriteria {
  @JsonProperty("SearchOption")
  private List<LocationSearchCriteriaSearchOption> searchOption = null;

  @JsonProperty("MaximumListSize")
  private String maximumListSize = null;

  @JsonProperty("SearchRadius")
  private String searchRadius = null;

  @JsonProperty("ServiceSearch")
  private LocationSearchCriteriaServiceSearch serviceSearch = null;

  @JsonProperty("FreightWillCallSearch")
  private LocationSearchCriteriaFreightWillCallSearch freightWillCallSearch = null;

  @JsonProperty("AccessPointSearch")
  private LocationSearchCriteriaAccessPointSearch accessPointSearch = null;

  @JsonProperty("OpenTimeCriteria")
  private LocationSearchCriteriaOpenTimeCriteria openTimeCriteria = null;

  @JsonProperty("BrexitFilter")
  private String brexitFilter = null;

  public LocatorRequestLocationSearchCriteria searchOption(List<LocationSearchCriteriaSearchOption> searchOption) {
    this.searchOption = searchOption;
    return this;
  }

  public LocatorRequestLocationSearchCriteria addSearchOptionItem(LocationSearchCriteriaSearchOption searchOptionItem) {
    if (this.searchOption == null) {
      this.searchOption = new ArrayList<>();
    }
    this.searchOption.add(searchOptionItem);
    return this;
  }

   /**
   * Get searchOption
   * @return searchOption
  **/
  public List<LocationSearchCriteriaSearchOption> getSearchOption() {
    return searchOption;
  }

  public void setSearchOption(List<LocationSearchCriteriaSearchOption> searchOption) {
    this.searchOption = searchOption;
  }

  public LocatorRequestLocationSearchCriteria maximumListSize(String maximumListSize) {
    this.maximumListSize = maximumListSize;
    return this;
  }

   /**
   * If present, indicates the maximum number of locations the client wishes to receive in response; ranges from 1 to 50 with a default value of 5.
   * @return maximumListSize
  **/
  public String getMaximumListSize() {
    return maximumListSize;
  }

  public void setMaximumListSize(String maximumListSize) {
    this.maximumListSize = maximumListSize;
  }

  public LocatorRequestLocationSearchCriteria searchRadius(String searchRadius) {
    this.searchRadius = searchRadius;
    return this;
  }

   /**
   * Defines the maximum radius the user wishes to search for a UPS location. If the user does not specify, the default value is 100 miles. Whole numbers only.   Valid values are: 5-100 for UnitOfMeasure MI 5-150 for UnitOfMesaure KM
   * @return searchRadius
  **/
  public String getSearchRadius() {
    return searchRadius;
  }

  public void setSearchRadius(String searchRadius) {
    this.searchRadius = searchRadius;
  }

  public LocatorRequestLocationSearchCriteria serviceSearch(LocationSearchCriteriaServiceSearch serviceSearch) {
    this.serviceSearch = serviceSearch;
    return this;
  }

   /**
   * Get serviceSearch
   * @return serviceSearch
  **/
  public LocationSearchCriteriaServiceSearch getServiceSearch() {
    return serviceSearch;
  }

  public void setServiceSearch(LocationSearchCriteriaServiceSearch serviceSearch) {
    this.serviceSearch = serviceSearch;
  }

  public LocatorRequestLocationSearchCriteria freightWillCallSearch(LocationSearchCriteriaFreightWillCallSearch freightWillCallSearch) {
    this.freightWillCallSearch = freightWillCallSearch;
    return this;
  }

   /**
   * Get freightWillCallSearch
   * @return freightWillCallSearch
  **/
  public LocationSearchCriteriaFreightWillCallSearch getFreightWillCallSearch() {
    return freightWillCallSearch;
  }

  public void setFreightWillCallSearch(LocationSearchCriteriaFreightWillCallSearch freightWillCallSearch) {
    this.freightWillCallSearch = freightWillCallSearch;
  }

  public LocatorRequestLocationSearchCriteria accessPointSearch(LocationSearchCriteriaAccessPointSearch accessPointSearch) {
    this.accessPointSearch = accessPointSearch;
    return this;
  }

   /**
   * Get accessPointSearch
   * @return accessPointSearch
  **/
  public LocationSearchCriteriaAccessPointSearch getAccessPointSearch() {
    return accessPointSearch;
  }

  public void setAccessPointSearch(LocationSearchCriteriaAccessPointSearch accessPointSearch) {
    this.accessPointSearch = accessPointSearch;
  }

  public LocatorRequestLocationSearchCriteria openTimeCriteria(LocationSearchCriteriaOpenTimeCriteria openTimeCriteria) {
    this.openTimeCriteria = openTimeCriteria;
    return this;
  }

   /**
   * Get openTimeCriteria
   * @return openTimeCriteria
  **/
  public LocationSearchCriteriaOpenTimeCriteria getOpenTimeCriteria() {
    return openTimeCriteria;
  }

  public void setOpenTimeCriteria(LocationSearchCriteriaOpenTimeCriteria openTimeCriteria) {
    this.openTimeCriteria = openTimeCriteria;
  }

  public LocatorRequestLocationSearchCriteria brexitFilter(String brexitFilter) {
    this.brexitFilter = brexitFilter;
    return this;
  }

   /**
   * Brexit Filter. Applicable for country code GB; Pass the PostalCode for the address in the location search if Brexit functionality is desired. UAPs with postal code starts with BT returned when brexit filter starts with BT, else UAPs returned with non BT postal code. Applicable for UAP and Proximal building search.
   * @return brexitFilter
  **/
  public String getBrexitFilter() {
    return brexitFilter;
  }

  public void setBrexitFilter(String brexitFilter) {
    this.brexitFilter = brexitFilter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocatorRequestLocationSearchCriteria locatorRequestLocationSearchCriteria = (LocatorRequestLocationSearchCriteria) o;
    return Objects.equals(this.searchOption, locatorRequestLocationSearchCriteria.searchOption) &&
        Objects.equals(this.maximumListSize, locatorRequestLocationSearchCriteria.maximumListSize) &&
        Objects.equals(this.searchRadius, locatorRequestLocationSearchCriteria.searchRadius) &&
        Objects.equals(this.serviceSearch, locatorRequestLocationSearchCriteria.serviceSearch) &&
        Objects.equals(this.freightWillCallSearch, locatorRequestLocationSearchCriteria.freightWillCallSearch) &&
        Objects.equals(this.accessPointSearch, locatorRequestLocationSearchCriteria.accessPointSearch) &&
        Objects.equals(this.openTimeCriteria, locatorRequestLocationSearchCriteria.openTimeCriteria) &&
        Objects.equals(this.brexitFilter, locatorRequestLocationSearchCriteria.brexitFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchOption, maximumListSize, searchRadius, serviceSearch, freightWillCallSearch, accessPointSearch, openTimeCriteria, brexitFilter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocatorRequestLocationSearchCriteria {\n");
    
    sb.append("    searchOption: ").append(toIndentedString(searchOption)).append("\n");
    sb.append("    maximumListSize: ").append(toIndentedString(maximumListSize)).append("\n");
    sb.append("    searchRadius: ").append(toIndentedString(searchRadius)).append("\n");
    sb.append("    serviceSearch: ").append(toIndentedString(serviceSearch)).append("\n");
    sb.append("    freightWillCallSearch: ").append(toIndentedString(freightWillCallSearch)).append("\n");
    sb.append("    accessPointSearch: ").append(toIndentedString(accessPointSearch)).append("\n");
    sb.append("    openTimeCriteria: ").append(toIndentedString(openTimeCriteria)).append("\n");
    sb.append("    brexitFilter: ").append(toIndentedString(brexitFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
