/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.LocatorRequestLocationSearchCriteria;
import com.ups.wwwcie.api.client.LocatorRequestOriginAddress;
import com.ups.wwwcie.api.client.LocatorRequestRequest;
import com.ups.wwwcie.api.client.LocatorRequestServiceGeoUnit;
import com.ups.wwwcie.api.client.LocatorRequestSortCriteria;
import com.ups.wwwcie.api.client.LocatorRequestTranslate;
import com.ups.wwwcie.api.client.LocatorRequestUnitOfMeasurement;

import java.util.ArrayList;
import java.util.List;
/**
 * N/A
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class LocatorRequest {
  @JsonProperty("Request")
  private LocatorRequestRequest request = null;

  @JsonProperty("OriginAddress")
  private LocatorRequestOriginAddress originAddress = null;

  @JsonProperty("Translate")
  private LocatorRequestTranslate translate = null;

  @JsonProperty("UnitOfMeasurement")
  private LocatorRequestUnitOfMeasurement unitOfMeasurement = null;

  @JsonProperty("LocationID")
  private List<String> locationID = null;

  @JsonProperty("LocationSearchCriteria")
  private LocatorRequestLocationSearchCriteria locationSearchCriteria = null;

  @JsonProperty("SortCriteria")
  private LocatorRequestSortCriteria sortCriteria = null;

  @JsonProperty("AllowAllConfidenceLevels")
  private String allowAllConfidenceLevels = null;

  @JsonProperty("SearchOptionCode")
  private String searchOptionCode = null;

  @JsonProperty("ServiceGeoUnit")
  private LocatorRequestServiceGeoUnit serviceGeoUnit = null;

  @JsonProperty("FreightIndicator")
  private String freightIndicator = null;

  public LocatorRequest request(LocatorRequestRequest request) {
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  public LocatorRequestRequest getRequest() {
    return request;
  }

  public void setRequest(LocatorRequestRequest request) {
    this.request = request;
  }

  public LocatorRequest originAddress(LocatorRequestOriginAddress originAddress) {
    this.originAddress = originAddress;
    return this;
  }

   /**
   * Get originAddress
   * @return originAddress
  **/
  public LocatorRequestOriginAddress getOriginAddress() {
    return originAddress;
  }

  public void setOriginAddress(LocatorRequestOriginAddress originAddress) {
    this.originAddress = originAddress;
  }

  public LocatorRequest translate(LocatorRequestTranslate translate) {
    this.translate = translate;
    return this;
  }

   /**
   * Get translate
   * @return translate
  **/
  public LocatorRequestTranslate getTranslate() {
    return translate;
  }

  public void setTranslate(LocatorRequestTranslate translate) {
    this.translate = translate;
  }

  public LocatorRequest unitOfMeasurement(LocatorRequestUnitOfMeasurement unitOfMeasurement) {
    this.unitOfMeasurement = unitOfMeasurement;
    return this;
  }

   /**
   * Get unitOfMeasurement
   * @return unitOfMeasurement
  **/
  public LocatorRequestUnitOfMeasurement getUnitOfMeasurement() {
    return unitOfMeasurement;
  }

  public void setUnitOfMeasurement(LocatorRequestUnitOfMeasurement unitOfMeasurement) {
    this.unitOfMeasurement = unitOfMeasurement;
  }

  public LocatorRequest locationID(List<String> locationID) {
    this.locationID = locationID;
    return this;
  }

  public LocatorRequest addLocationIDItem(String locationIDItem) {
    if (this.locationID == null) {
      this.locationID = new ArrayList<>();
    }
    this.locationID.add(locationIDItem);
    return this;
  }

   /**
   * Location ID is the identification number of the UPS affiliated location.
   * @return locationID
  **/
  public List<String> getLocationID() {
    return locationID;
  }

  public void setLocationID(List<String> locationID) {
    this.locationID = locationID;
  }

  public LocatorRequest locationSearchCriteria(LocatorRequestLocationSearchCriteria locationSearchCriteria) {
    this.locationSearchCriteria = locationSearchCriteria;
    return this;
  }

   /**
   * Get locationSearchCriteria
   * @return locationSearchCriteria
  **/
  public LocatorRequestLocationSearchCriteria getLocationSearchCriteria() {
    return locationSearchCriteria;
  }

  public void setLocationSearchCriteria(LocatorRequestLocationSearchCriteria locationSearchCriteria) {
    this.locationSearchCriteria = locationSearchCriteria;
  }

  public LocatorRequest sortCriteria(LocatorRequestSortCriteria sortCriteria) {
    this.sortCriteria = sortCriteria;
    return this;
  }

   /**
   * Get sortCriteria
   * @return sortCriteria
  **/
  public LocatorRequestSortCriteria getSortCriteria() {
    return sortCriteria;
  }

  public void setSortCriteria(LocatorRequestSortCriteria sortCriteria) {
    this.sortCriteria = sortCriteria;
  }

  public LocatorRequest allowAllConfidenceLevels(String allowAllConfidenceLevels) {
    this.allowAllConfidenceLevels = allowAllConfidenceLevels;
    return this;
  }

   /**
   * Indicator to allow confidence level in search.
   * @return allowAllConfidenceLevels
  **/
  public String getAllowAllConfidenceLevels() {
    return allowAllConfidenceLevels;
  }

  public void setAllowAllConfidenceLevels(String allowAllConfidenceLevels) {
    this.allowAllConfidenceLevels = allowAllConfidenceLevels;
  }

  public LocatorRequest searchOptionCode(String searchOptionCode) {
    this.searchOptionCode = searchOptionCode;
    return this;
  }

   /**
   * Valid values:  01-Proximity Search Details 02-Address Search Details 03-Proximity Search Summary 04-Address Search Summary 05-Freight Will Call Search.  Either OptionType 03 or 04 is required.
   * @return searchOptionCode
  **/
  public String getSearchOptionCode() {
    return searchOptionCode;
  }

  public void setSearchOptionCode(String searchOptionCode) {
    this.searchOptionCode = searchOptionCode;
  }

  public LocatorRequest serviceGeoUnit(LocatorRequestServiceGeoUnit serviceGeoUnit) {
    this.serviceGeoUnit = serviceGeoUnit;
    return this;
  }

   /**
   * Get serviceGeoUnit
   * @return serviceGeoUnit
  **/
  public LocatorRequestServiceGeoUnit getServiceGeoUnit() {
    return serviceGeoUnit;
  }

  public void setServiceGeoUnit(LocatorRequestServiceGeoUnit serviceGeoUnit) {
    this.serviceGeoUnit = serviceGeoUnit;
  }

  public LocatorRequest freightIndicator(String freightIndicator) {
    this.freightIndicator = freightIndicator;
    return this;
  }

   /**
   * FreightIndicator. Required for Freight Location Search.
   * @return freightIndicator
  **/
  public String getFreightIndicator() {
    return freightIndicator;
  }

  public void setFreightIndicator(String freightIndicator) {
    this.freightIndicator = freightIndicator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocatorRequest locatorRequest = (LocatorRequest) o;
    return Objects.equals(this.request, locatorRequest.request) &&
        Objects.equals(this.originAddress, locatorRequest.originAddress) &&
        Objects.equals(this.translate, locatorRequest.translate) &&
        Objects.equals(this.unitOfMeasurement, locatorRequest.unitOfMeasurement) &&
        Objects.equals(this.locationID, locatorRequest.locationID) &&
        Objects.equals(this.locationSearchCriteria, locatorRequest.locationSearchCriteria) &&
        Objects.equals(this.sortCriteria, locatorRequest.sortCriteria) &&
        Objects.equals(this.allowAllConfidenceLevels, locatorRequest.allowAllConfidenceLevels) &&
        Objects.equals(this.searchOptionCode, locatorRequest.searchOptionCode) &&
        Objects.equals(this.serviceGeoUnit, locatorRequest.serviceGeoUnit) &&
        Objects.equals(this.freightIndicator, locatorRequest.freightIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, originAddress, translate, unitOfMeasurement, locationID, locationSearchCriteria, sortCriteria, allowAllConfidenceLevels, searchOptionCode, serviceGeoUnit, freightIndicator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocatorRequest {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    originAddress: ").append(toIndentedString(originAddress)).append("\n");
    sb.append("    translate: ").append(toIndentedString(translate)).append("\n");
    sb.append("    unitOfMeasurement: ").append(toIndentedString(unitOfMeasurement)).append("\n");
    sb.append("    locationID: ").append(toIndentedString(locationID)).append("\n");
    sb.append("    locationSearchCriteria: ").append(toIndentedString(locationSearchCriteria)).append("\n");
    sb.append("    sortCriteria: ").append(toIndentedString(sortCriteria)).append("\n");
    sb.append("    allowAllConfidenceLevels: ").append(toIndentedString(allowAllConfidenceLevels)).append("\n");
    sb.append("    searchOptionCode: ").append(toIndentedString(searchOptionCode)).append("\n");
    sb.append("    serviceGeoUnit: ").append(toIndentedString(serviceGeoUnit)).append("\n");
    sb.append("    freightIndicator: ").append(toIndentedString(freightIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
