/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ServiceSearchServiceCode;
import com.ups.wwwcie.api.client.ServiceSearchServiceOptionCode;

import java.util.ArrayList;
import java.util.List;
/**
 * Allows for users to further define the search criteria. Refer to the rules specified in Service Search section.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class LocationSearchCriteriaServiceSearch {
  @JsonProperty("Time")
  private String time = null;

  @JsonProperty("ServiceCode")
  private List<ServiceSearchServiceCode> serviceCode = null;

  @JsonProperty("ServiceOptionCode")
  private List<ServiceSearchServiceOptionCode> serviceOptionCode = null;

  public LocationSearchCriteriaServiceSearch time(String time) {
    this.time = time;
    return this;
  }

   /**
   * Scheduled Local Drop-off Time. Format: HHMM
   * @return time
  **/
  public String getTime() {
    return time;
  }

  public void setTime(String time) {
    this.time = time;
  }

  public LocationSearchCriteriaServiceSearch serviceCode(List<ServiceSearchServiceCode> serviceCode) {
    this.serviceCode = serviceCode;
    return this;
  }

  public LocationSearchCriteriaServiceSearch addServiceCodeItem(ServiceSearchServiceCode serviceCodeItem) {
    if (this.serviceCode == null) {
      this.serviceCode = new ArrayList<>();
    }
    this.serviceCode.add(serviceCodeItem);
    return this;
  }

   /**
   * Get serviceCode
   * @return serviceCode
  **/
  public List<ServiceSearchServiceCode> getServiceCode() {
    return serviceCode;
  }

  public void setServiceCode(List<ServiceSearchServiceCode> serviceCode) {
    this.serviceCode = serviceCode;
  }

  public LocationSearchCriteriaServiceSearch serviceOptionCode(List<ServiceSearchServiceOptionCode> serviceOptionCode) {
    this.serviceOptionCode = serviceOptionCode;
    return this;
  }

  public LocationSearchCriteriaServiceSearch addServiceOptionCodeItem(ServiceSearchServiceOptionCode serviceOptionCodeItem) {
    if (this.serviceOptionCode == null) {
      this.serviceOptionCode = new ArrayList<>();
    }
    this.serviceOptionCode.add(serviceOptionCodeItem);
    return this;
  }

   /**
   * Get serviceOptionCode
   * @return serviceOptionCode
  **/
  public List<ServiceSearchServiceOptionCode> getServiceOptionCode() {
    return serviceOptionCode;
  }

  public void setServiceOptionCode(List<ServiceSearchServiceOptionCode> serviceOptionCode) {
    this.serviceOptionCode = serviceOptionCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationSearchCriteriaServiceSearch locationSearchCriteriaServiceSearch = (LocationSearchCriteriaServiceSearch) o;
    return Objects.equals(this.time, locationSearchCriteriaServiceSearch.time) &&
        Objects.equals(this.serviceCode, locationSearchCriteriaServiceSearch.serviceCode) &&
        Objects.equals(this.serviceOptionCode, locationSearchCriteriaServiceSearch.serviceOptionCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, serviceCode, serviceOptionCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationSearchCriteriaServiceSearch {\n");
    
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    serviceCode: ").append(toIndentedString(serviceCode)).append("\n");
    sb.append("    serviceOptionCode: ").append(toIndentedString(serviceOptionCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
