/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Container to hold the private network details.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class PrivateNetworkListPrivateNetwork {
  @JsonProperty("NetworkID")
  private String networkID = null;

  @JsonProperty("NetworkDescription")
  private String networkDescription = null;

  public PrivateNetworkListPrivateNetwork networkID(String networkID) {
    this.networkID = networkID;
    return this;
  }

   /**
   * Value of networkID.
   * @return networkID
  **/
  public String getNetworkID() {
    return networkID;
  }

  public void setNetworkID(String networkID) {
    this.networkID = networkID;
  }

  public PrivateNetworkListPrivateNetwork networkDescription(String networkDescription) {
    this.networkDescription = networkDescription;
    return this;
  }

   /**
   * Description of the Network.
   * @return networkDescription
  **/
  public String getNetworkDescription() {
    return networkDescription;
  }

  public void setNetworkDescription(String networkDescription) {
    this.networkDescription = networkDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrivateNetworkListPrivateNetwork privateNetworkListPrivateNetwork = (PrivateNetworkListPrivateNetwork) o;
    return Objects.equals(this.networkID, privateNetworkListPrivateNetwork.networkID) &&
        Objects.equals(this.networkDescription, privateNetworkListPrivateNetwork.networkDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkID, networkDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrivateNetworkListPrivateNetwork {\n");
    
    sb.append("    networkID: ").append(toIndentedString(networkID)).append("\n");
    sb.append("    networkDescription: ").append(toIndentedString(networkDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
