/*
 * Locator
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.AvailableLocationAttributesOptionCode;
import com.ups.wwwcie.api.client.AvailableLocationAttributesOptionType;

/**
 * This container contains the information about the currently existing Retail Locations or Additional Services or Program types.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-03T14:58:26.891244800+07:00[Asia/Bangkok]")
public class SearchResultsAvailableLocationAttributes {
  @JsonProperty("OptionType")
  private AvailableLocationAttributesOptionType optionType = null;

  @JsonProperty("OptionCode")
  private AvailableLocationAttributesOptionCode optionCode = null;

  public SearchResultsAvailableLocationAttributes optionType(AvailableLocationAttributesOptionType optionType) {
    this.optionType = optionType;
    return this;
  }

   /**
   * Get optionType
   * @return optionType
  **/
  public AvailableLocationAttributesOptionType getOptionType() {
    return optionType;
  }

  public void setOptionType(AvailableLocationAttributesOptionType optionType) {
    this.optionType = optionType;
  }

  public SearchResultsAvailableLocationAttributes optionCode(AvailableLocationAttributesOptionCode optionCode) {
    this.optionCode = optionCode;
    return this;
  }

   /**
   * Get optionCode
   * @return optionCode
  **/
  public AvailableLocationAttributesOptionCode getOptionCode() {
    return optionCode;
  }

  public void setOptionCode(AvailableLocationAttributesOptionCode optionCode) {
    this.optionCode = optionCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResultsAvailableLocationAttributes searchResultsAvailableLocationAttributes = (SearchResultsAvailableLocationAttributes) o;
    return Objects.equals(this.optionType, searchResultsAvailableLocationAttributes.optionType) &&
        Objects.equals(this.optionCode, searchResultsAvailableLocationAttributes.optionCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optionType, optionCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResultsAvailableLocationAttributes {\n");
    
    sb.append("    optionType: ").append(toIndentedString(optionType)).append("\n");
    sb.append("    optionCode: ").append(toIndentedString(optionCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
