/*
 * Pickup
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The container of desired pickup date
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T10:01:45.611049100+07:00[Asia/Bangkok]")
public class PickupCreationRequestPickupDateInfo {
  @JsonProperty("CloseTime")
  private String closeTime = null;

  @JsonProperty("ReadyTime")
  private String readyTime = null;

  @JsonProperty("PickupDate")
  private String pickupDate = null;

  public PickupCreationRequestPickupDateInfo closeTime(String closeTime) {
    this.closeTime = closeTime;
    return this;
  }

   /**
   * Pickup location&#x27;s local close time. - User provided Close Time must be later than the Earliest Allowed Customer Close Time.  - Earliest Allowed Customer Close Time is defined by UPS pickup operation system.  - CloseTime minus ReadyTime must be greater than the LeadTime.  - LeadTime is determined by UPS pickup operation system. LeadTime is the minimum amount of time UPS requires between customer�s request for a pickup and driver arriving at the location for the pickup.  Format: HHmm Hour: 0-23 Minute: 0-59
   * @return closeTime
  **/
  public String getCloseTime() {
    return closeTime;
  }

  public void setCloseTime(String closeTime) {
    this.closeTime = closeTime;
  }

  public PickupCreationRequestPickupDateInfo readyTime(String readyTime) {
    this.readyTime = readyTime;
    return this;
  }

   /**
   * Pickup location&#x27;s local ready time.  ReadyTime means the time when your shipment(s) can be ready for UPS to pick up.  - User provided ReadyTime must be earlier than CallByTime.  - CallByTime is determined by UPS pickup operation system. CallByTime is the Latest time a Customer can call UPS or self-serve on UPS.com and complete a Pickup Request and UPS can still make the Pickup service request.  - If ReadyTime is earlier than current local time, UPS uses the current local time as the ReadyTime.  Format: HHmm Hour: 0-23 Minute: 0-59
   * @return readyTime
  **/
  public String getReadyTime() {
    return readyTime;
  }

  public void setReadyTime(String readyTime) {
    this.readyTime = readyTime;
  }

  public PickupCreationRequestPickupDateInfo pickupDate(String pickupDate) {
    this.pickupDate = pickupDate;
    return this;
  }

   /**
   * Local pickup date of the location.  Format: yyyyMMdd yyyy &#x3D; Year Appliable MM &#x3D; 01� 12 dd &#x3D; 01�31
   * @return pickupDate
  **/
  public String getPickupDate() {
    return pickupDate;
  }

  public void setPickupDate(String pickupDate) {
    this.pickupDate = pickupDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickupCreationRequestPickupDateInfo pickupCreationRequestPickupDateInfo = (PickupCreationRequestPickupDateInfo) o;
    return Objects.equals(this.closeTime, pickupCreationRequestPickupDateInfo.closeTime) &&
        Objects.equals(this.readyTime, pickupCreationRequestPickupDateInfo.readyTime) &&
        Objects.equals(this.pickupDate, pickupCreationRequestPickupDateInfo.pickupDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(closeTime, readyTime, pickupDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickupCreationRequestPickupDateInfo {\n");
    
    sb.append("    closeTime: ").append(toIndentedString(closeTime)).append("\n");
    sb.append("    readyTime: ").append(toIndentedString(readyTime)).append("\n");
    sb.append("    pickupDate: ").append(toIndentedString(pickupDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
