/*
 * Pickup
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.ResponseAlert;
import com.ups.wwwcie.api.client.ResponseResponseStatus;
import com.ups.wwwcie.api.client.ResponseTransactionReference;

/**
 * Response Container
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T10:01:45.611049100+07:00[Asia/Bangkok]")
public class PickupCancelResponseResponse {
  @JsonProperty("ResponseStatus")
  private ResponseResponseStatus responseStatus = null;

  @JsonProperty("Alert")
  private ResponseAlert alert = null;

  @JsonProperty("TransactionReference")
  private ResponseTransactionReference transactionReference = null;

  public PickupCancelResponseResponse responseStatus(ResponseResponseStatus responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

   /**
   * Get responseStatus
   * @return responseStatus
  **/
  public ResponseResponseStatus getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(ResponseResponseStatus responseStatus) {
    this.responseStatus = responseStatus;
  }

  public PickupCancelResponseResponse alert(ResponseAlert alert) {
    this.alert = alert;
    return this;
  }

   /**
   * Get alert
   * @return alert
  **/
  public ResponseAlert getAlert() {
    return alert;
  }

  public void setAlert(ResponseAlert alert) {
    this.alert = alert;
  }

  public PickupCancelResponseResponse transactionReference(ResponseTransactionReference transactionReference) {
    this.transactionReference = transactionReference;
    return this;
  }

   /**
   * Get transactionReference
   * @return transactionReference
  **/
  public ResponseTransactionReference getTransactionReference() {
    return transactionReference;
  }

  public void setTransactionReference(ResponseTransactionReference transactionReference) {
    this.transactionReference = transactionReference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickupCancelResponseResponse pickupCancelResponseResponse = (PickupCancelResponseResponse) o;
    return Objects.equals(this.responseStatus, pickupCancelResponseResponse.responseStatus) &&
        Objects.equals(this.alert, pickupCancelResponseResponse.alert) &&
        Objects.equals(this.transactionReference, pickupCancelResponseResponse.transactionReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseStatus, alert, transactionReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickupCancelResponseResponse {\n");
    
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    alert: ").append(toIndentedString(alert)).append("\n");
    sb.append("    transactionReference: ").append(toIndentedString(transactionReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
