/*
 * Pickup
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PickupRateResponseRateResult;
import com.ups.wwwcie.api.client.PickupRateResponseResponse;
import com.ups.wwwcie.api.client.PickupRateResponseWeekendServiceTerritory;

/**
 * The response of rating on-callpickup.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T10:01:45.611049100+07:00[Asia/Bangkok]")
public class PickupRateResponse {
  @JsonProperty("Response")
  private PickupRateResponseResponse response = null;

  @JsonProperty("RateResult")
  private PickupRateResponseRateResult rateResult = null;

  @JsonProperty("WeekendServiceTerritoryIndicator")
  private String weekendServiceTerritoryIndicator = null;

  @JsonProperty("WeekendServiceTerritory")
  private PickupRateResponseWeekendServiceTerritory weekendServiceTerritory = null;

  public PickupRateResponse response(PickupRateResponseResponse response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  public PickupRateResponseResponse getResponse() {
    return response;
  }

  public void setResponse(PickupRateResponseResponse response) {
    this.response = response;
  }

  public PickupRateResponse rateResult(PickupRateResponseRateResult rateResult) {
    this.rateResult = rateResult;
    return this;
  }

   /**
   * Get rateResult
   * @return rateResult
  **/
  public PickupRateResponseRateResult getRateResult() {
    return rateResult;
  }

  public void setRateResult(PickupRateResponseRateResult rateResult) {
    this.rateResult = rateResult;
  }

  public PickupRateResponse weekendServiceTerritoryIndicator(String weekendServiceTerritoryIndicator) {
    this.weekendServiceTerritoryIndicator = weekendServiceTerritoryIndicator;
    return this;
  }

   /**
   * Indicates if the pickup address qualifies for WST (Weekend Service Territory). Returned if the pickup date is Saturday and subversion greater or equal to 1607.                                                                                                                                                                                                                          Valid Values:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Y &#x3D; WST N &#x3D; Non-WST
   * @return weekendServiceTerritoryIndicator
  **/
  public String getWeekendServiceTerritoryIndicator() {
    return weekendServiceTerritoryIndicator;
  }

  public void setWeekendServiceTerritoryIndicator(String weekendServiceTerritoryIndicator) {
    this.weekendServiceTerritoryIndicator = weekendServiceTerritoryIndicator;
  }

  public PickupRateResponse weekendServiceTerritory(PickupRateResponseWeekendServiceTerritory weekendServiceTerritory) {
    this.weekendServiceTerritory = weekendServiceTerritory;
    return this;
  }

   /**
   * Get weekendServiceTerritory
   * @return weekendServiceTerritory
  **/
  public PickupRateResponseWeekendServiceTerritory getWeekendServiceTerritory() {
    return weekendServiceTerritory;
  }

  public void setWeekendServiceTerritory(PickupRateResponseWeekendServiceTerritory weekendServiceTerritory) {
    this.weekendServiceTerritory = weekendServiceTerritory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickupRateResponse pickupRateResponse = (PickupRateResponse) o;
    return Objects.equals(this.response, pickupRateResponse.response) &&
        Objects.equals(this.rateResult, pickupRateResponse.rateResult) &&
        Objects.equals(this.weekendServiceTerritoryIndicator, pickupRateResponse.weekendServiceTerritoryIndicator) &&
        Objects.equals(this.weekendServiceTerritory, pickupRateResponse.weekendServiceTerritory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, rateResult, weekendServiceTerritoryIndicator, weekendServiceTerritory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickupRateResponse {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    rateResult: ").append(toIndentedString(rateResult)).append("\n");
    sb.append("    weekendServiceTerritoryIndicator: ").append(toIndentedString(weekendServiceTerritoryIndicator)).append("\n");
    sb.append("    weekendServiceTerritory: ").append(toIndentedString(weekendServiceTerritory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
