/*
 * Pickup
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.RateResultDisclaimer;

/**
 * The result of rating on-callpickup. It correlates to rate status code 01
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T10:01:45.611049100+07:00[Asia/Bangkok]")
public class PickupCreationResponseRateResult {
  @JsonProperty("Disclaimer")
  private RateResultDisclaimer disclaimer = null;

  @JsonProperty("RateType")
  private String rateType = null;

  @JsonProperty("CurrencyCode")
  private String currencyCode = null;

  @JsonProperty("ChargeDetail")
  private OneOfPickupCreationResponseRateResultChargeDetail chargeDetail = null;

  @JsonProperty("TaxCharges")
  private OneOfPickupCreationResponseRateResultTaxCharges taxCharges = null;

  @JsonProperty("TotalTax")
  private String totalTax = null;

  @JsonProperty("GrandTotalOfAllCharge")
  private String grandTotalOfAllCharge = null;

  @JsonProperty("GrandTotalOfAllIncentedCharge")
  private String grandTotalOfAllIncentedCharge = null;

  @JsonProperty("PreTaxTotalCharge")
  private String preTaxTotalCharge = null;

  @JsonProperty("PreTaxTotalIncentedCharge")
  private String preTaxTotalIncentedCharge = null;

  public PickupCreationResponseRateResult disclaimer(RateResultDisclaimer disclaimer) {
    this.disclaimer = disclaimer;
    return this;
  }

   /**
   * Get disclaimer
   * @return disclaimer
  **/
  public RateResultDisclaimer getDisclaimer() {
    return disclaimer;
  }

  public void setDisclaimer(RateResultDisclaimer disclaimer) {
    this.disclaimer = disclaimer;
  }

  public PickupCreationResponseRateResult rateType(String rateType) {
    this.rateType = rateType;
    return this;
  }

   /**
   * Indicates this pickup is rated as same-day or future-day pickup. SD &#x3D; Same-day Pickup FD &#x3D; Future-day Pickup
   * @return rateType
  **/
  public String getRateType() {
    return rateType;
  }

  public void setRateType(String rateType) {
    this.rateType = rateType;
  }

  public PickupCreationResponseRateResult currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * IATA currency codes for the pickup charge. Such as USD
   * @return currencyCode
  **/
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public PickupCreationResponseRateResult chargeDetail(OneOfPickupCreationResponseRateResultChargeDetail chargeDetail) {
    this.chargeDetail = chargeDetail;
    return this;
  }

   /**
   * Get chargeDetail
   * @return chargeDetail
  **/
  public OneOfPickupCreationResponseRateResultChargeDetail getChargeDetail() {
    return chargeDetail;
  }

  public void setChargeDetail(OneOfPickupCreationResponseRateResultChargeDetail chargeDetail) {
    this.chargeDetail = chargeDetail;
  }

  public PickupCreationResponseRateResult taxCharges(OneOfPickupCreationResponseRateResultTaxCharges taxCharges) {
    this.taxCharges = taxCharges;
    return this;
  }

   /**
   * Get taxCharges
   * @return taxCharges
  **/
  public OneOfPickupCreationResponseRateResultTaxCharges getTaxCharges() {
    return taxCharges;
  }

  public void setTaxCharges(OneOfPickupCreationResponseRateResultTaxCharges taxCharges) {
    this.taxCharges = taxCharges;
  }

  public PickupCreationResponseRateResult totalTax(String totalTax) {
    this.totalTax = totalTax;
    return this;
  }

   /**
   * The sum of all taxes.
   * @return totalTax
  **/
  public String getTotalTax() {
    return totalTax;
  }

  public void setTotalTax(String totalTax) {
    this.totalTax = totalTax;
  }

  public PickupCreationResponseRateResult grandTotalOfAllCharge(String grandTotalOfAllCharge) {
    this.grandTotalOfAllCharge = grandTotalOfAllCharge;
    return this;
  }

   /**
   * The grand total of each charge and applied tax.
   * @return grandTotalOfAllCharge
  **/
  public String getGrandTotalOfAllCharge() {
    return grandTotalOfAllCharge;
  }

  public void setGrandTotalOfAllCharge(String grandTotalOfAllCharge) {
    this.grandTotalOfAllCharge = grandTotalOfAllCharge;
  }

  public PickupCreationResponseRateResult grandTotalOfAllIncentedCharge(String grandTotalOfAllIncentedCharge) {
    this.grandTotalOfAllIncentedCharge = grandTotalOfAllIncentedCharge;
    return this;
  }

   /**
   * The grand total of each incented charge and applied tax. Only present if 1. UserLevelDiscountIndicator &#x3D; Y and User Level Promotion is applied to the pickup or 2 .if any incentive rate is applied to the pickup and SubVersion on the request is greater than or equal to 1707.
   * @return grandTotalOfAllIncentedCharge
  **/
  public String getGrandTotalOfAllIncentedCharge() {
    return grandTotalOfAllIncentedCharge;
  }

  public void setGrandTotalOfAllIncentedCharge(String grandTotalOfAllIncentedCharge) {
    this.grandTotalOfAllIncentedCharge = grandTotalOfAllIncentedCharge;
  }

  public PickupCreationResponseRateResult preTaxTotalCharge(String preTaxTotalCharge) {
    this.preTaxTotalCharge = preTaxTotalCharge;
    return this;
  }

   /**
   * Total of charges before taxes. Only present when tax details requested in input.
   * @return preTaxTotalCharge
  **/
  public String getPreTaxTotalCharge() {
    return preTaxTotalCharge;
  }

  public void setPreTaxTotalCharge(String preTaxTotalCharge) {
    this.preTaxTotalCharge = preTaxTotalCharge;
  }

  public PickupCreationResponseRateResult preTaxTotalIncentedCharge(String preTaxTotalIncentedCharge) {
    this.preTaxTotalIncentedCharge = preTaxTotalIncentedCharge;
    return this;
  }

   /**
   * Total of incented charges before taxes. Only present if 1. UserLevelDiscountIndicator &#x3D; Y and User Level Promotion is applied to the pickup or 2 .if any incentive rate is applied to the pickup and SubVersion on the request is greater than or equal to 1707.
   * @return preTaxTotalIncentedCharge
  **/
  public String getPreTaxTotalIncentedCharge() {
    return preTaxTotalIncentedCharge;
  }

  public void setPreTaxTotalIncentedCharge(String preTaxTotalIncentedCharge) {
    this.preTaxTotalIncentedCharge = preTaxTotalIncentedCharge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickupCreationResponseRateResult pickupCreationResponseRateResult = (PickupCreationResponseRateResult) o;
    return Objects.equals(this.disclaimer, pickupCreationResponseRateResult.disclaimer) &&
        Objects.equals(this.rateType, pickupCreationResponseRateResult.rateType) &&
        Objects.equals(this.currencyCode, pickupCreationResponseRateResult.currencyCode) &&
        Objects.equals(this.chargeDetail, pickupCreationResponseRateResult.chargeDetail) &&
        Objects.equals(this.taxCharges, pickupCreationResponseRateResult.taxCharges) &&
        Objects.equals(this.totalTax, pickupCreationResponseRateResult.totalTax) &&
        Objects.equals(this.grandTotalOfAllCharge, pickupCreationResponseRateResult.grandTotalOfAllCharge) &&
        Objects.equals(this.grandTotalOfAllIncentedCharge, pickupCreationResponseRateResult.grandTotalOfAllIncentedCharge) &&
        Objects.equals(this.preTaxTotalCharge, pickupCreationResponseRateResult.preTaxTotalCharge) &&
        Objects.equals(this.preTaxTotalIncentedCharge, pickupCreationResponseRateResult.preTaxTotalIncentedCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disclaimer, rateType, currencyCode, chargeDetail, taxCharges, totalTax, grandTotalOfAllCharge, grandTotalOfAllIncentedCharge, preTaxTotalCharge, preTaxTotalIncentedCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickupCreationResponseRateResult {\n");
    
    sb.append("    disclaimer: ").append(toIndentedString(disclaimer)).append("\n");
    sb.append("    rateType: ").append(toIndentedString(rateType)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    chargeDetail: ").append(toIndentedString(chargeDetail)).append("\n");
    sb.append("    taxCharges: ").append(toIndentedString(taxCharges)).append("\n");
    sb.append("    totalTax: ").append(toIndentedString(totalTax)).append("\n");
    sb.append("    grandTotalOfAllCharge: ").append(toIndentedString(grandTotalOfAllCharge)).append("\n");
    sb.append("    grandTotalOfAllIncentedCharge: ").append(toIndentedString(grandTotalOfAllIncentedCharge)).append("\n");
    sb.append("    preTaxTotalCharge: ").append(toIndentedString(preTaxTotalCharge)).append("\n");
    sb.append("    preTaxTotalIncentedCharge: ").append(toIndentedString(preTaxTotalIncentedCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
