/*
 * Pickup
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PickupGetServiceCenterFacilitiesResponse;

/**
 * N/A  
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T10:01:45.611049100+07:00[Asia/Bangkok]")
public class PICKUPServCenterResponseWrapper {
  @JsonProperty("PickupGetServiceCenterFacilitiesResponse")
  private PickupGetServiceCenterFacilitiesResponse pickupGetServiceCenterFacilitiesResponse = null;

  public PICKUPServCenterResponseWrapper pickupGetServiceCenterFacilitiesResponse(PickupGetServiceCenterFacilitiesResponse pickupGetServiceCenterFacilitiesResponse) {
    this.pickupGetServiceCenterFacilitiesResponse = pickupGetServiceCenterFacilitiesResponse;
    return this;
  }

   /**
   * Get pickupGetServiceCenterFacilitiesResponse
   * @return pickupGetServiceCenterFacilitiesResponse
  **/
  public PickupGetServiceCenterFacilitiesResponse getPickupGetServiceCenterFacilitiesResponse() {
    return pickupGetServiceCenterFacilitiesResponse;
  }

  public void setPickupGetServiceCenterFacilitiesResponse(PickupGetServiceCenterFacilitiesResponse pickupGetServiceCenterFacilitiesResponse) {
    this.pickupGetServiceCenterFacilitiesResponse = pickupGetServiceCenterFacilitiesResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PICKUPServCenterResponseWrapper piCKUPServCenterResponseWrapper = (PICKUPServCenterResponseWrapper) o;
    return Objects.equals(this.pickupGetServiceCenterFacilitiesResponse, piCKUPServCenterResponseWrapper.pickupGetServiceCenterFacilitiesResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pickupGetServiceCenterFacilitiesResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PICKUPServCenterResponseWrapper {\n");
    
    sb.append("    pickupGetServiceCenterFacilitiesResponse: ").append(toIndentedString(pickupGetServiceCenterFacilitiesResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
