/*
 * Pickup
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PickupCreationRequestFreightOptions;
import com.ups.wwwcie.api.client.PickupCreationRequestPickupAddress;
import com.ups.wwwcie.api.client.PickupCreationRequestPickupDateInfo;
import com.ups.wwwcie.api.client.PickupCreationRequestPickupPiece;
import com.ups.wwwcie.api.client.PickupCreationRequestRequest;
import com.ups.wwwcie.api.client.PickupCreationRequestShipper;
import com.ups.wwwcie.api.client.PickupCreationRequestTotalWeight;
import com.ups.wwwcie.api.client.PickupCreationRequestTrackingData;
import com.ups.wwwcie.api.client.PickupCreationRequestTrackingDataWithReferenceNumber;

import java.util.ArrayList;
import java.util.List;
/**
 * This request is for scheduling an on-call pickup
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T10:01:45.611049100+07:00[Asia/Bangkok]")
public class PickupCreationRequest {
  @JsonProperty("Request")
  private PickupCreationRequestRequest request = null;

  @JsonProperty("RatePickupIndicator")
  private String ratePickupIndicator = null;

  @JsonProperty("TaxInformationIndicator")
  private String taxInformationIndicator = null;

  @JsonProperty("UserLevelDiscountIndicator")
  private String userLevelDiscountIndicator = null;

  @JsonProperty("Shipper")
  private PickupCreationRequestShipper shipper = null;

  @JsonProperty("PickupDateInfo")
  private PickupCreationRequestPickupDateInfo pickupDateInfo = null;

  @JsonProperty("PickupAddress")
  private PickupCreationRequestPickupAddress pickupAddress = null;

  @JsonProperty("AlternateAddressIndicator")
  private String alternateAddressIndicator = null;

  @JsonProperty("PickupPiece")
  private List<PickupCreationRequestPickupPiece> pickupPiece = new ArrayList<>();

  @JsonProperty("TotalWeight")
  private PickupCreationRequestTotalWeight totalWeight = null;

  @JsonProperty("OverweightIndicator")
  private String overweightIndicator = null;

  @JsonProperty("TrackingData")
  private List<PickupCreationRequestTrackingData> trackingData = null;

  @JsonProperty("TrackingDataWithReferenceNumber")
  private PickupCreationRequestTrackingDataWithReferenceNumber trackingDataWithReferenceNumber = null;

  @JsonProperty("PaymentMethod")
  private String paymentMethod = null;

  @JsonProperty("SpecialInstruction")
  private String specialInstruction = null;

  @JsonProperty("ReferenceNumber")
  private String referenceNumber = null;

  @JsonProperty("FreightOptions")
  private PickupCreationRequestFreightOptions freightOptions = null;

  @JsonProperty("ServiceCategory")
  private String serviceCategory = null;

  @JsonProperty("CashType")
  private String cashType = null;

  @JsonProperty("ShippingLabelsAvailable")
  private String shippingLabelsAvailable = null;

  public PickupCreationRequest request(PickupCreationRequestRequest request) {
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  public PickupCreationRequestRequest getRequest() {
    return request;
  }

  public void setRequest(PickupCreationRequestRequest request) {
    this.request = request;
  }

  public PickupCreationRequest ratePickupIndicator(String ratePickupIndicator) {
    this.ratePickupIndicator = ratePickupIndicator;
    return this;
  }

   /**
   * Indicates whether to rate the on-callpickup or not.  Valid values: Y &#x3D; Rate this pickup N &#x3D; Do not rate this pickup (default)
   * @return ratePickupIndicator
  **/
  public String getRatePickupIndicator() {
    return ratePickupIndicator;
  }

  public void setRatePickupIndicator(String ratePickupIndicator) {
    this.ratePickupIndicator = ratePickupIndicator;
  }

  public PickupCreationRequest taxInformationIndicator(String taxInformationIndicator) {
    this.taxInformationIndicator = taxInformationIndicator;
    return this;
  }

   /**
   * Indicates whether to return detailed taxes for the on-callpickups.  Valid values: Y &#x3D; Rate this pickup with taxes N &#x3D; Do not rate this pickup with taxes (default)
   * @return taxInformationIndicator
  **/
  public String getTaxInformationIndicator() {
    return taxInformationIndicator;
  }

  public void setTaxInformationIndicator(String taxInformationIndicator) {
    this.taxInformationIndicator = taxInformationIndicator;
  }

  public PickupCreationRequest userLevelDiscountIndicator(String userLevelDiscountIndicator) {
    this.userLevelDiscountIndicator = userLevelDiscountIndicator;
    return this;
  }

   /**
   * Indicates whether to return user level promo discount for the on-callpickups.  Valid values: Y &#x3D; Rate this pickup with user level promo discount N &#x3D; Do not rate this pickup with user level promo discount(default)
   * @return userLevelDiscountIndicator
  **/
  public String getUserLevelDiscountIndicator() {
    return userLevelDiscountIndicator;
  }

  public void setUserLevelDiscountIndicator(String userLevelDiscountIndicator) {
    this.userLevelDiscountIndicator = userLevelDiscountIndicator;
  }

  public PickupCreationRequest shipper(PickupCreationRequestShipper shipper) {
    this.shipper = shipper;
    return this;
  }

   /**
   * Get shipper
   * @return shipper
  **/
  public PickupCreationRequestShipper getShipper() {
    return shipper;
  }

  public void setShipper(PickupCreationRequestShipper shipper) {
    this.shipper = shipper;
  }

  public PickupCreationRequest pickupDateInfo(PickupCreationRequestPickupDateInfo pickupDateInfo) {
    this.pickupDateInfo = pickupDateInfo;
    return this;
  }

   /**
   * Get pickupDateInfo
   * @return pickupDateInfo
  **/
  public PickupCreationRequestPickupDateInfo getPickupDateInfo() {
    return pickupDateInfo;
  }

  public void setPickupDateInfo(PickupCreationRequestPickupDateInfo pickupDateInfo) {
    this.pickupDateInfo = pickupDateInfo;
  }

  public PickupCreationRequest pickupAddress(PickupCreationRequestPickupAddress pickupAddress) {
    this.pickupAddress = pickupAddress;
    return this;
  }

   /**
   * Get pickupAddress
   * @return pickupAddress
  **/
  public PickupCreationRequestPickupAddress getPickupAddress() {
    return pickupAddress;
  }

  public void setPickupAddress(PickupCreationRequestPickupAddress pickupAddress) {
    this.pickupAddress = pickupAddress;
  }

  public PickupCreationRequest alternateAddressIndicator(String alternateAddressIndicator) {
    this.alternateAddressIndicator = alternateAddressIndicator;
    return this;
  }

   /**
   * Indicates if pickup address is a different address than that specified in a customer&#x27;s profile.  Valid values: Y &#x3D; Alternate address N &#x3D; Original pickup address (default)
   * @return alternateAddressIndicator
  **/
  public String getAlternateAddressIndicator() {
    return alternateAddressIndicator;
  }

  public void setAlternateAddressIndicator(String alternateAddressIndicator) {
    this.alternateAddressIndicator = alternateAddressIndicator;
  }

  public PickupCreationRequest pickupPiece(List<PickupCreationRequestPickupPiece> pickupPiece) {
    this.pickupPiece = pickupPiece;
    return this;
  }

  public PickupCreationRequest addPickupPieceItem(PickupCreationRequestPickupPiece pickupPieceItem) {
    this.pickupPiece.add(pickupPieceItem);
    return this;
  }

   /**
   * Get pickupPiece
   * @return pickupPiece
  **/
  public List<PickupCreationRequestPickupPiece> getPickupPiece() {
    return pickupPiece;
  }

  public void setPickupPiece(List<PickupCreationRequestPickupPiece> pickupPiece) {
    this.pickupPiece = pickupPiece;
  }

  public PickupCreationRequest totalWeight(PickupCreationRequestTotalWeight totalWeight) {
    this.totalWeight = totalWeight;
    return this;
  }

   /**
   * Get totalWeight
   * @return totalWeight
  **/
  public PickupCreationRequestTotalWeight getTotalWeight() {
    return totalWeight;
  }

  public void setTotalWeight(PickupCreationRequestTotalWeight totalWeight) {
    this.totalWeight = totalWeight;
  }

  public PickupCreationRequest overweightIndicator(String overweightIndicator) {
    this.overweightIndicator = overweightIndicator;
    return this;
  }

   /**
   * Indicates if at least any package is over 70 lbs or 32 kgs.  Valid values:  Y &#x3D; Over weight  N &#x3D; Not over weight (default)  Not required for WWEF service.
   * @return overweightIndicator
  **/
  public String getOverweightIndicator() {
    return overweightIndicator;
  }

  public void setOverweightIndicator(String overweightIndicator) {
    this.overweightIndicator = overweightIndicator;
  }

  public PickupCreationRequest trackingData(List<PickupCreationRequestTrackingData> trackingData) {
    this.trackingData = trackingData;
    return this;
  }

  public PickupCreationRequest addTrackingDataItem(PickupCreationRequestTrackingData trackingDataItem) {
    if (this.trackingData == null) {
      this.trackingData = new ArrayList<>();
    }
    this.trackingData.add(trackingDataItem);
    return this;
  }

   /**
   * Get trackingData
   * @return trackingData
  **/
  public List<PickupCreationRequestTrackingData> getTrackingData() {
    return trackingData;
  }

  public void setTrackingData(List<PickupCreationRequestTrackingData> trackingData) {
    this.trackingData = trackingData;
  }

  public PickupCreationRequest trackingDataWithReferenceNumber(PickupCreationRequestTrackingDataWithReferenceNumber trackingDataWithReferenceNumber) {
    this.trackingDataWithReferenceNumber = trackingDataWithReferenceNumber;
    return this;
  }

   /**
   * Get trackingDataWithReferenceNumber
   * @return trackingDataWithReferenceNumber
  **/
  public PickupCreationRequestTrackingDataWithReferenceNumber getTrackingDataWithReferenceNumber() {
    return trackingDataWithReferenceNumber;
  }

  public void setTrackingDataWithReferenceNumber(PickupCreationRequestTrackingDataWithReferenceNumber trackingDataWithReferenceNumber) {
    this.trackingDataWithReferenceNumber = trackingDataWithReferenceNumber;
  }

  public PickupCreationRequest paymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * The payment method to pay for this on call pickup. 00 &#x3D; No payment needed 01 &#x3D; Pay by shipper account 03 &#x3D; Pay by charge card 04 &#x3D; Pay by 1Z tracking number 05 &#x3D; Pay by check or money order 06 &#x3D; Cash(applicable only for these countries - BE,FR,DE,IT,MX,NL,PL,ES,GB,CZ,HU,FI,NO) 07&#x3D;Pay by PayPal Refer to Appendix # for valid payment methods for CZ, HU, FI and NO   For countries and (or) zip codes where pickup is free of charge, please submit 00, means no payment needed as payment method.  - If 01 is the payment method, then ShipperAccountNumber and ShipperAccount CountryCode must be provided. - If 03 is selected, then CreditCard information should be provided. - If 04 is selected, then the shipper agreed to pay for the pickup packages. - If 05 is selected, then the shipper will pay for the pickup packages with a check or money order.
   * @return paymentMethod
  **/
  public String getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public PickupCreationRequest specialInstruction(String specialInstruction) {
    this.specialInstruction = specialInstruction;
    return this;
  }

   /**
   * Special handling instruction from the customer
   * @return specialInstruction
  **/
  public String getSpecialInstruction() {
    return specialInstruction;
  }

  public void setSpecialInstruction(String specialInstruction) {
    this.specialInstruction = specialInstruction;
  }

  public PickupCreationRequest referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * Information entered by a customer for Privileged reference
   * @return referenceNumber
  **/
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public PickupCreationRequest freightOptions(PickupCreationRequestFreightOptions freightOptions) {
    this.freightOptions = freightOptions;
    return this;
  }

   /**
   * Get freightOptions
   * @return freightOptions
  **/
  public PickupCreationRequestFreightOptions getFreightOptions() {
    return freightOptions;
  }

  public void setFreightOptions(PickupCreationRequestFreightOptions freightOptions) {
    this.freightOptions = freightOptions;
  }

  public PickupCreationRequest serviceCategory(String serviceCategory) {
    this.serviceCategory = serviceCategory;
    return this;
  }

   /**
   * Service Category. Applicable to the following countries: BE, FR, DE, IT, MX, NL, PL, ES, GB  Valid values:  01 - domestic (default) 02 - international 03 - transborder
   * @return serviceCategory
  **/
  public String getServiceCategory() {
    return serviceCategory;
  }

  public void setServiceCategory(String serviceCategory) {
    this.serviceCategory = serviceCategory;
  }

  public PickupCreationRequest cashType(String cashType) {
    this.cashType = cashType;
    return this;
  }

   /**
   * Describes the type of cash funds that the driver will collect. Applicable to the following countries: BE,FR,DE,IT,MX,NL,PL,ES,GB Valid values:  01 - Pickup only (default) 02 - Transportation only 03 - Pickup and Transportation
   * @return cashType
  **/
  public String getCashType() {
    return cashType;
  }

  public void setCashType(String cashType) {
    this.cashType = cashType;
  }

  public PickupCreationRequest shippingLabelsAvailable(String shippingLabelsAvailable) {
    this.shippingLabelsAvailable = shippingLabelsAvailable;
    return this;
  }

   /**
   * This element should be set to �Y� in the request to indicate that user has pre-printed shipping labels for all the packages, otherwise this will be treated as false.
   * @return shippingLabelsAvailable
  **/
  public String getShippingLabelsAvailable() {
    return shippingLabelsAvailable;
  }

  public void setShippingLabelsAvailable(String shippingLabelsAvailable) {
    this.shippingLabelsAvailable = shippingLabelsAvailable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickupCreationRequest pickupCreationRequest = (PickupCreationRequest) o;
    return Objects.equals(this.request, pickupCreationRequest.request) &&
        Objects.equals(this.ratePickupIndicator, pickupCreationRequest.ratePickupIndicator) &&
        Objects.equals(this.taxInformationIndicator, pickupCreationRequest.taxInformationIndicator) &&
        Objects.equals(this.userLevelDiscountIndicator, pickupCreationRequest.userLevelDiscountIndicator) &&
        Objects.equals(this.shipper, pickupCreationRequest.shipper) &&
        Objects.equals(this.pickupDateInfo, pickupCreationRequest.pickupDateInfo) &&
        Objects.equals(this.pickupAddress, pickupCreationRequest.pickupAddress) &&
        Objects.equals(this.alternateAddressIndicator, pickupCreationRequest.alternateAddressIndicator) &&
        Objects.equals(this.pickupPiece, pickupCreationRequest.pickupPiece) &&
        Objects.equals(this.totalWeight, pickupCreationRequest.totalWeight) &&
        Objects.equals(this.overweightIndicator, pickupCreationRequest.overweightIndicator) &&
        Objects.equals(this.trackingData, pickupCreationRequest.trackingData) &&
        Objects.equals(this.trackingDataWithReferenceNumber, pickupCreationRequest.trackingDataWithReferenceNumber) &&
        Objects.equals(this.paymentMethod, pickupCreationRequest.paymentMethod) &&
        Objects.equals(this.specialInstruction, pickupCreationRequest.specialInstruction) &&
        Objects.equals(this.referenceNumber, pickupCreationRequest.referenceNumber) &&
        Objects.equals(this.freightOptions, pickupCreationRequest.freightOptions) &&
        Objects.equals(this.serviceCategory, pickupCreationRequest.serviceCategory) &&
        Objects.equals(this.cashType, pickupCreationRequest.cashType) &&
        Objects.equals(this.shippingLabelsAvailable, pickupCreationRequest.shippingLabelsAvailable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, ratePickupIndicator, taxInformationIndicator, userLevelDiscountIndicator, shipper, pickupDateInfo, pickupAddress, alternateAddressIndicator, pickupPiece, totalWeight, overweightIndicator, trackingData, trackingDataWithReferenceNumber, paymentMethod, specialInstruction, referenceNumber, freightOptions, serviceCategory, cashType, shippingLabelsAvailable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickupCreationRequest {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    ratePickupIndicator: ").append(toIndentedString(ratePickupIndicator)).append("\n");
    sb.append("    taxInformationIndicator: ").append(toIndentedString(taxInformationIndicator)).append("\n");
    sb.append("    userLevelDiscountIndicator: ").append(toIndentedString(userLevelDiscountIndicator)).append("\n");
    sb.append("    shipper: ").append(toIndentedString(shipper)).append("\n");
    sb.append("    pickupDateInfo: ").append(toIndentedString(pickupDateInfo)).append("\n");
    sb.append("    pickupAddress: ").append(toIndentedString(pickupAddress)).append("\n");
    sb.append("    alternateAddressIndicator: ").append(toIndentedString(alternateAddressIndicator)).append("\n");
    sb.append("    pickupPiece: ").append(toIndentedString(pickupPiece)).append("\n");
    sb.append("    totalWeight: ").append(toIndentedString(totalWeight)).append("\n");
    sb.append("    overweightIndicator: ").append(toIndentedString(overweightIndicator)).append("\n");
    sb.append("    trackingData: ").append(toIndentedString(trackingData)).append("\n");
    sb.append("    trackingDataWithReferenceNumber: ").append(toIndentedString(trackingDataWithReferenceNumber)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    specialInstruction: ").append(toIndentedString(specialInstruction)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    freightOptions: ").append(toIndentedString(freightOptions)).append("\n");
    sb.append("    serviceCategory: ").append(toIndentedString(serviceCategory)).append("\n");
    sb.append("    cashType: ").append(toIndentedString(cashType)).append("\n");
    sb.append("    shippingLabelsAvailable: ").append(toIndentedString(shippingLabelsAvailable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
