/*
 * PreNotification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Container to hold UnitOfMeasurement information for package weight.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:38.808862600+07:00[Asia/Bangkok]")
public class PackageWeightUnitOfMeasurement {
  @JsonProperty("Code")
  private String code = null;

  @JsonProperty("Description")
  private String description = null;

  public PackageWeightUnitOfMeasurement code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Package weight unit of measurement code.  Codes are:  LBS &#x3D; Pounds KGS &#x3D; Kilograms
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public PackageWeightUnitOfMeasurement description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the unit of measurement for package weight.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageWeightUnitOfMeasurement packageWeightUnitOfMeasurement = (PackageWeightUnitOfMeasurement) o;
    return Objects.equals(this.code, packageWeightUnitOfMeasurement.code) &&
        Objects.equals(this.description, packageWeightUnitOfMeasurement.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageWeightUnitOfMeasurement {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
