/*
 * PreNotification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PreNotificationRequest;

/**
 * N/A  
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:38.808862600+07:00[Asia/Bangkok]")
public class PRENOTIFICATIONRequestWrapper {
  @JsonProperty("PreNotificationRequest")
  private PreNotificationRequest preNotificationRequest = null;

  public PRENOTIFICATIONRequestWrapper preNotificationRequest(PreNotificationRequest preNotificationRequest) {
    this.preNotificationRequest = preNotificationRequest;
    return this;
  }

   /**
   * Get preNotificationRequest
   * @return preNotificationRequest
  **/
  public PreNotificationRequest getPreNotificationRequest() {
    return preNotificationRequest;
  }

  public void setPreNotificationRequest(PreNotificationRequest preNotificationRequest) {
    this.preNotificationRequest = preNotificationRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PRENOTIFICATIONRequestWrapper prENOTIFICATIONRequestWrapper = (PRENOTIFICATIONRequestWrapper) o;
    return Objects.equals(this.preNotificationRequest, prENOTIFICATIONRequestWrapper.preNotificationRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preNotificationRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PRENOTIFICATIONRequestWrapper {\n");
    
    sb.append("    preNotificationRequest: ").append(toIndentedString(preNotificationRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
