/*
 * PreNotification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ups.wwwcie.api.client.PreNotificationRequestRequest;
import com.ups.wwwcie.api.client.PreNotificationRequestShipment;

/**
 * Pre-Notification Request.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:38.808862600+07:00[Asia/Bangkok]")
public class PreNotificationRequest {
  @JsonProperty("Request")
  private PreNotificationRequestRequest request = null;

  @JsonProperty("Shipment")
  private PreNotificationRequestShipment shipment = null;

  public PreNotificationRequest request(PreNotificationRequestRequest request) {
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  public PreNotificationRequestRequest getRequest() {
    return request;
  }

  public void setRequest(PreNotificationRequestRequest request) {
    this.request = request;
  }

  public PreNotificationRequest shipment(PreNotificationRequestShipment shipment) {
    this.shipment = shipment;
    return this;
  }

   /**
   * Get shipment
   * @return shipment
  **/
  public PreNotificationRequestShipment getShipment() {
    return shipment;
  }

  public void setShipment(PreNotificationRequestShipment shipment) {
    this.shipment = shipment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreNotificationRequest preNotificationRequest = (PreNotificationRequest) o;
    return Objects.equals(this.request, preNotificationRequest.request) &&
        Objects.equals(this.shipment, preNotificationRequest.shipment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, shipment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreNotificationRequest {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    shipment: ").append(toIndentedString(shipment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
