/*
 * PreNotification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ups.wwwcie.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Ship From address container.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-07T15:43:38.808862600+07:00[Asia/Bangkok]")
public class ShipmentShipFromAddress {
  @JsonProperty("AddressLine")
  private List<String> addressLine = new ArrayList<>();

  @JsonProperty("City")
  private String city = null;

  @JsonProperty("StateProvinceCode")
  private String stateProvinceCode = null;

  @JsonProperty("PostalCode")
  private String postalCode = null;

  @JsonProperty("CountryCode")
  private String countryCode = null;

  public ShipmentShipFromAddress addressLine(List<String> addressLine) {
    this.addressLine = addressLine;
    return this;
  }

  public ShipmentShipFromAddress addAddressLineItem(String addressLineItem) {
    this.addressLine.add(addressLineItem);
    return this;
  }

   /**
   * The Ship From street address including name and number (when applicable).
   * @return addressLine
  **/
  public List<String> getAddressLine() {
    return addressLine;
  }

  public void setAddressLine(List<String> addressLine) {
    this.addressLine = addressLine;
  }

  public ShipmentShipFromAddress city(String city) {
    this.city = city;
    return this;
  }

   /**
   * The Ship From city.
   * @return city
  **/
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public ShipmentShipFromAddress stateProvinceCode(String stateProvinceCode) {
    this.stateProvinceCode = stateProvinceCode;
    return this;
  }

   /**
   * The Ship From location&#x27;s state or province code.
   * @return stateProvinceCode
  **/
  public String getStateProvinceCode() {
    return stateProvinceCode;
  }

  public void setStateProvinceCode(String stateProvinceCode) {
    this.stateProvinceCode = stateProvinceCode;
  }

  public ShipmentShipFromAddress postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The Ship From location&#x27;s postal code. 9 characters are accepted.
   * @return postalCode
  **/
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public ShipmentShipFromAddress countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * The Ship From location&#x27;s country or territory code.
   * @return countryCode
  **/
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentShipFromAddress shipmentShipFromAddress = (ShipmentShipFromAddress) o;
    return Objects.equals(this.addressLine, shipmentShipFromAddress.addressLine) &&
        Objects.equals(this.city, shipmentShipFromAddress.city) &&
        Objects.equals(this.stateProvinceCode, shipmentShipFromAddress.stateProvinceCode) &&
        Objects.equals(this.postalCode, shipmentShipFromAddress.postalCode) &&
        Objects.equals(this.countryCode, shipmentShipFromAddress.countryCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressLine, city, stateProvinceCode, postalCode, countryCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentShipFromAddress {\n");
    
    sb.append("    addressLine: ").append(toIndentedString(addressLine)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateProvinceCode: ").append(toIndentedString(stateProvinceCode)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
